### PR TITLE
Implement get_resolved_value.

### PR DESCRIPTION
**Pull request by jgfouca**

### CODE REVIEW

**Comment by jedwards4b** [comment]
We got some issues to work out here.   I don't like all the ### around the subroutine names, it's just noise to me.   And you changed all of the subroutine names, why did you do that?

**Comment by jgfouca** [comment]
That's been the coding style for all the Python in CIME. It's a personal preference of mine that, since python only uses whitespace to identify code blocks, functions don't jump out at me enough without the ###.

As far as the renames, ThisName is generally not the format used for functions in python, that format is reserved for class names.

**Comment by jedwards4b** [comment]
I'll let you rename the functions if you let me get rid of the comment noise.

**Comment by jgfouca** [comment]
Well, this opens up a can worms regarding coding conventions. I'm not sure we want the code to look differently from one CIME file to the next, so we need to agree on something. The way this file looks currently is at least consistent with the rest of the code base. Can we just continue that for now until we agree on something else?

As far as the names, FunctionName is not pythonic and is even flagged by some python code checkers (pylint), so that's not really a concession.

**Comment by gold2718** [comment]
Please don't take out end-of-block comments. These are placeholders which provide a visual indication of where the block ends (similar to a close curly brace in other languages).
My python lexer* uses these to identify blocks and to be able to fix broken blocks which have been attacked by a rouge editor indentation algorithm.

*aka these tires old eyes of mine

**Comment by jedwards4b** [comment]
Can I appeal to the standard here https://www.python.org/dev/peps/pep-0008/#blank-lines  they refer to blank lines around subroutines but I can't find any reference to a line full of # signs.

**Comment by gold2718** [comment]
I agree with Jim F. on function names. I also have a specific request for end-of-block convention (see below) but perhaps this should be its own issue for CIME?

This is how I use block-ending comments in my code:
if (test):
    code
   while (condition):
      more code
    # End while
# End if

**Comment by jedwards4b** [comment]
i don't think that's what you meant

**Comment by rljacob** [comment]
meta convention:  when adding to an existing code base, follow the existing convention.

**Comment by jedwards4b** [comment]
Jim - I don't think that your get_resolved_value will work in the general case - what if the retreved value has another reference in it?   It needs to be recursive.

**Comment by bandre-ucar** [comment]
I second pep8. Since we are basically starting a new code base, it should
all follow the pep8 convention. Most of the whitespace related issues can
trivially be resolved by running autopep8 on the code base.

https://pypi.python.org/pypi/autopep8

**Comment by rljacob** [comment]
Can is opened.  Please continue on a separate issue: #47

**Comment by jedwards4b** [comment]
Hi Jim,

Back to the main topic - I've integrated the get_default_value with branch
oopy
on my fork and added a small test to the python/utils/tests subdirectory
this test should get the resolved value of the machines file from the
config_files.xml file.   The unresolved value is

$CIMEROOT/cime_config/$MODEL/machines/config_machines.xml

get_resolved_value is returning

CIMEROOT/cime_config/MODEL/machines/config_machines.xml





On Mon, Jan 25, 2016 at 3:13 PM, Robert Jacob <notifications@github.com>
wrote:

> Can is opened. Please continue on a separate issue: #47
> <https://github.com/ESMCI/cime/issues/47>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ESMCI/cime/pull/46#issuecomment-174691626>.
>



-- 
Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by bertinia** [comment]
Here's some code that I wrote for the postprocessing that recursively
resolves env. var names.
You can call functional readXML with a casedir path and a list of xml files
with id/value pair entries to be resolved.

One thing I had to do for the diags was to accommodate that case where an
env var needed to be expanded
within another string. In this case, I used ($VAR) to delineate. For
example:


      <entry id="OCN_GRID"                                  value="gx1v6">
      <entry id="OCNDIAG_TOBSFILE_V42"
value="PHC2_TEMP_($OCN_GRID)_42lev_ann_avg.nc">

when resolved recursively, will set OCNDIAG_TOBSFILE_V42 =
"PHC2_TEMP_gx1v6_42lev_ann_avg.nc"

We can add something like this to the util lib.


****************************************

re_val = re.compile(r'\$(\{([A-Za-z0-9_]+)\}|[A-Za-z0-9_]+)')

#==============================================================================



# expand recursive function



#==============================================================================



def expand (val, src):

  """



  Recursively traverse the environment dictionary to expand all environment
variables






  Arguments



  val (string) - value to be expanded



  src (dictionary) -  source dictionary to search and resolve param val







  Return



  expanded value



  """

  return re_val.sub(lambda m: expand(src.get(m.group(1), ''), src), val)


#==============================================================================



# readXML - read and resolve an XML input file against a source directory



#==============================================================================



def readXML(casedir, env_file_list):

  """



  for the <entry id=value> xml files in casedir/env_file_list,



  returns a dictionary output["id"]="value"







  Arguments:



  casedir (string) - case root directory



  env_file_list - list of env_*.xml files to parse in the casedir







  Return:



  output (dictionary)



  """

  output = os.environ.copy()

  for efile in env_file_list:

    env_file = '{0}/{1}'.format(casedir, efile)

    if os.path.isfile(env_file):

      xml_tree = ET.ElementTree()

      xml_tree.parse(env_file)

      for entry_tag in xml_tree.findall('entry'):

        output[entry_tag.get('id')] = entry_tag.get('value')

    else:

      err_msg = 'cesmEnvLib.readXML ERROR: {0} does not exist or cannot be
read'.format(env_file)

      raise TypeError(err_msg)


  # expand nested environment variables



  for k,v in output.iteritems():

    output[k] = expand(v, output)


  # remove () in output dictionary values



  for k,v in output.iteritems():

    output[k] = re.sub('[()]', '', v)


  return output


On Mon, Jan 25, 2016 at 3:32 PM, jedwards4b <notifications@github.com>
wrote:

> Hi Jim,
>
> Back to the main topic - I've integrated the get_default_value with branch
> oopy
> on my fork and added a small test to the python/utils/tests subdirectory
> this test should get the resolved value of the machines file from the
> config_files.xml file. The unresolved value is
>
> $CIMEROOT/cime_config/$MODEL/machines/config_machines.xml
>
> get_resolved_value is returning
>
> CIMEROOT/cime_config/MODEL/machines/config_machines.xml
>
>
>
>
>
> On Mon, Jan 25, 2016 at 3:13 PM, Robert Jacob <notifications@github.com>
> wrote:
>
> > Can is opened. Please continue on a separate issue: #47
> > <https://github.com/ESMCI/cime/issues/47>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ESMCI/cime/pull/46#issuecomment-174691626>.
> >
>
>
>
> --
> Jim Edwards
>
> CESM Software Engineer
> National Center for Atmospheric Research
> Boulder, CO
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ESMCI/cime/pull/46#issuecomment-174701654>.
>



-- 
Alice Bertini
NCAR - CSEG Software Engineer

**Comment by jedwards4b** [comment]
Alice we had a convention of ${ } for that already.  Can you switch so that
we are consistent?

On Mon, Jan 25, 2016 at 3:48 PM, Alice Bertini <notifications@github.com>
wrote:

> Here's some code that I wrote for the postprocessing that recursively
> resolves env. var names.
> You can call functional readXML with a casedir path and a list of xml files
> with id/value pair entries to be resolved.
>
> One thing I had to do for the diags was to accommodate that case where an
> env var needed to be expanded
> within another string. In this case, I used ($VAR) to delineate. For
> example:
>
>
> <entry id="OCN_GRID" value="gx1v6">
> <entry id="OCNDIAG_TOBSFILE_V42"
> value="PHC2_TEMP_($OCN_GRID)_42lev_ann_avg.nc">
>
> when resolved recursively, will set OCNDIAG_TOBSFILE_V42 =
> "PHC2_TEMP_gx1v6_42lev_ann_avg.nc"
>
> We can add something like this to the util lib.
>
>
> ****************************************
>
> re_val = re.compile(r'\$(\{([A-Za-z0-9_]+)\}|[A-Za-z0-9_]+)')
>
>
> #==============================================================================
>
>
>
> # expand recursive function
>
>
>
>
> #==============================================================================
>
>
>
> def expand (val, src):
>
> """
>
>
>
> Recursively traverse the environment dictionary to expand all environment
> variables
>
>
>
>
>
>
> Arguments
>
>
>
> val (string) - value to be expanded
>
>
>
> src (dictionary) - source dictionary to search and resolve param val
>
>
>
>
>
>
>
> Return
>
>
>
> expanded value
>
>
>
> """
>
> return re_val.sub(lambda m: expand(src.get(m.group(1), ''), src), val)
>
>
>
> #==============================================================================
>
>
>
> # readXML - read and resolve an XML input file against a source directory
>
>
>
>
> #==============================================================================
>
>
>
> def readXML(casedir, env_file_list):
>
> """
>
>
>
> for the <entry id=value> xml files in casedir/env_file_list,
>
>
>
> returns a dictionary output["id"]="value"
>
>
>
>
>
>
>
> Arguments:
>
>
>
> casedir (string) - case root directory
>
>
>
> env_file_list - list of env_*.xml files to parse in the casedir
>
>
>
>
>
>
>
> Return:
>
>
>
> output (dictionary)
>
>
>
> """
>
> output = os.environ.copy()
>
> for efile in env_file_list:
>
> env_file = '{0}/{1}'.format(casedir, efile)
>
> if os.path.isfile(env_file):
>
> xml_tree = ET.ElementTree()
>
> xml_tree.parse(env_file)
>
> for entry_tag in xml_tree.findall('entry'):
>
> output[entry_tag.get('id')] = entry_tag.get('value')
>
> else:
>
> err_msg = 'cesmEnvLib.readXML ERROR: {0} does not exist or cannot be
> read'.format(env_file)
>
> raise TypeError(err_msg)
>
>
> # expand nested environment variables
>
>
>
> for k,v in output.iteritems():
>
> output[k] = expand(v, output)
>
>
> # remove () in output dictionary values
>
>
>
> for k,v in output.iteritems():
>
> output[k] = re.sub('[()]', '', v)
>
>
> return output
>
>
> On Mon, Jan 25, 2016 at 3:32 PM, jedwards4b <notifications@github.com>
> wrote:
>
> > Hi Jim,
> >
> > Back to the main topic - I've integrated the get_default_value with
> branch
> > oopy
> > on my fork and added a small test to the python/utils/tests subdirectory
> > this test should get the resolved value of the machines file from the
> > config_files.xml file. The unresolved value is
> >
> > $CIMEROOT/cime_config/$MODEL/machines/config_machines.xml
> >
> > get_resolved_value is returning
> >
> > CIMEROOT/cime_config/MODEL/machines/config_machines.xml
> >
> >
> >
> >
> >
> > On Mon, Jan 25, 2016 at 3:13 PM, Robert Jacob <notifications@github.com>
> > wrote:
> >
> > > Can is opened. Please continue on a separate issue: #47
> > > <https://github.com/ESMCI/cime/issues/47>
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/ESMCI/cime/pull/46#issuecomment-174691626>.
> > >
> >
> >
> >
> > --
> > Jim Edwards
> >
> > CESM Software Engineer
> > National Center for Atmospheric Research
> > Boulder, CO
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ESMCI/cime/pull/46#issuecomment-174701654>.
> >
>
>
>
> --
> Alice Bertini
> NCAR - CSEG Software Engineer
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ESMCI/cime/pull/46#issuecomment-174709570>.
>



-- 
Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by jedwards4b** [comment]
I have this working now on my oopy branch.

On Mon, Jan 25, 2016 at 3:32 PM, Jim Edwards <jedwards@ucar.edu> wrote:

> Hi Jim,
>
> Back to the main topic - I've integrated the get_default_value with branch
> oopy
> on my fork and added a small test to the python/utils/tests subdirectory
> this test should get the resolved value of the machines file from the
> config_files.xml file.   The unresolved value is
>
> $CIMEROOT/cime_config/$MODEL/machines/config_machines.xml
>
> get_resolved_value is returning
>
> CIMEROOT/cime_config/MODEL/machines/config_machines.xml
>
>
>
>
>
> On Mon, Jan 25, 2016 at 3:13 PM, Robert Jacob <notifications@github.com>
> wrote:
>
>> Can is opened. Please continue on a separate issue: #47
>> <https://github.com/ESMCI/cime/issues/47>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ESMCI/cime/pull/46#issuecomment-174691626>.
>>
>
>
>
> --
> Jim Edwards
>
> CESM Software Engineer
> National Center for Atmospheric Research
> Boulder, CO
>



-- 
Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by jedwards4b** [comment]
I've merged this with my oopy branch which integrates it with the create_test and open a new pull request with both pieces tomorrow - is that okay?

**Comment by jgfouca** [comment]
Thanks for adding a test. I also added a simple doctest for the function.

**Comment by jgfouca** [comment]
Yes, go ahead and do whatever you want with the PR.

**Pull request closed without merging**
