### PR TITLE
create_test: Add --force-procs and --force-threads options

### LINKED ISSUE #897: Need support for TEST specifiers in config_pes.xml
Previously, it was possible to define test-specific PE layouts: e.g.
```
<pes MACH="cetus" TEST="^.+$">
<NTASKS_ATM>64</NTASKS_ATM> <NTHRDS_ATM>16</NTHRDS_ATM> <ROOTPE_ATM>0</ROOTPE_ATM>
...
```

The new PE XML appears to support only machine, compset, grid, pesize tags. Is there a specifier for tests?

### PR DESCRIPTION
**Pull request by jgfouca**
Allows user to force procs and threads withouth having to change test names.

Also, refactors case.py handling of pecount to allow for user to force threads
without having to change procs.

Test suite: scripts_regression_tests
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes #897 

User interface changes?: Yes, adds pecount force options to create_test

Code review: @jedwards4b

### CODE REVIEW

**Comment by rljacob** [comment]
Why is "--force" needed?   Can it just be --procs --threads with the rule that command line options override what's in config_pes?

**Comment by jgfouca** [comment]
@rljacob , that would be fine. I guess my mind registered these flags as pretty "strong" demands by the user since the proc/threads will get applied to all tests and hence should not be used lightly. If you feel strongly I can make a new PR.

**Comment by jedwards4b** [comment]
Please refer to the discussion on this topic in issue #1016

**Comment by jedwards4b** [comment]
Sorry I had the wrong issue - should have been #1017

**Pull request merged**
