### PR TITLE
updated machine config for titan

### LINKED ISSUE #280: Git CIME5 working on Titan

### PR DESCRIPTION
**Pull request by wilke**
Titan machine config

Test suite: 
Test baseline: 
Test namelist changes: 
Test status: [bit for bit, roundoff, climate changing]

Fixes #280

User interface changes?: 

Code review:

### CODE REVIEW

**Comment by rljacob** [comment]
Tagging @mrnorman

**Comment by rljacob** [comment]
Why change the name from pgi_acc to pgiacc?

**Comment by sarich** [comment]
using '_' in the compiler name breaks create_test, it uses '_' as a parsing
tool

**Comment by rljacob** [comment]
Ok.  This looks good to me.

**Comment by sarich** [comment]
case.sh needs to be removed

**Comment by sarich** [comment]
Looks good on cime_developer except for SMS_D_Ln9_Mmpi_serial.f19_g16_rx1.A.titan_pgiacc (linking to Fortran libraries from C fails)
Will merge this and open that as separate case

**Pull request merged**
