### PR TITLE
Update NCAR machines to use Intel version 17

### LINKED ISSUE #1982: Intel 15 fails on new CAM-SE
When running with the new CAM-SE dycore, Intel 15 produces runtime errors on what appears to be correct code. Nag has no problem with this code (with or without DEBUG).
This problem currently manifests on Yellowstone and Hobart.
I feel the solution is to update supported machines to Intel 17.

### PR DESCRIPTION
**Pull request by gold2718**
**NB: NOT READY TO MERGE, see comment in discussion**
Update Yellowstone and Hobart to use Intel 17.

Test suite:  scripts_regression_tests.py on Yellowstone
Test baseline: NA
Test namelist changes: NA
Test status: roundoff

Fixes #1982 

User interface changes?: N

Update gh-pages html (Y/N)?: N

Code review:

### CODE REVIEW

**Comment by gold2718** [comment]
Running scripts_regression_tests.py on Yellowstone results in some failures with mostly different tests failing on different runs. The failures (cesm.log) mostly look like this:
```
Execute poe command line: poe  /glade/p/cesmdata/cseg/tools/bin/launch /glade/scratch/goldy/scripts_regression_test.20171023_153722/DAE.f19_f19.A.yellowstone_intel.fake_testing_only_20171023_162219/bld/cesm.exe
ATTENTION: 0031-393  Ignoring -resd/MP_RESD specified for batch job
ATTENTION: 0031-408  15 tasks allocated by Resource Manager, continuing...
ATTENTION: 0031-606 Unrecognized environment variable, MP_EAGER_LIMIT_LOCAL.
ERROR: 0031-758 AFFINITY: [caldera14] Oversubscribe: 15 tasks in total, each task requires 1 resource, but there are only 1 available resource. Affinity can not be applied
ERROR: 0031-161  EOF on socket connection with node caldera14-ib
INFO: 0031-639  Exit status from pm_respond = -1
```
Is this due to the change or something going on with Yellowstone?

**Comment by jedwards4b** [comment]
@gold2718 the error on yellowstone is because some of the jobs are trying to use shared nodes and the nodes do not have resources available.   You need to retry.  
That said I thought that we were not going to change the environment on yellowstone due to the possible implications for ongoing cmip experiments.

**Comment by gold2718** [comment]
@jedwards4b , can we make a new Yellowstone compiler entry (Intel17) so that we can run CAM-SE?

**Comment by jedwards4b** [comment]
yes, that would be a better way to do it.

**Comment by gold2718** [comment]
So if I run scripts_regression_tests.py a few times and each test passes at least once, is that now considered a good day on Yellowstone?

**Comment by gold2718** [comment]
Meanwhile, if I try the same fixes on Hobart, I can't seem to run anything. E.g.,
```
forrtl: severe (257): formatted I/O to unit open for unformatted transfers, unit 6, file /proc/70389/fd/1
Image              PC                Routine            Line        Source             
libnetcdff.so.6.0  00007F96FC06BBE7  for__io_return        Unknown  Unknown
libifcore.so.5     00007F96F62195B3  for_write_seq_lis     Unknown  Unknown
cesm.exe           0000000004835A78  shr_abort_mod_mp_         157  shr_abort_mod.F90
cesm.exe           0000000004835015  shr_abort_mod_mp_          59  shr_abort_mod.F90
cesm.exe           000000000044BA7D  cime_comp_mod_mp_        4102  cime_comp_mod.F90
cesm.exe           000000000040D8A4  cime_comp_mod_mp_         607  cime_comp_mod.F90
cesm.exe           000000000044C08F  MAIN__                     37  cime_driver.F90
cesm.exe           000000000040D65E  Unknown               Unknown  Unknown
libc-2.17.so       00007F96F566CB15  __libc_start_main     Unknown  Unknown
cesm.exe           000000000040D569  Unknown               Unknown  Unknown

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 70389 RUNNING AT h032.cgd.ucar.edu
=   EXIT CODE: 1
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
```
This was an attempt to call shr_sys_abort to understand an error in a call to rewind.

**Comment by jedwards4b** [comment]
This is a hobart module issue - not sure why you would post it here.

**Comment by gold2718** [comment]
Because I didn't realize that. I have no idea how to express the nature of the problem to the IS group. Any hints?

**Comment by jedwards4b** [comment]
@gold2718 are you still pursuing this or can we close this PR?

**Comment by jedwards4b** [comment]
No response from @gold2718, closing this PR.

**Comment by gold2718** [comment]
Sorry for the delay, I had to run some checks to see if the original problem went away. CAM-SE built successfully on Hobart with intel so okay to close.

**Pull request closed without merging**
