### PR TITLE
add logic for aprun for narwhal, warhawk, onyx

### PR DESCRIPTION
**Pull request by apcraig**
Add support for narwhal, warhawk, and onxy for use of aprun.

This should ultimately NOT be required for porting cime, it would be nice if whatever this piece of code is doing were generalized or fixed, so modifications per machine were not needed.

A few test cases were run on narwhal, warhawk, and onyx.

Test suite:
Test baseline:
Test namelist changes:
Test status: bit for bit

Fixes [CIME Github issue #]

User interface changes?: N

Update gh-pages html (Y/N)?: N

### CODE REVIEW

**Comment by apcraig** [comment]
See #2024

**Review by jedwards4b — CHANGES_REQUESTED** [review]
This flag is not generally needed for using aprun, it is only required on the theta system due to options needed specifically for that machine - are you sure you need it for these?   See for example machines aleph, bluewaters, gaea and swan in config_machines.xml    If you decide that you do indeed need this for those systems please be explicit about why and we will see if there is a more general way to do it.

**Comment by apcraig** [comment]
thanks @jedwards4b.  All I know is that if I don't have this mod, the scripts fail.

```
Traceback (most recent call last):
  File "./case.setup", line 106, in <module>
    _main_func(__doc__)
  File "./case.setup", line 102, in _main_func
    case.case_setup(clean=clean, test_mode=test_mode, reset=reset, keep=keep)
  File "/p/home/apcraig/E3SM/E3SM.dod-port/cime/CIME/case/case_setup.py", line 483, in case_setup
    is_batch=is_batch,
  File "/p/home/apcraig/E3SM/E3SM.dod-port/cime/CIME/utils.py", line 2433, in run_and_log_case_status
    rv = func()
  File "/p/home/apcraig/E3SM/E3SM.dod-port/cime/CIME/case/case_setup.py", line 446, in <lambda>
    self, caseroot, clean=clean, test_mode=test_mode, reset=reset, keep=keep
  File "/p/home/apcraig/E3SM/E3SM.dod-port/cime/CIME/case/case_setup.py", line 372, in _case_setup_impl
    env_batch.make_all_batch_files(case)
  File "/p/home/apcraig/E3SM/E3SM.dod-port/cime/CIME/XML/env_batch.py", line 1361, in make_all_batch_files
    self.make_batch_script(input_batch_script, job, case)
  File "/p/home/apcraig/E3SM/E3SM.dod-port/cime/CIME/XML/env_batch.py", line 232, in make_batch_script
    overrides = self.get_job_overrides(job, case)
  File "/p/home/apcraig/E3SM/E3SM.dod-port/cime/CIME/XML/env_batch.py", line 224, in get_job_overrides
    overrides["mpirun"] = case.get_mpirun_cmd(job=job, overrides=overrides)
  File "/p/home/apcraig/E3SM/E3SM.dod-port/cime/CIME/case/case.py", line 2017, in get_mpirun_cmd
    self, run_exe, overrides=overrides
  File "/p/home/apcraig/E3SM/E3SM.dod-port/cime/CIME/aprun.py", line 177, in get_aprun_cmd_for_case
    run_exe,
  File "/p/home/apcraig/E3SM/E3SM.dod-port/cime/CIME/aprun.py", line 58, in _get_aprun_cmd_for_case_impl
    tt = rootpe + (ntask - 1) * pstrid + 1
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

It could be that some different settings in config_machines or elsewhere would help, but CIME is very complicated.  Does the above error suggest I can fix this another way?

**Comment by apcraig** [comment]
Also, I cannot find aleph or the other machines in config_machines.xml.  I'm doing this in E3SM, I don't think they are there.

**Comment by jedwards4b** [comment]
This error seems to indicate that the variable ntask is being interpreted as a string instead of int.   Do you have a PR for ccs_config that you can post as a draft so that I can look at it and try to spot the issue?

**Comment by apcraig** [comment]
@jedwards4b, not sure what you're asking for, PR for css_config?

**Comment by jedwards4b** [comment]
Right those are cesm machines.   I guess I'll extract myself and let you work with the e3sm team.

**Comment by rljacob** [comment]
@apcraig point us to the branch in github that has those machine configs and we can look at it.

**Comment by apcraig** [comment]
I'm going to create a PR for these machines soon in E3SM.  My dev branch is

https://github.com/apcraig/E3SM/tree/apcraig/e3sm/dod-port

Thanks!

**Pull request closed without merging**
