### PR TITLE
Add source file feature

### LINKED ISSUE #3631: Enable source scripts in module_system
In a module system, it's useful to add `source setup_script` (e.g. `source compilervars.sh intel64`) to set up env-vars for new packages (that don't have a module to `module load package/x.y.z`). This doesn't appear to be working in current env_mach_specific.xml workflow.

### PR DESCRIPTION
**Pull request by jedwards4b**
Allows for a sh format file to be sourced and incorporated into the cime environment.  
To use it you would add an entry in the <environment_variables> section such as
```
<environment_variables>
  <env source="sh">/path/to/an/sh/shell/file</env>
</environment_variables>
```
Note that sh is the only supported format for this feature.  

Test suite: hand testing, scripts_regression_tests.py
Test baseline: 
Test namelist changes: 
Test status: bit for bit
Fixes #3631 

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by amametjanov** [comment]
Are shell script arguments supported: e.g. `source compilervars.sh intel64` when setting up intel compiler variables?

**Comment by jedwards4b** [comment]
@amametjanov I would appreciate if you could test that for me, since I"m not sure what the intent is.

**Comment by jedwards4b** [comment]
@amametjanov Yes it does support arguments.

**Comment by amametjanov** [comment]
For a case created with
```
@cori03:~/cori/repos/cime> ./scripts/create_test --no-build SMS.f19_g16.X
```
and
```
@cori03:~/cori/repos/cime> git diff
diff --git a/config/cesm/machines/config_machines.xml b/config/cesm/machines/config_machines.xml
index ab2228320..e0fa1edd0 100644
--- a/config/cesm/machines/config_machines.xml
+++ b/config/cesm/machines/config_machines.xml
@@ -846,6 +846,7 @@ This allows using a different mpirun command to launch unit tests
       <env name="OMP_STACKSIZE">256M</env>
       <env name="OMP_PROC_BIND">spread</env>
       <env name="OMP_PLACES">threads</env>
+      <env>/usr/common/software/intel/parallel_studio_xe_2020_update2_cluster_edition/compilers_and_libraries_2020.2.254/linu
x/bin/compilervars.sh intel64</env>
     </environment_variables>
   </machine>
   <machine MACH="cori-knl">
```
tail of "helper" script is
```
@cori02:/global/cscratch1/sd/azamat/SMS.f19_g16.X.cori-haswell_intel.20200825_141800_pz5f17> tail -n 2 .env_mach_specific.sh 
export OMP_PLACES=threads
export None=/usr/common/software/intel/parallel_studio_xe_2020_update2_cluster_edition/compilers_and_libraries_2020.2.254/linux/bin/compilervars.sh intel64
```
Could `export None=` be changed to `source` too?

**Comment by jedwards4b** [comment]
The line needs to be
<env source="sh">/usr/common/software/intel/parallel_studio_xe_2020_update2_cluster_edition/compilers_and_libraries_2020.2.254/linu
x/bin/compilervars.sh intel64</env>

**Comment by jedwards4b** [comment]
@amametjanov Sorry I've corrected the formatting issue in the github conversation.

**Comment by amametjanov** [comment]
Thanks for that. Still getting
```
export None=/usr/common/software/intel/parallel_studio_xe_2020_update2_cluster_edition/compilers_and_libraries_2020.2.254/linux/bin/compilervars.sh intel64
```
in .env_mach_specific.sh. Probably not important, but would be nice to just `$ source .env_mach_specific.sh` and get the right compiler.

**Comment by jedwards4b** [comment]
@amametjanov  Please try again.

**Comment by amametjanov** [comment]
Works. Thanks!

**Pull request merged**
