### PR TITLE
Improve handling of hist comparisons in TestStatus.log

### LINKED ISSUE #566: RMS failures in tests should be reported *concisely* in TestStatus.log
In cime4, RMS diffs were reported in TestStatus.log. That functionality should be brought back.

### LINKED ISSUE #1510: Log files should be more clear about cprnc comparisons
From ACME slack:

 I'm trying to confirm that our fix to the PET_Ln9.ne30_oEC.A_WCYCL2000.skybridge_intel test worked. In the log, I see only one cprnc result -- that the results are different from the baseline, which we expect. Does it pass the self-comparison? I don't see that anywhere

017-05-10 00:24:31: Comparing hists for case 'PET_Ln9.ne30_oEC.A_WCYCL2000.skybridge_intel.C.jenkins_next_20170509_231246' dir1='/gscratch/jenkins/acme_scratch/skybridge/PET_Ln9.ne30_oEC.A_WCYCL2000.skybridge_intel.C.jenkins_next_20170509_231246/run', suffix1='base',  dir2='/gscratch/jenkins/acme_scratch/skybridge/PET_Ln9.ne30_oEC.A_WCYCL2000.skybridge_intel.C.jenkins_next_20170509_231246/run' suffix2='single_thread'

[8:50] 
/gscratch/jenkins/acme_scratch/skybridge/PET_Ln9.ne30_oEC.A_WCYCL2000.skybridge_intel.C.jenkins_next_20170509_231246/run/PET_Ln9.ne30_oEC.A_WCYCL2000.skybridge_intel.C.jenkins_next_20170509_231246.cpl.hi.0001-01-01-16200.nc.base matched /gscratch/jenkins/acme_scratch/skybridge/PET_Ln9.ne30_oEC.A_WCYCL2000.skybridge_intel.C.jenkins_next_20170509_231246/run/PET_Ln9.ne30_oEC.A_WCYCL2000.skybridge_intel.C.jenkins_next_20170509_231246.cpl.hi.0001-01-01-16200.nc.single_thread

Jon Wolfe [8:50 AM] 
I had just searched for cprnc, which spits out the results in a long format. Most of the logs have that output

Mark Taylor [8:51 AM] 
it would provide more confidence if it said PASS after the compare - instead I believe no output at all means pass

[8:52] 
I went through this identical drill with @jgfouca a couple of weeks ago

[8:52] 
(wanted to confirm all other tests really did pass)

Jon Wolfe [8:53 AM] 
I agree, it would feel better if it actually said PASS. And It's uncomfortable to make assumptions like this, but I'll deal...

### PR DESCRIPTION
**Pull request by jgfouca**
There were two issues. First, when a diff occurred, it generated a
monstrous amount of output in TestStatus.log. A more reasonable approach
is to handle it the same as a build or run failure: note the fail and point
the user to the relevant log file.

To make up for the absence of DIFF information in TestStatus.log, we make sure to upload
cprnc.log to cdash if needed.

The other issue is users being unclear if a compare passed or failed. The pass
or fail is now explicitly printed to the log.

Test suite: by-hand, code-checker
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes #1510 
Fixes #566 

User interface changes?: Contents of TestStatus.log

Code review: @jedwards4b

### CODE REVIEW

**Comment by billsacks** [comment]
Thanks a lot for doing this. This is going to make it a lot easier to skim through TestStatus.log files.

This also addresses #566 - specifically, see https://github.com/ESMCI/cime/issues/566#issuecomment-248459632

Personally, I'm okay with no RMS errors appearing in TestStatus.log. I think that feature was put in place (in cime4 or earlier, where **just** the RMS lines were put in TestStatus.log) in order to facilitate things like `grep RMS */TestStatus.log`. While that's a nice ability, I often use `tools/cprnc/summarize_cprnc_diffs` for this purpose. However, I wonder if others (maybe @fischer-ncar @ekluzek @mvertens or others) have come to rely on these RMS lines appearing in TestStatus.log?

**Comment by fischer-ncar** [comment]
I have come to depend on the RMS lines appearing in TestStatus.log.  It allows me to figure out it a test failure is a minor or major problem.

**Comment by ekluzek** [comment]
I do constantly use "grep RMS TestStatus.log" to see what's going on. So removing those will affect my workflow. I don't need the rest of the cprnc output, but I do look at the RMS lines.

**Comment by billsacks** [comment]
What about this solution: If there are baseline failures, then copy the relevant cprnc.out file(s) to the case directory. Then you make it easy to skim through TestStatus.log, and if you want to quickly see all RMS errors, you can do `grep RMS */*.cprnc.out` rather than `grep RMS TestStatus.log`?

**Comment by fischer-ncar** [comment]
I'm fine with Bill's solution.  I actually prefer it over RMS lines being in TestStatus.log.

**Comment by ekluzek** [comment]
I agree as well. That would be better than jamming all of cprnc output in the TestStatus.log. If the cprnc output was easy to find and check that would help.

**Comment by jgfouca** [comment]
OK, I will implement Bill's solution.

**Comment by jgfouca** [comment]
@billsacks OK, I implemented your solution.

**Comment by billsacks** [comment]
@jgfouca - fantastic, thanks a lot! I think this PR will really help with the efficiency of parsing test failures.

**Pull request merged**
