### PR TITLE
add flux convergence criteria

### PR DESCRIPTION
**Pull request by jedwards4b**
Use a flux criteria for iterative calculation of atmocn flux.   This is introduced in a backward compatible way.   Clean up some unused variables and unnecessary if blocks.

Test suite:  ERS_Ld7.f19_g17.B1850.hobart_pgi.allactive-defaultio 
Test baseline: 
Test namelist changes: 
Test status: roundoff

Fixes [CIME Github issue #]

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by jedwards4b** [comment]
Not ready to merge yet - still need to test on cheyenne.

**Comment by jedwards4b** [comment]
I have done the following additional testing.
Generated a baseline from master using SMS.f09_g17.B1850.cheyenne_intel.allactive-defaultio
Compared to this branch with changes in user_nl_cpl to reproduce original results:
flux_convergence = 0.0
flux_max_iteration = 2
This test was bfb, I then did the same test again but in both the master and branch added
flux_diurnal = .true.
this was also bfb.   @mvertens I think this is ready to merge.

**Comment by mvertens** [comment]
@jedwards4b - Thanks for doing this. Can you please run an addition debug
test and restart test:
   ERS.SMS.f09_g17.B1850.cheyenne_intel.allactive-defaultio
   SMS_D.SMS.f09_g17.B1850.cheyenne_intel.allactive-defaultio
This would give me more confidence that this change is working for restarts
and for debug mode.

**Comment by jedwards4b** [comment]
@mvertens Additional tests completed successfully.

**Comment by rljacob** [comment]
I'd like some more background on this.  What is this for?

**Comment by jedwards4b** [comment]
@rljacob - This is an iterative solver for surfaces winds used in flux computations.   In the original code the loop limit was hard coded at 2 (in fact it wasn't even a loop, the code was cut and pasted)
In experiments with cesm fully coupled cases we found that in some regions the equation wasn't sufficiently converging in two iterations.   So we have introduced a convergence criteria and maximum iteration count for the loop.   For acme we have set flux_convergence=0.0 and flux_max_iteration=2 so that the code is bfb with the original.   For cesm we plan to use flux_convergence=0.01 and flux_max_iteration=5.

**Pull request merged**
