### PR TITLE
Fix format descriptor in mem-logging for IBM compiler

### PR DESCRIPTION
**Pull request by amametjanov**
Replace indefinite repeat (star) with large numeric value.
Checked changes with several compilers:
* xl/16.1.1-7
* intel/19.1.0.166
* gcc/9.3.0 and gcc/8.1.1
* pgi/19.9
* cce/10.0.3

Test suite: SMS.f19_g16.X
Test baseline: n/a
Test namelist changes: none
Test status: bit for bit

Fixes E3SM-Project/E3SM#4138

User interface changes?: none

Update gh-pages html (Y/N)?: N

Code review: @dqwu

### CODE REVIEW

**Review by dqwu — APPROVED** [review]
Tested with XL, GNU and PGI compilers on Summit, no build errors.

**Comment by rljacob** [comment]
@amametjanov please check on the build fails from the CI above.

**Comment by jedwards4b** [comment]
I think that it may just be a matter of merging master into this PR since I recently fixed the github action.

**Comment by amametjanov** [comment]
I'm not sure how to read the 1800-line log. Which machine is CI running on and how to access build logs?

I had tested with several compilers on OLCF Summit and ALCF Theta. Is it possibly an issue within CI setup?

From https://github.com/ESMCI/cime/runs/2082716835?check_suite_focus=true: e.g.
```
======================================================================
ERROR: test_case_submit_interface (__main__.K_TestCimeCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts_regression_tests.py", line 1205, in tearDown
    kill_subprocesses()
  File "./scripts_regression_tests.py", line 228, in kill_subprocesses
    proc_ids = CIME.utils.find_proc_id(proc_name=name, children_only=True)
  File "/home/runner/work/cime/cime/scripts/tests/../lib/CIME/utils.py", line 973, in find_proc_id
    expect(stat in [0, 1], "pgrep failed with error: '{}'".format(errput))
  File "/home/runner/work/cime/cime/scripts/tests/../lib/CIME/utils.py", line 137, in expect
    raise exc_type(msg)
CIME.utils.CIMEError: ERROR: pgrep failed with error: 'pgrep: cannot allocate 4611686018427387903 bytes'
...
======================================================================
ERROR: test_b_full (__main__.O_TestTestScheduler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts_regression_tests.py", line 1395, in test_b_full
    ct.run_tests()
  File "/home/runner/work/cime/cime/scripts/tests/../lib/CIME/test_scheduler.py", line 1056, in run_tests
    expect(threading.active_count() == 1, "Leftover threads?")
  File "/home/runner/work/cime/cime/scripts/tests/../lib/CIME/utils.py", line 137, in expect
    raise exc_type(msg)
CIME.utils.CIMEError: ERROR: Leftover threads?
...
======================================================================
FAIL: test_clean_rebuild (__main__.G_TestBuildSystem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts_regression_tests.py", line 2566, in test_clean_rebuild
    casedir = self._create_test(["--no-run", "SMS.f19_g16_rx1.A"], test_id=self._baseline_name)
  File "./scripts_regression_tests.py", line 1269, in _create_test
    output = run_cmd_assert_result(self, "{} {}/create_test {}".format(env_changes, SCRIPT_DIR, " ".join(extra_args)),
  File "./scripts_regression_tests.py", line 72, in run_cmd_assert_result
    test_obj.assertEqual(stat, expected_stat, msg=msg)
AssertionError: 100 != 0 : 
COMMAND:  /home/runner/work/cime/cime/scripts/create_test --no-run SMS.f19_g16_rx1.A -t fake_testing_only_20210311_022210 --baseline-root /home/runner/cesm/scratch/scripts_regression_test.20210311_021801/baselines --compiler=gnu --mpilib=openmpi --test-root=/home/runner/cesm/scratch/scripts_regression_test.20210311_021801 --output-root=/home/runner/cesm/scratch/scripts_regression_test.20210311_021801
FROM_DIR: /home/runner/work/cime/cime/scripts/tests
SHOULD HAVE WORKED, INSTEAD GOT STAT 100
OUTPUT: Testnames: ['SMS.f19_g16_rx1.A.ubuntu-latest_gnu']
...
        File not found: rof2ocn_ice_rmapname = "cpl/gridmaps/rx1/map_rx1_to_gx1v6_nnsm_e1000r300_170503.nc", will attempt to download in check_input_data phase
           NOTE: ignoring setting of rof2ocn_fmapname=idmap in seq_maps.rc
        ERROR: /home/runner/work/cime/cime/src/build_scripts/buildlib.cprnc FAILED, cat /home/runner/cesm/scratch/scripts_regression_test.20210311_021801/SMS.f19_g16_rx1.A.ubuntu-latest_gnu.fake_testing_only_20210311_022210/bld/cprnc.bldlog.210311-022212

```

**Comment by jedwards4b** [comment]
@amametjanov with your permission I can push a fix to your branch

**Comment by amametjanov** [comment]
Yes, please go ahead. I can rebase onto latest master and force-push, if that'll help. E3SM discourages merging master into branches.

**Comment by jedwards4b** [comment]
All I was going to do was merge master into your branch, but I don't want to defy e3sm policy.  Basically you just need the latest .github/workflow/srt.yml from master.

**Comment by amametjanov** [comment]
Okay, updated that file in this branch and pushed. This page now shows that the two build checks passed.

**Review by jedwards4b — APPROVED** [review]

**Pull request merged**
