### PR TITLE
Python2 Strings to Python3 Strings

### LINKED ISSUE #1492: Change Python2 Strings to Python3 Strings
For future compatibility we should switch strings from python2, e.g. `'%s' % var`, to python3 strings, e.g. `'{}'.format(var)`. The strength of this approach becomes obvious when we look at something like the following:
```
"%s 1 OR %s 2 OR %s 3" % ((var, ) * 3)
```
vs
```
{0} 1 or {0} 2 or {0} 3".format(var)
```

### PR DESCRIPTION
**Pull request by erichlf**
This PR changes all python2 style strings to python3 style strings. It does not change the scripts_regression_tests.py script nor the code_checker script.

Test suite: code_checker and scripts_regression_tests.py
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes #1492 

User interface changes?: 

Code review: @jgfouca @jedwards4b

### CODE REVIEW

**Comment by jedwards4b** [comment]
I have rebased to master to resolve conflicts and ran scripts_regression_tests.py on cheyenne.

**Comment by erichlf** [comment]
@jedwards4b hmmm, so did I and it looks like it took your changes instead of mine. There was a place in wait_for_tests.py which had a repeated format, so I changed it in favor of using the indexed format. I wonder what happened to my push?

**Comment by erichlf** [comment]
Yep, now I can't pull.

**Comment by jedwards4b** [comment]
After a rebase you need to reset your local to the remote
git reset --hard 
please correct my wait_for_tests.py merge if I did it wrong...

**Comment by erichlf** [comment]
Okay, hurry things are not conflicting. lol

**Pull request merged**
