### PR TITLE
Adding support for anvil - maint/cime5.1

### PR DESCRIPTION
**Pull request by jayeshkrishna**
This commit adds support for anvil (the new cluster at ANL)

Test suite:
Test baseline:
Test namelist changes:
Test status: 

User interface changes?: None

Code review: @rljacob

Adding support for the new acme cluster, anvil. This
machine uses the same login node as blues and jobs are
submitted to the "acme" queue.

To use the anvil cluster, create your case on the
blues login node by specifying the "-mach" explicitly
as "anvil"

### CODE REVIEW

**Comment by rljacob** [comment]
Lets also update the MAX_TASKS_PER_NODE to 36 on this too?

**Comment by jayeshkrishna** [comment]
I will update the branch. How do we update master (re-merge the branch with a new PR?)?

**Comment by rljacob** [comment]
I think make a new branch just for that addition to master.

**Comment by jayeshkrishna** [comment]
ok, I will create a new branch off latest master (that updates MAX_TASKS_PER_NODE) to update master and update this branch to include the changes to maint/cime5.1

**Pull request merged**
