### PR TITLE
Fix missing baseline comment

### LINKED ISSUE #599: Bug in hist_utils.py causes tests to fail when just the baselines are missing
TestStatus is reporting that the RUN phase is failing when it's just the baselines missing.
Looks like I made a typo in hist_utils.py when I added BFAIL to the comment when baselines are missing. @jedwards4b

### PR DESCRIPTION
**Pull request by fischer-ncar**
Fix bug in hist_utils.py that was causing complete test failure when baselines were missing.

Test suite: scripts_regression_tests
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes #599 

User interface changes?: 

Code review:

### CODE REVIEW

**Comment by jgfouca** [comment]
I would have expected pylint to catch stuff like this

**Comment by fischer-ncar** [comment]
@jgfouca pylint missed it.  This is what pylint reported.

C:294, 0: Line too long (108/100) (line-too-long)

C:294, 0: Exactly one space required after comma          
return False, "ERROR %s baseline directory '%s' does not exist" % TEST_NO_BASELINES_COMMENT,bdir
 ..........................................................^ (bad-whitespace)

**Comment by jgfouca** [comment]
@fischer-ncar yes, i know pylint missed it because our code_checker test has been passing. Sorry for the ambiguous comment; i wasn't accusing you of not running pylint, i was just expressing disappointment that pylint missed such an obvious error

**Comment by fischer-ncar** [comment]
@jgfouca, I just wanted to show you what pylint did and didn't report.  I'm disappointed that it missed the error too.

**Pull request merged**
