### PR TITLE
Add support for MPASO_USE_PETSC

### PR DESCRIPTION
**Pull request by jgfouca**
Test suite:
Test baseline:
Test namelist changes:
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?:

Update gh-pages html (Y/N)?:

### CODE REVIEW

**Review by jasonb5 — APPROVED** [review]
LGTM

**Comment by rljacob** [comment]
@bishtgautam I notice ELM uses  "USE_PETSC_LIB" as a cpp in its code.  How is that set?

**Comment by bishtgautam** [comment]
@rljacob Currently, the code to add `-DUSE_PETSC_LIB` is broken in E3SM for a long time.

**Comment by rljacob** [comment]
Ok.  The logic we are going for is to allow a user to specify which components need PETSc.  Any combination of on/off should be allowed.  If any of them do, add the PETSc library to the linker.

**Pull request merged**
