### PR TITLE
Add timestamp to rpointers

### PR DESCRIPTION
**Pull request by jedwards4b**
Modifies tests to allow for timestamps on rpointer files.  Fully backward compatible to non-timestamped rpointers. 

Test suite: cesm prealpha and prebeta tests
Test baseline:
Test namelist changes:
Test status: bit for bit
Fixes 
User interface changes?:

Update gh-pages html (Y/N)?:

### CODE REVIEW

**Review by fischer-ncar — APPROVED** [review]

**Review by jasonb5 — APPROVED** [review]
LGTM

**Comment by rljacob** [comment]
Are all these commits related to adding timestamps to rpointers?   Doesn't look like it.

**Comment by rljacob** [comment]
@jedwards4b it might be the merge of master in to this branch.  You may want to rebase it instead.  That gives a cleaner commit history.

**Comment by jedwards4b** [comment]
I've backed up and rebased - how does it look now?

**Comment by jedwards4b** [comment]
It seems that the website https://web.lcrc.anl.gov/public/e3sm/inputdata/ is down.

**Comment by rljacob** [comment]
website is fixed.

**Comment by rljacob** [comment]
Curious how this feature is being used.

**Comment by jedwards4b** [comment]
By adding the timestamp to rpointer files it is much easier to restart from intermediate restart files.   Currently in order to do this the rpointer files must be constructed by hand, an error prone and tedious step.

**Pull request merged**
