### PR TITLE
Jgfouca/branch for acme split 2019 07 22

### PR DESCRIPTION
**Pull request by jgfouca**
Bug fixes:
* ROOTPE needs to be explicitly set to zero for all component models for PTS_MODE (single column model mode)
* Need to check for BUILD_COMPLETE after checking locked files
* Make create_dirs more robust when multiple threads are running

Features:
* Infrastructure upgrade to support finite volume physics grid

Test suite: scripts_regression_tests
Test baseline: 
Test namelist changes: 
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review: @jedwards4b

### CODE REVIEW

**Comment by jgfouca** [comment]
Tests ongoing.

**Comment by billsacks** [comment]
@jgfouca thanks, as always, for your summary bullet points.

Does this

> Infrastructure upgrade to support finite volume physics grid

affect anything outside of e3sm-specific config stuff? If so, we might want to request a review from someone in CESM who is working on a similar feature, to make sure the two play nicely together.

**Comment by jgfouca** [comment]
@billsacks , the only change to a non-E3SM file for that PR was: cime/src/drivers/mct/main/seq_domain_mct.F90

**Comment by billsacks** [comment]
> @billsacks , the only change to a non-E3SM file for that PR was: cime/src/drivers/mct/main/seq_domain_mct.F90

Okay thanks - and that change looks reasonable to me.

**Pull request merged**
