### PR TITLE
Seq io fix pio2

### LINKED ISSUE #3810: test IRT_N2_Ln9.f19_g16_rx1.A failing
With pio2 the mask is read incorrectly from the ice stream data file.
This causes the test to fail since #3800

### PR DESCRIPTION
**Pull request by jedwards4b**
Don't rely on pio to do data conversions.  Note that I used both pio2 and pio1 for these tests. 

Test suite: scripts_regression_tests.py, IRT_N2_Ln9.f19_g16_rx1.A.cheyenne_gnu, PET.T62_g16.G.cheyenne_pgi.pop-cice
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes #3810 

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by jedwards4b** [comment]
I've converted this to draft because the test PET.T62_g16.G.cheyenne_pgi.pop-cice is giving mixed results
in the COMPARE_base_single_thread.  Sometimes it passes, other times it fails and the fails seem to vary in 
exact content.

**Review by jgfouca — APPROVED** [review]

**Review by fischer-ncar — APPROVED** [review]

**Comment by jedwards4b** [comment]
Fixed and ready.

**Comment by rljacob** [comment]
What are the changes to streams for?

**Comment by jedwards4b** [comment]
There was an implicit change of data type when reading the stream - this is not supported in pio2 the data type is read in the type on file and converted explicitly.

**Pull request merged**
