### PR TITLE
PFS tests should always save timing

### PR DESCRIPTION
**Pull request by jgfouca**
Test suite: pre-commit
Test baseline:
Test namelist changes:
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?:

Update gh-pages html (Y/N)?:

### CODE REVIEW

**Review by jedwards4b — APPROVED** [review]

**Comment by jgfouca** [comment]
I could think of any reason why you'd ever want to run a PFS test and not save the timings.

**Comment by jedwards4b** [comment]
I can actually - I frequently use the PFS test for load balancing and don't want to save or compare to a baseline.

**Comment by jgfouca** [comment]
@jedwards4b , ah ok. Should I abort this PR?

**Comment by jedwards4b** [comment]
I'm not sure - if I create a PFS test and don't specify a baseline directory with --generate what happens?

**Comment by rljacob** [comment]
I'm looking at pfs.py and can't tell what its doing.  Is that actual test mechanics somewhere else in CIME?

**Comment by jedwards4b** [comment]
That's the place to look - all it does is run a case for 20 days.  It saves the timing files and software_environment.txt file for each run.  It can save them to a baseline directory but most often I use it as a standalone tool to load balance configurations.

**Comment by jedwards4b** [comment]
I should add that it turns off history and restart to minimize IO for the run.

**Comment by jgfouca** [comment]
I think SAVE_TIMING should work fine with or without baselines. @rljacob , the mechanics of the test are very simple, basically the same as SMS, so the only interesting stuff is in `CIME/data/config/config_tests.xml`

**Comment by rljacob** [comment]
Yes SAVE_TIMING just saves the timing info to another directory.  It doesn't reference any other runs.

**Comment by rljacob** [comment]
This is off topic but it seems like turning off history and setting the run length to 20 days should be **in** pfs.py.  Same for other tests.  Why even have CIME/data/config/config_tests.xml ?

**Comment by jgfouca** [comment]
@rljacob , test parameters are kept separate from test python mechanics. I think this approach makes sense since create_test parses the test options and handles the XML creation before the test-specific python code is run.

**Comment by billsacks** [comment]
Does this address #2918 or is this somewhat separate from what I was asking there?

Regarding the tangential discussion of config_tests.xml: I have to say that I agree with @rljacob here: I have always found it confusing that I need to look in two places to see the full picture of how a test is defined. Maybe there are a handful of things that truly can't be handled in the python, but it seems like most of what we do in config_tests.xml could be done with a case.set_value early in the test, and then we could have everything in one place.

**Comment by rljacob** [comment]
I happened to be looking at ert.py which DOES use case.set_value and thought it was easy to follow.  Then I went to pfs.py and wondered how it was set to do 20 days.

**Comment by rljacob** [comment]
How does the PFS test determine pass/fail without a baseline?

**Comment by jedwards4b** [comment]
It does not - you need a baseline.
I use PFS mostly for loadbalancing fully coupled configurations.

**Comment by rljacob** [comment]
What does your workflow look like when you're loadbalancing?  I would build PFS once and then go to the test casedir and do cycles of edit pelayout-submit-look at timings.

**Comment by jedwards4b** [comment]
Yes, that's exactly it and the env_mach_pes.xml and software_environment.txt are saved for each run.

**Pull request merged**
