### PR TITLE
cori_port for cime5.1

### PR DESCRIPTION
**Pull request by jedwards4b**
initial port to cori-haswelll and cori-knl for acme 

Test suite: unable to run as acme, i need the reviewer to do this.   
Test baseline: 
Test namelist changes: 
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?: 

Code review:

### CODE REVIEW

**Comment by rljacob** [comment]
@ndkeen can you run scripts_regresions_tests on any platform?   We need to verify the changes to the python scripts didn't break anything.

**Comment by ndkeen** [comment]
Unless I'm doing something wrong, this is the branch that I was discussing with jedwards and yourself on slack.  The runs fail as something is not right with the -c flag setting.  I have been asking for guidance on how to move forward

**Comment by jgfouca** [comment]
@ndkeen if you're having trouble running scripts_regression_tests, let me know. Machine name and a paste of the error should be enough for me to figure it out.

**Comment by ndkeen** [comment]
the issue is that some of the changes made when I originally tested are not there anymore.  should i try to redo them?  or figure out what happened?

**Comment by jgfouca** [comment]
You lost your work? Did you have some kind of snafu with git?

**Comment by ndkeen** [comment]
This was work Jim had done.  Added a function and the ability to compute a value I needed for the srun command.  It's not working as it did before on a branch I had been using from a different repo.  I think he would have to be the one to fix it, or at east tell me what needs to be done.

**Comment by jedwards4b** [comment]
@ndkeen What is the status of this?   As far as I can tell there is nothing wrong with the PR but only with your merge procedure.

**Comment by ndkeen** [comment]
OK, as far as I know, I already merged (hit the green button) a _different_ PR that does this work, so we should be ale to close this one.

https://github.com/ESMCI/cime/pull/809/commits/2245f676af23bf0dae9730e27b051559ad569ee8

**Comment by jedwards4b** [comment]
that was a commit to master, this one is for the cime5.1 branch that acme is using.

**Comment by ndkeen** [comment]
OK, I was doing what I thought I was advised to do.  Of course, I need these changes on acme side.

**Pull request closed without merging**
