### PR TITLE
add travis_ci testing

### PR DESCRIPTION
**Pull request by jedwards4b**
Adding travis_ci to run scripts_regression_tests.py A_RunUnitTests B_CheckCode
on each PR using both python 2.7 and 3.6

Test suite: by hand
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes 

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review: @jgfouca

### CODE REVIEW

**Comment by billsacks** [comment]
Awesome - thanks a lot for doing this @jedwards4b !

**Comment by rljacob** [comment]
Can you say more about what this does?   Travis-ci runs it where?

**Comment by jedwards4b** [comment]
https://travis-ci.org/
It runs on an Ubuntu linux system using both python 2.7 and 3.6

**Comment by rljacob** [comment]
Who provides the hardware to run the tests?

**Comment by jedwards4b** [comment]
They do - information available in the link.

**Pull request merged**
