### PR TITLE
deal with issues of downloading checksum file

### LINKED ISSUE #3033: cime_developer tests failed on anlworkstation
The errors can be reproduced on anlworkstation by running a single cime_developer test:
`./create_test DAE.ww3a.ADWAV --machine=anlworkstation --test-root=****`

Errors were:
```
        Traceback (most recent call last):
          File "./case.submit", line 108, in <module>
            _main_func(__doc__)
          File "./case.submit", line 105, in _main_func
            mail_user=mail_user, mail_type=mail_type, batch_args=batch_args)
          File "scripts/lib/CIME/case/case_submit.py", line 191, in submit
            custom_success_msg_functor=verbatim_success_msg)
          File "scripts/lib/CIME/utils.py", line 1702, in run_and_log_case_status
            rv = func()
          File "scripts/lib/CIME/case/case_submit.py", line 189, in <lambda>
            batch_args=batch_args)
          File "scripts/lib/CIME/case/case_submit.py", line 120, in _submit
            case.check_case()
          File "scripts/lib/CIME/case/case_submit.py", line 205, in check_case
            self.check_all_input_data()
          File "scripts/lib/CIME/case/check_input_data.py", line 159, in check_all_input_data
            chksum_file)
          File "scripts/lib/CIME/case/check_input_data.py", line 37, in _download_checksum_file
            success = server.getfile(rel_path, new_file)
          File "scripts/lib/CIME/Servers/wget.py", line 31, in getfile
            full_url = os.path.join(self._server_loc, rel_path)
          File "/usr/lib/python2.7/posixpath.py", line 75, in join
            if b.startswith('/'):
        AttributeError: 'NoneType' object has no attribute 'startswith'
```
This test passed before. Is this caused by missing input files requierd by latest CIME?
Looks like CIME is not handling the case where there is no file to download (None)?

### LINKED ISSUE #3034: Possible issues with inputdata checksum downloads
I have noticed two possible issues with the inputdata checksum implementation. I'm not sure if these are actually issues, but wanted to get @jedwards4b 's thoughts on these:

(1) I noticed that my tests were downloading the `inputdata_checksum.dat` file every time I ran `./case.submit`. I would have thought this download from the inputdata server would only happen if (a) you are actually downloading any files (e.g., the first time it goes to download a file, it downloads the checksum file from that server, too), or (b) you run `check_input_data` with the `--chksum` argument.

(2) In this loop:

https://github.com/ESMCI/cime/blob/e1779e35e9d62f2d1a4f66b13aa8a71d6e37cb45/scripts/lib/CIME/case/check_input_data.py#L140-L159

If I'm understanding the logic correctly, the loop will exit as soon as it downloads the first checksum file successfully - rather than, say, downloading the checksum file from each server. Is that actually what's intended here? (Or am I misunderstanding the logic?)

### LINKED ISSUE #3036: Having long wait time on case.submit
This is with cime5.6.12

I'm having long wait times on running case.submit on cheyenne today, with it eventually failing as we see below. It seems to be because of some type of network issue getting to svn inputdata from cheyenne. I'm wondering if we need another --skip option to skip checking the connection to inputdata?

```
   Calling /gpfs/fs1/scratch/erik/release-clm5.0.19/cime/src/components/stub_comps/swav/cime_config/buildnml
   Calling /gpfs/fs1/scratch/erik/release-clm5.0.19/cime/src/components/stub_comps/sesp/cime_config/buildnml
   Calling /gpfs/fs1/scratch/erik/release-clm5.0.19/cime/src/drivers/mct/cime_config/buildnml
Finished creating component namelists
Checking that inputdata is available as part of case submission
Client protocol gftp not enabled
Using protocol wget with user anonymous and passwd user@example.edu
ERROR: Could not connect to repo '{0}'
This is most likely either a proxy, or network issue .
```

### PR DESCRIPTION
**Pull request by jedwards4b**
Should only download chksum file if chksum option is specified or download is specified.
Fix error when trying to download existent checksum file.

Test suite: scripts_regression_tests.py
Test baseline: 
Test namelist changes: 
Test status: bit for bit,
Fixes #3033 
Fixes #3034 
Fixes #3036

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by billsacks** [comment]
@jedwards4b I haven't looked at the changes yet, but: should this go into maint-5.6 rather than master? (Isn't this checksum stuff on the maint-5.6 branch?)

**Comment by billsacks** [comment]
(Or, I should say: both maint-5.6 and master... but first to maint-5.6?)

**Comment by jedwards4b** [comment]
Yes you are correct - I will close this and open one to maint-5.6

**Comment by jedwards4b** [comment]
Superceeded by #3038

**Pull request closed without merging**
