### PR TITLE
Greenplanet support

### PR DESCRIPTION
**Pull request by mnlevy1981**
Adding two new machines to support UCI's [GreenPlanet](https://ps.uci.edu/greenplanet) cluster.
Currently supporting two [SLURM partitions](https://ps.uci.edu/greenplanet/slurm_partitions) (`sky2.4` and `sib2.9`).

Test suite: None; I've built a handful of compsets on the machine but haven't done any tests on cheyenne
Test baseline: N/A
Test namelist changes: N/A
Test status: N/A

Fixes [CIME Github issue #] N/A

User interface changes?: none

Update gh-pages html (Y/N)?: N

Code review: not yet

Note that this PR requires https://github.com/ESCOMP/POP2-CESM/pull/45 before CESM will run on the new machine. Opening as a draft PR until I get more feedback from UCI team, but I think this is all that's needed for now.

### CODE REVIEW

**Comment by jedwards4b** [comment]
@mnlevy1981  you should run scripts_regression_tests.py on the platform, you should also consider running the ECT.

**Comment by mnlevy1981** [comment]
`scripts_regression_tests.py` highlighted the fact that I hadn't built `cprnc` yet (and was using the `cheyenne` defaults for it and the baselines directory), so those are fixed in bf190b6 and it looks like the tests run fine now. Looking into ECT

**Comment by mnlevy1981** [comment]
Test results aren't stellar...

Most of scripts regression passed, but there were a few failures:

```
...
test_cime_case_test_custom_project (__main__.K_TestCimeCase) ... FAIL
test_save_timings_manual (__main__.L_TestSaveTimings) ... FAIL
...
FAIL: test_cime_case_test_custom_project (__main__.K_TestCimeCase)
FAIL: test_self_build_cprnc (__main__.K_TestCimeCase)
FAIL: test_save_timings_manual (__main__.L_TestSaveTimings)
...
----------------------------------------------------------------------
Ran 158 tests in 4011.901s

FAILED (failures=3, skipped=16)
```

I'm not worried about `test_custom_project` as this machine doesn't use project / account keys, and I'm not worried about `build_cprnc` because I built `cprnc` on this machine. I don't know what to make of the `TestSaveTimings`, but the full error makes it seem like maybe a system glitch prevented PIO from building?

```
FAIL: test_save_timings_manual (__main__.L_TestSaveTimings)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts_regression_tests.py", line 2590, in test_save_timings_manual
    self.simple_test(manual_timing=True)
  File "./scripts_regression_tests.py", line 2561, in simple_test
    self._create_test(["SMS_Ln9_P1.f19_g16_rx1.A", timing_flag, "--walltime="+walltime], test_id=self._baseline_name)
  File "./scripts_regression_tests.py", line 1264, in _create_test
    output = run_cmd_assert_result(self, "{} {}/create_test {}".format(env_changes, SCRIPT_DIR, " ".join(extra_args)),
  File "./scripts_regression_tests.py", line 70, in run_cmd_assert_result
    test_obj.assertEqual(stat, expected_stat, msg=msg)
AssertionError: 100 != 0 :
COMMAND:  /nfspool-0/home/mnlevy/codes/CESM/cesm2.2.0/cime/scripts/create_test SMS_Ln9_P1.f19_g16_rx1.A  --walltime=00:15:00 -t fake_testing_only_20201209_113247 --baseline-root /DFS-L/SCRATCH/moore/mnlevy/cesm_runs/scripts_regression_test.20201209_111628/baselines --test-root=/DFS-L/SCRATCH/moore/mnlevy/cesm_runs/scripts_regression_test.20201209_111628 --output-root=/DFS-L/SCRATCH/moore/mnlevy/cesm_runs/scripts_regression_test.20201209_111628
FROM_DIR: /nfspool-0/home/mnlevy/codes/CESM/cesm2.2.0/cime/scripts/tests
SHOULD HAVE WORKED, INSTEAD GOT STAT 100
OUTPUT: Testnames: ['SMS_Ln9_P1.f19_g16_rx1.A.greenplanet-sky24_intel']
No project info available
create_test will do up to 1 tasks simultaneously
create_test will use up to 50 cores simultaneously
Creating test directory /DFS-L/SCRATCH/moore/mnlevy/cesm_runs/scripts_regression_test.20201209_111628/SMS_Ln9_P1.f19_g16_rx1.A.greenplanet-sky24_intel.fake_testing_only_20201209_113247
RUNNING TESTS:
  SMS_Ln9_P1.f19_g16_rx1.A.greenplanet-sky24_intel
Starting CREATE_NEWCASE for test SMS_Ln9_P1.f19_g16_rx1.A.greenplanet-sky24_intel with 1 procs
Finished CREATE_NEWCASE for test SMS_Ln9_P1.f19_g16_rx1.A.greenplanet-sky24_intel in 1.520060 seconds (PASS)
Starting XML for test SMS_Ln9_P1.f19_g16_rx1.A.greenplanet-sky24_intel with 1 procs
Finished XML for test SMS_Ln9_P1.f19_g16_rx1.A.greenplanet-sky24_intel in 0.467151 seconds (PASS)
Starting SETUP for test SMS_Ln9_P1.f19_g16_rx1.A.greenplanet-sky24_intel with 1 procs
Finished SETUP for test SMS_Ln9_P1.f19_g16_rx1.A.greenplanet-sky24_intel in 1.651646 seconds (PASS)
Starting SHAREDLIB_BUILD for test SMS_Ln9_P1.f19_g16_rx1.A.greenplanet-sky24_intel with 1 procs
Finished SHAREDLIB_BUILD for test SMS_Ln9_P1.f19_g16_rx1.A.greenplanet-sky24_intel in 69.466942 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /DFS-L/SCRATCH/moore/mnlevy/cesm_runs/scripts_regression_test.20201209_111628/SMS_Ln9_P1.f19_g16_rx1.A.greenplanet-sky24_intel.fake_testing_only_20201209_113247
    Errors were:
        Building test for SMS in directory /DFS-L/SCRATCH/moore/mnlevy/cesm_runs/scripts_regression_test.20201209_111628/SMS_Ln9_P1.f19_g16_rx1.A.greenplanet-sky24_intel.fake_testing_only_20201209_113247
           NOTE: ignoring setting of rof2ocn_fmapname=idmap in seq_maps.rc
        ERROR: /nfspool-0/home/mnlevy/codes/CESM/cesm2.2.0/cime/src/build_scripts/buildlib.pio FAILED, cat /DFS-L/SCRATCH/moore/mnlevy/cesm_runs/scripts_regression_test.20201209_111628/SMS_Ln9_P1.f19_g16_rx1.A.greenplanet-sky24_intel.fake_testing_only_20201209_113247/bld/pio.bldlog.201209-113252
```

I think the python script might be a little over-zealous cleaning up after itself, because the `SMS_Ln9_P1.f19_g16_rx1.A.greenplanet-sky24_intel.fake_testing_only_20201209_113247` no longer exists and I actually can't find any of the tests that were run.

For the ensemble test, I stuck with the POP ECT and salinity seems to be an issue:

```
**********Run 1 (file=/glade/scratch/mlevy/popECT_gp/popcase.cesm2.2.0.000.pop.h.0001-12.nc):
                UVEL: 99.45%
                VVEL: 99.42%
                TEMP: 99.36%
                SALT: 0.30%
                 SSH: 99.65%
**********1 of 5 variables failed, resulting in an overall FAIL**********
```

I re-ran the test for each of the 12 months, but `SALT` was less than 2% for all of them (while the other four variables were >98%). I'm open to suggestions on how to either convince myself that the results are okay or what to change to try to get better results.

**Comment by mnlevy1981** [comment]
I ran the POP ECT on cheyenne and get the same type of failure:

```
**********Run 1 (file=/glade/scratch/mlevy/popcase_chey.cesm2.2.0.000/run/popcase_chey.cesm2.2.0.000.pop.h.0001-12.nc):
                UVEL: 99.83%
                VVEL: 99.86%
                TEMP: 99.82%
                SALT: 0.30%
                 SSH: 99.96%
**********1 of 5 variables failed, resulting in an overall FAIL**********
```

So maybe the `cesm2.2.0` ensemble is incorrect? I was planning on three cheyenne runs: starting with an out-of-the-box test, then changing `init_ts_perturb` to match the value that failed on GreenPlanet, and then also changing the PE-layout to match GreenPlanet... but this was the "out-of-the-box" cheyenne test.

**Comment by jedwards4b** [comment]
@fischer-ncar do you know what the issue is?

**Comment by fischer-ncar** [comment]
I was able to reproduce @mnlevy1981 ECT failure.  I was also able to reproduce the failure with one of the files used to generate the summary file.  So there is definitely something wrong with the summary file.

**Comment by fischer-ncar** [comment]
The ECT failure is a pyCECT backwards compatibility issue.  I was able to get Mike's file to pass with an older version of pyCECT.  @mnlevy1981, can you copy over your file from Greenplanet, then I can verify it for you by hand.

**Comment by mnlevy1981** [comment]
@fischer-ncar That's great! The files are in `/glade/scratch/mlevy/popECT_gp/`

**Comment by fischer-ncar** [comment]
It passes.

--------pyCECT--------
 
Thursday, 10. December 2020 05:24PM
 
Ensemble summary file = /glade/p/cesmdata/inputdata/validation/pop_ensembles/cesm2.2.0/pop_ens.T62_g17.G.cesm2.2.0.cheyenne_intel.summary_c200917.nc
 
Testcase file directory = /glade/scratch/mlevy/popECT_gp/
 
 
Found 1 matching files in specified --indir
 
Z-score tolerance = 3.00
ZPR = 90.00%
STATUS: Checkpoint month(s) =  [12]
 
**********Run 1 (file=/glade/scratch/mlevy/popECT_gp/popcase.cesm2.2.0.000.pop.h.0001-12.nc):
                UVEL: 99.45%
                VVEL: 99.42%
                TEMP: 99.36%
                SALT: 99.41%
                 SSH: 99.65%
**********0 of 5 variables failed, resulting in an overall PASS**********
 
Testing complete.

**Comment by mnlevy1981** [comment]
> It passes.

Woohoo! Thanks for tracking down a working copy of the test :)

**Comment by mnlevy1981** [comment]
Using `PyCECT` 3.2.0 I can verify that the greenplanet test passes:

```
**********Run 1 (file=/glade/scratch/mlevy/popECT_gp/popcase.cesm2.2.0.000.pop.h.0001-12.nc):
                UVEL: 99.45%
                VVEL: 99.42%
                TEMP: 99.36%
                SALT: 99.41%
                 SSH: 99.65%
**********0 of 5 variables failed, resulting in an overall PASS**********
```

**Comment by jedwards4b** [comment]
@fischer-ncar is this a new pysect bug?  If so can you open an issue?

**Comment by fischer-ncar** [comment]
@jedwards4b not really a pycect bug, more of a pycect forward compatibility issue for POP-ECT.  I'll open a cime issue to update the PyCECT version.  The validation website is using a newer version of PyCECT and doesn't have this issue.

**Comment by mnlevy1981** [comment]
@jedwards4b After @fischer-ncar pointed me to https://github.com/NCAR/PyCECT I played around with this test. CIME currently uses PyCECT 3.0.8 from back in Nov 2018; my run passes according to the next release (3.1.0) as well as every subsequent release (3.1.1, 3.2.0, and 3.2.1). It's not clear to me what changed between 3.0.8 and 3.1.0 but the problem has definitely already been addressed on the PyCECT side.

**Comment by jedwards4b** [comment]
Sounds good thanks.

**Review by jedwards4b — APPROVED** [review]

**Comment by mnlevy1981** [comment]
Unrelated to the PyCECT issue, it looks like I need the sysadmin on the machine to create a module for perl so I can update `config_machines.xml` (I had trouble with the system version of `xml::libxml` and another user ran into what looks like some other perl issue; the machine default is 5.16.3 from 2012 so I'm just hoping something more recent works out of the box). Once that's done I'll take this PR out of draft mode so it can be merged.

**Comment by jedwards4b** [comment]
@mnlevy1981 you can load xml::libxml as a user with the following commands:
curl -L http://cpanmin.us | perl - XML::LibXML
export PERL5LIB=$HOME/perl5/lib/perl5:$PERL5LIB    <--- bash/zsh
setenv PERL5LIB $HOME/perl5/lib/perl5                 <---- csh/tcsh

**Comment by jedwards4b** [comment]
@mnlevy1981 should this be merged or closed?

**Comment by mnlevy1981** [comment]
> @mnlevy1981 should this be merged or closed?

Let's merge it in - I haven't heard any complaints from the greenplanet users and they've been producing results so it must be working for them

**Pull request merged**
