### PR TITLE
Fix replay archive

### LINKED ISSUE #4049: replay.sh: Capture script in provenance.py for archiving (E3SM)
We need to archive replay.sh in performance archive so that it can be picked up by PACE for E3SM.
Logic needs to be added to https://github.com/ESMCI/cime/blob/master/scripts/lib/CIME/provenance.py#L400

cc @jasonb5 @rljacob

### PR DESCRIPTION
**Pull request by jasonb5**
- Fixes capturing `replay.sh` in performance archive.
- Fixes handling error when `replay.sh` is not writable.

Test suite: scripts_regression_tests.py
Test baseline: n/a
Test namelist changes: n/a 
Test status: bfb

Fixes #4049 #4050 

User interface changes?: n/a

Update gh-pages html (Y/N)?: n/a

### CODE REVIEW

**Comment by sarats** [comment]
On the E3SM side, we definitely want replay.sh to be created for every case. As this script would be written in a user's case directory, I'm not sure how they might run into permission issues. Perhaps I'm missing something here?

**Comment by jedwards4b** [comment]
@sarats often in the course of debugging issues for users I want to run a command in their case directory.  I attempted to run the pelayout script in a users case and got a permission error.

**Review by jedwards4b — APPROVED** [review]

**Comment by rljacob** [comment]
The commit message about a "capturing error" is confusing.  Provenance just wants to copy replay.sh to another directory so only needs read permission on the file.   But if it needs to be writeable for other people to run commands like "preview_run", that makes sense.

**Comment by jasonb5** [comment]
The "capturing error" should have been "handling error", this is a separate fix for #4050. My understanding was a user may want to execute a CIME command in another users directory where they do not have write permission.

The two fixes in this PR are loosely related by the "replay.sh" script.

**Comment by rljacob** [comment]
@jgfouca make sure this is also in your next CIME update to E3SM.

**Comment by jgfouca** [comment]
@rljacob I was thinking the same thing, I just pinged Jason to fix the conflict. I'm doing a CIME update the minute this gets merged.

**Comment by sarats** [comment]
It would be good to get the new Git files as well for provenance. We can try asking WC to update their v2 tag.

**Comment by jgfouca** [comment]
@sarats , what needs to happen to get those files? Do we have an issue or PR for that?

**Comment by rljacob** [comment]
PR #4055 did that.  Just need to get the newest CIME master in to E3SM and then have the WC team update their clone.  I don't think they'll need to rebuild their executable for everything to work.

**Comment by jasonb5** [comment]
@jgfouca This is ready to merge.

**Pull request merged**
