### PR TITLE
Jet/ebm liqice maps

### PR DESCRIPTION
**Pull request by jtruesdal**
Trying again to allow separate mapping files for ice and liquid runoff to ocean. The code is set up to be backward compatible and uses the same default mapping file for both the liquid and ice just as before. A different mapping file for liquid is used by the Estuary Box Model.

Test suite: pre_alpha
Test baseline: beta07
Test namelist changes: 
rof2ocn_rmapname and rof2ocn_rmaptype have been split into:

rof2ocn_ice_rmapname
rof2ocn_ice_rmaptype
rof2ocn_liq_rmapname
rof2ocn_liq_rmaptype

Test status: [bit for bit, roundoff, climate changing]  BFB. nlcomp fails.  This was expected.

Fixes [CIME Github issue #]

User interface changes?: 

Code review: Jim Edwards

### CODE REVIEW

**Comment by rljacob** [comment]
@jtruesdal did you run scripts_regression_tests.py on this branch?

**Comment by jedwards4b** [comment]
Rob,  I will do it - I have another one line change I want to make anyway - will put my change in the branch, test and merge- okay?

**Comment by rljacob** [comment]
Yes that's ok.

**Comment by jtruesdal** [comment]
Hi Rob.  I didn't run that script but will do so in the future.  I'm just learning the cime workflow and this was my first PR under ESMCI.  I didn't know ESMCI had a separate testing workflow and I was following the CESM/cime test strategy.

**Pull request merged**
