### PR TITLE
(WIP) work toward immediate resubmit

### PR DESCRIPTION
**Pull request by jedwards4b**
Submitted for discussion with @mfdeakin-sandia  this is untested code in which I've modified the loop in env_batch.py to do immediate resubmits.

Test suite: 
Test baseline: 
Test namelist changes: 
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by mfdeakin-sandia** [comment]
Sorry, I'll test this later, but I don't see how it solves the issue with `CONTINUE_RUN`? In this case, it doesn't look like it's set at all for runs after the first one.

**Comment by jedwards4b** [comment]
This code is incomplete, I'm just trying to illustrate the way I think the RESUBMIT loop should work.

**Comment by mfdeakin-sandia** [comment]
Alright, so if I pull this into the branch I have, would that be acceptable? Once I fix all the other issues, that is.
I was considering cleaning things up more, maybe sharing the code which sets `CONTINUE_RUN` with the resubmit version.

**Comment by jedwards4b** [comment]
Sure you can pull this into your branch and we'll look at what you have after you clean it up.  I think we'll need to iterate a few more times before we get to where we want to go.

**Comment by jedwards4b** [comment]
Incorporated in #2511

**Pull request closed without merging**
