### PR TITLE
Adding components

### PR DESCRIPTION
**Pull request by jedwards4b**
Start a section on adding new components to cime.   This still needs a lot of work.

Test suite:  None - documentation only
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes

User interface changes?: 

Update gh-pages html (Y/N)?: Y

Code review:

### CODE REVIEW

**Comment by billsacks** [comment]
@kauff - you may be interested in this and/or able to contribute, with your ISSM integration work.

**Comment by rljacob** [comment]
We definitely need this but I feel like its to much for Part II of the user's guide.   I see 3 classes of user:  The "pure" CIME user who only uses the scripts and xml files of a cime-driven model,  the coupled model developer that wants to  make their model part of a  "cime-driven" model and the cime developer who develops the core CIME python and Fortran services.

**Comment by bertinia** [comment]
I agree with Rob and will work on splitting the User's Guide into 3 sections as suggested. 
For now, I'm going to merge this PR and build the html in the gh-pages branch so that other documentation work can be continuously 
integrated into the master like the testing section that @fischer-ncar is working on and
the grids that @mnlevy1981 is working on.

**Comment by rljacob** [comment]
The current users's guide and its 2 parts is fine for the first class of user.   The separate "CIME programmers guide" is for the last class.   The middle one was a separate guide called "Buildling a Coupled Model with CIME"  and has a stub here:  http://esmci.github.io/cime/build_cpl/index.html

**Pull request merged**
