### PR TITLE
check_input_data: Expand SharedArea coverage to entire implementation

### PR DESCRIPTION
**Pull request by jgfouca**
Users are reporting directories in the input file area that have locked-down permissions. I did see several os.makedirs calls in check_input_data.py that fell outside SharedArea contexts. I think the easiest thing is to just do the entire implementation in a SharedArea.

Test suite: by-hand, pylint
Test baseline:
Test namelist changes:
Test status: bfb

Fixes [CIME Github issue #]

User interface changes?:

Update gh-pages html (Y/N)?:

### CODE REVIEW

**Comment by jgfouca** [comment]
@jonbob ^^^

**Review by jedwards4b — APPROVED** [review]
I don't have any problem with this change but I don't think that it will necessarily solve issues with permissions in inputdata.   For example on perlmutter group write permissions are set but many cesm and e3sm users are not in the group, and I don't think that we want everyone to have write permission to this directory tree.

**Comment by jgfouca** [comment]
@jedwards4b , yeah the root of the input dir will require the correct group ownership and chmod +s.

**Comment by jedwards4b** [comment]
I guess that what I'm saying is that I don't think that we can get to a place where any user can write to inputdata without intervention from someone with more privilege.   One way that we could workaround this is to create a temporary inputdata directory in the users space, linking files that are in the default inputdata location and downloading files which are not.   I was working on something like this in another context - on TACC systems access to the $WORK dir can be quite slow from compute nodes so I created a method to stage inputdata into the $SCRATCH dir prior to running.  We lost our TACC project though and I didn't bring this branch change into master - I think I can find it though if you are interested.

**Comment by jgfouca** [comment]
@jedwards4b , i think it may actually be this PR. I'm seeing similar failures when I run cime_tiny by hand that go away when I remove my changes.

**Comment by jgfouca** [comment]
@jedwards4b , I forgot to do the returns in the wrappers 😆

**Pull request merged**
