### PR TITLE
cdf64 only valid for serial netcdf, fix seq test

### LINKED ISSUE #1114: ERIO test gives false positive in PIO1
The netcdf4p and netcdf4c pio types silently fail to open that format and fail over to netcdf and
so this test falsely indicates those tests as passing.

### PR DESCRIPTION
**Pull request by jedwards4b**
The cdf64 parameter is only needed for serial netcdf io.  The seq test was not
implemented as intended, each component should be on it's own set of tasks.  

Test suite: scripts_regression_tests.py
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Partially Fixes #1114 

User interface changes?: 

Code review:

### CODE REVIEW

**Comment by jgfouca** [comment]
@jedwards4b looking at #1114 , does this PR make it so we'll detect silent fails?

**Comment by jedwards4b** [comment]
No, in order to do that we should add a format check to the ERIO test and check that the
file is written in the expected format.

**Comment by jgfouca** [comment]
@jedwards4b should that be in this PR or something else?

**Comment by jedwards4b** [comment]
It's something else I think,  I've updated the comment to say partially fixes and I'll make sure that the issue remains open.

**Comment by jgfouca** [comment]
thanks

**Pull request merged**
