### PR TITLE
Refactors how/when rebuilds are required

### PR DESCRIPTION
**Pull request by jasonb5**
- Refactors `check_lockedfiles`
- Updates `xmlchange` to use `check_lockedfiles`
- Adds ability for components to define when a rebuild is required
  - Define custom component triggers by adding `REBUILD_TRIGGER_{comp}` with comma separated list of variables to `config_component.xml`, e.g. `REBUILD_TRIGGER_CPL=NTASKS` would require a rebuild if `NTASKS` changes for the cpl component
- Removes warning/error when pelayout is changed
  - To add old behavior define `REBUILD_TRIGGER_CPL` with a value `NTASKS,NTHRDS,NINST` to couplers `config_component.xml`

Test suite: n/a
Test baseline: n/a
Test namelist changes: n/a
Test status: n/a

Fixes n/a
User interface changes? n/a
Update gh-pages html (Y/N)?:

### CODE REVIEW

**Comment by jasonb5** [comment]
TODO
- [ ] Finish adding tests

**Review by jgfouca — APPROVED** [review]
LGTM

**Comment by jgfouca** [comment]
@jedwards4b , you want to review or should I just merge?

**Comment by rljacob** [comment]
Does this mean I can: change NTASKS for a component that doesn't need a rebuild, run case.setup, immediately run case.submit without running case.build ?   Do I still have to run case.setup?

**Comment by jasonb5** [comment]
@rljacob Yes you would still have to run `./case.setup` to regenerate the batch script files, but `./case.build` can be skipped.
It's possible we could automatically run `./case.setup` after running `./xmlchange` on a variable or make it an option to do it with a single command e.g. `./xmlchange NTASKS=8 --reset` or something similar.

**Comment by jgfouca** [comment]
@jedwards4b , last chance to review before I merge.

**Comment by jasonb5** [comment]
@jgfouca What are your thoughts on adding a `--reset` argument to `./xmlchange` to skip the call to `./case.setup --reset`? I can address this in another PR if it's a worth while addition.

**Comment by jgfouca** [comment]
@jasonb5 , that sounds fine to me.

**Comment by jasonb5** [comment]
@jgfouca Sounds good, I'll make a separate PR for it.

**Comment by jedwards4b** [comment]
I was on vacation.  Sorry you couldn't find another cesm person to review, I'll bring that up in our team meeting tomorrow.

**Pull request merged**
