### PR TITLE
Implement walltime stash to support more-accurate walltimes

### PR DESCRIPTION
**Pull request by jgfouca**
This is for ACME only, but I'd still like feedback on the merits of the idea.

The idea is to make a "stash" of walltimes in the baseline area under a hardcoded baseline name "walltimes". Each time a test is run, store the time it took in a special file. This file will be used for more-accurate walltime requests on the batch system whenever the test is run again.

Test suite: scripts_regression_tests (anvil)
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes [CIME Github issue #]

User interface changes?: N

Update gh-pages html (Y/N)?: N

Code review: @jedwards4b

### CODE REVIEW

**Comment by jgfouca** [comment]
@jedwards4b , i'm thinking of adding some complexity to map the requested runtime to its wiggle-room multiplier. You're idea is pretty good too and simpler. It may result in timeouts for really big tests though.

**Comment by jgfouca** [comment]
OK, I'm pretty happy with this now.

**Comment by jgfouca** [comment]
@jedwards4b I almost forgot, I'm also worried about multi-submit jobs, especially in the case where the second job is much shorter than the first.

**Comment by jgfouca** [comment]
@jedwards4b , I believe this is ready to merge unless @rljacob or @mvertens want to chime in.

**Comment by rljacob** [comment]
I did have a question about where the "walltimes" file lives.  Is it directly under BASELINE_ROOT?

**Comment by jgfouca** [comment]
@rljacob , yes, it lives under $BASELINE_ROOT with a baseline name of "walltimes", so
$BASELINE_ROOT/walltimes/$CASE/walltimes

**Pull request merged**
