### PR TITLE
Remove manage externals

### PR DESCRIPTION
**Pull request by jedwards4b**
Removes the need for manage_externals from CESM.  We are still early in the discussion stage, so will set to draft. 

Test suite:
Test baseline:
Test namelist changes:
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?:

Update gh-pages html (Y/N)?:

### CODE REVIEW

**Comment by jedwards4b** [comment]
@jasonb5 I'm going to need your help again.  I need to update entrypoint.sh for the tests to run on this branch, I made the changes I think I need on the entrypoint.sh of this branch, but it doesn't use that one.

**Comment by jasonb5** [comment]
@jedwards4b I see the issue, I'll need to manually build and push the container. I'll work on fixing these workflows shortly.
@jgfouca Do we need submodules to be in the `git@github.com:` form?

**Comment by jgfouca** [comment]
@jasonb5 , yes, it is helpful to have submodules in ssh form.

**Comment by jedwards4b** [comment]
@jasonb5 I think I already did that here: https://github.com/ESMCI/cime/pull/4556

**Comment by jasonb5** [comment]
@jedwards4b I'm referring to [.gitmodules](https://github.com/ESMCI/cime/blob/0dac4775041351c3d06d14d6610e474aadc92e05/.gitmodules) in this branch.

**Comment by jedwards4b** [comment]
I just realized that this is going to cause e3sm problems because you will get more than you want.   I may need to think of another way to do this.

**Comment by rljacob** [comment]
Maybe put all those in a .gitmodules in https://github.com/ESCOMP/CESM ?

**Comment by jedwards4b** [comment]
@rljacob They are already there - the point of this .gitmodules was just to be able to do github testing without 
getting all of cesm.  I can figure out another way to do that.

**Comment by jedwards4b** [comment]
I think that I just need to withdraw this PR until the CESM developers decide if they want to remove manage externals or not.  If they do decide to remove manage externals then I will put the new cesm on the trunk before reopening this PR.

**Pull request closed without merging**
