### PR TITLE
Allow for building/running on cori-haswell

### PR DESCRIPTION
**Pull request by ndkeen**
Changes to allow building/running on the Haswell nodes of Cori.  Changed the machine name from corip1 to cori-haswell, added some stubs for cori-knl, removed a default option for the batch directives, and added a constraint to the batch directives to run on the Haswell nodes.  Also updated the Intel compiler version from v16 to v17.

Test suite: cime_developer passed.  acme_developer had a few passes, but many failed which was expected
Test baseline: 
Test namelist changes: 
Test status: [BFB]

Fixes [no github issue]

User interface changes?: no

Code review: 

Allow for building/running on cori-haswell (basically same corip1, but renaming) and some stubs for cori-knl.

### CODE REVIEW

**Comment by rljacob** [comment]
Also hold off on merging this until I've added some other changes to the maint-cime5.1 branch.

**Comment by ndkeen** [comment]
OK, I will wait for you to make new changes to master and I can cut another branch.

**Comment by jedwards4b** [comment]
Please edit your original comment for this pull request and replace the stuff in [] with the requested information as well as indicate what tests were run for this PR.

**Comment by ndkeen** [comment]
Can I push this change?  I've been wanting this in there for a while now.

**Comment by rljacob** [comment]
Yes.

**Comment by jedwards4b** [comment]
Could you improve the initial comment for this PR before you merge.

**Comment by jedwards4b** [comment]
It's here:
https://github.com/ESMCI/cime/pull/809#pullrequestreview-8524392

**Comment by jedwards4b** [comment]
I see now, it looks like you did change it but left in the [] - I was only looking for the [] and so didn't notice.   This is fine.

**Comment by jedwards4b** [comment]
How did you come up with climate_changing in the TestStatus?   Did you actually test something to come to that conclusion?

**Comment by ndkeen** [comment]
Well, I was going to try to upgrade the version of the compiler from Intel 16 to 17.  And I thought we were to assume this would change answers.  But no, I have not compared baselines.  I can do that however.  I've also not verified that the cprnc is working as it did before on this machine.

**Comment by jedwards4b** [comment]
Yes it's answer changing but I don't think that we should use the climate changing flag unless we have good evidence to back it up.   Just updating to a new compiler version should not cause a climate changing difference - although exactly what that means is a subject of much debate.

**Comment by ndkeen** [comment]
I made a new branch for this work.  ndk/machinefiles/cori-haswell-knl

**Pull request merged**
