### PR TITLE
rename CESMSCRATCHROOT to CIME_OUTPUT_ROOT, add cli

### LINKED ISSUE #485: When specifying test root with ./create_test -r test_root, the run/ and bld/ directories should also change
`./create_test cime_developer -r $SCRATCH/acme_scratch/foo -t foo`

Will create `/global/cscratch1/sd/ndk/acme_scratch/foo` with the case directories as expected, however I also get the same case directory names in `/global/cscratch1/sd/ndk/acme_scratch` which contain only bld/ and run/ dirs.

In xml, we have:

``` <RUNDIR>$CESMSCRATCHROOT/$CASE/run</RUNDIR>
  <EXEROOT>$CESMSCRATCHROOT/$CASE/bld</EXEROOT>
```

Could we add $TESTROOT?  That is:
`<RUNDIR>$CESMSCRATCHROOT/$TESTROOT/$CASE/run</RUNDIR>`
Where it would normally be empty unless specified.

@jgfouca edit: Add a flag[s] to create_test to allow user to change rundir and exeroot potentially with a short cut option to have them go under the case directory.

### LINKED ISSUE #569: Evaluate $ENV{USER} before writing env_case.xml?
`env_case.xml` contains the following entry for `USER`:

```
<entry id="USER" value="$ENV{USER}">
```

`$USER` is then used in `$CESMSCRATCHROOT`, which appears in several other environment variables:

```
$ grep \$USER *
env_build.xml:    <entry id="CESMSCRATCHROOT" value="/glade/scratch/$USER">
$ grep \$CESMSCRATCHROOT *
env_build.xml:    <entry id="EXEROOT" value="$CESMSCRATCHROOT/$CASE/bld">
env_run.xml:    <entry id="RUNDIR" value="$CESMSCRATCHROOT/$CASE/run">
env_run.xml:    <entry id="DOUT_S_ROOT" value="$CESMSCRATCHROOT/archive/$CASE">
```

This means that when I do an `xmlquery` on any of those variables in a case created by someone else (@jedwards4b, for example), I see

```
$ cd /glade/scratch/jedwards/SMS_Ld1.f09_f09.FW2000.yellowstone_intel.cam-outfrq1d.GC.20160918_075947
$ ./xmlquery RUNDIR
run_desc:RUNDIR /glade/scratch/mlevy/SMS_Ld1.f09_f09.FW2000.yellowstone_intel.cam-outfrq1d.GC.20160918_075947/run type:char
                       The directory where the executable will be run.       By
                default this is set to EXEROOT/../run.       RUNDIR allows you to
                keep the run directory separate from the build directory
```

which is incorrect (note the `mlevy` instead of `jedwards`). I think the proper behavior is to populate `env_case.xml` with the actual user name rather counting on the xml tools to parse `$USER` from the environment.

This was pointed out by @klindsay28, who often evaluates other peoples' runs... so a common task for him is to start in a case directory that he did not create and pull things like `SRCROOT` and `RUNDIR` into his environment so that he can easily find files related to the run.

### LINKED ISSUE #737: create_clone with --keep-exe uses wrong EXEROOT
I did the following from `cime5.2.0-alpha.7`:

```
./create_clone -clone /glade/p/cesmdata/cseg/runs/cesm2_0/b.e20.B1850.f09_g16.pi_control.all.123 -case $scratch/cesm_tests/b.e20.B1850.f09_g16.pi_control.all.123 -keepexe
```

This let me submit without building, but it died at runtime: 

```
 991:numactl: execution of `/glade/scratch/sacks/b.e20.B1850.f09_g16.pi_control.all.123/bld/cesm.exe': No such file or directory
```

It looks like EXEROOT is set to point to my new case, instead of the bld directory in the cloned case.

### LINKED ISSUE #738: xmlquery EXEROOT in someone else's case gives the wrong path
I went into Cecile's case: `/glade/p/cesmdata/cseg/runs/cesm2_0/b.e20.B1850.f09_g16.pi_control.all.123` and did

```
./xmlquery EXEROOT
```

I get:

```
EXEROOT /glade/scratch/sacks/b.e20.B1850.f09_g16.pi_control.all.123/bld type:char
```

This suggests that Cecile's case is using an EXEROOT in my scratch space, which I'm sure isn't the case.

I think this is a problem with when environment variables are resolved. In particular, I'm guessing that the USER variable is resolved too late here, so that when I do an xmlquery from someone else's case, it treats me as the USER.

I think the solution there is to resolve $USER at create_newcase time and store it in an xml variable... then use that xml user variable in all other places. If I remember correctly, this is consistent with the suggestion made at a recent cseg meeting.

### PR DESCRIPTION
**Pull request by jedwards4b**
Add command line option for --output-root 

Test suite: scripts_regression_tests, create_test cime_developer --output-root /something/else
Test baseline: 
Test namelist changes: 
Test status: bit for bit
Fixes #738 
Fixes #737 
Fixes #569 
Fixes #485 

User interface changes?: 

Code review:

### CODE REVIEW

**Comment by jedwards4b** [comment]
Testing is still in progress.

**Comment by jedwards4b** [comment]
Fixes #369

**Comment by billsacks** [comment]
It looks like #569 is not actually fixed by this: I think it would still be good to resolve the $USER environment variable at create_newcase time rather than leaving it unresolved in the xml files. But if you'd like to defer changing that, we should at least remove the note saying that #569 is fixed by this PR.

**Comment by jedwards4b** [comment]
The intent of #569 is fixed by this PR and I would argue that $USER should be removed from the XML.

**Comment by billsacks** [comment]
> The intent of #569 is fixed by this PR and I would argue that $USER should be removed from the XML.

Okay, that makes sense - I agree.

This PR looks good to me - thanks for addressing all of this!

**Comment by mnlevy1981** [comment]
> The intent of #569 is fixed by this PR and I would argue that $USER should be removed from the XML. 

Can you point to a case directory where this applies? I picked a recent dir from your scratch directory and it doesn't seem to address the issue in #569 at all:

```
$ cd /glade/scratch/jedwards/PEA_P1_Ld3.f45_g37_rx1.A.yellowstone_intel.20161031_102044_v0jl5s
$ ./xmlquery EXEROOT
EXEROOT /glade/scratch/mlevy/PEA_P1_Ld3.f45_g37_rx1.A.yellowstone_intel.20161031_102044_v0jl5s/bld        type:char
```

Not sure if I picked a bad example when checking up on this, though...

**Comment by jedwards4b** [comment]
All tests pass except N_TestCreateTest currently failing on master

**Comment by jedwards4b** [comment]
@mnlevy1981 yes you picked a bad example.   How about 
/glade/scratch/jedwards/cesmtests/ERS_N2_Ld3.f19_g16_rx1.A.yellowstone_intel.20161031_083157_ui7e1s

**Comment by mnlevy1981** [comment]
> How about
/glade/scratch/jedwards/cesmtests/ERS_N2_Ld3.f19_g16_rx1.A.yellowstone_intel.20161031_083157_ui7e1s

Yup, that one looks good. Thanks!

**Comment by jgfouca** [comment]
So are EXEROOT and RUNDIR now derived from CIME_OUTPUT_ROOT?

**Comment by jedwards4b** [comment]
They are still defined in config_component.xml and still appear in the case, but yes they are now
derived from CIME_OUTPUT_ROOT.

**Comment by jgfouca** [comment]
And certain machines can still override EXEROOT in their XML if they want?

**Comment by jedwards4b** [comment]
They would change CIME_OUTPUT_ROOT, they could override EXEROOT if they wanted to but I'm not sure why they would.

**Comment by jgfouca** [comment]
OK, I like this change.

**Pull request merged**
