### PR TITLE
Allow CTSM in compset names

### LINKED ISSUE #3390: Allow CTSM as a valid land compset name
We need to make some changes to allow CTSM as a valid name in compset names.

Here are sample changes off of the maint-5.6 branch (will be moved to a branch off master later) to do this. These changes keep the current names of CLM4_5, and CLM5_0, but start adding CTSM5_1 as a valid option.

One requirement of this is that it seems that the config_archive.xml file in CTSM needs to also allow history/restart filenames with .ctsm. in addition to .clm2.

The branch is called allowctsm and is on @ekluzek's fork.

``` xml
diff --git a/config/cesm/config_grids.xml b/config/cesm/config_grids.xml
index 0ecb5b964..33e207368 100644
--- a/config/cesm/config_grids.xml
+++ b/config/cesm/config_grids.xml
@@ -66,61 +66,61 @@
       <support>Non-standard grid for running POP in true 1D mode</support>
     </model_grid>
 
-    <model_grid alias="CLM_USRDAT" compset="DATM.+CLM">
+    <model_grid alias="CLM_USRDAT" compset="DATM.+CLM|DATM.+CTSM">
       <grid name="atm">CLM_USRDAT</grid>
       <grid name="lnd">CLM_USRDAT</grid>
       <grid name="rof">null</grid>
     </model_grid>
 
-    <model_grid alias="1x1_numaIA" compset="DATM.+CLM">
+    <model_grid alias="1x1_numaIA" compset="DATM.+CLM|DATM.+CTSM">
       <grid name="atm">1x1_numaIA</grid>
       <grid name="lnd">1x1_numaIA</grid>
       <grid name="rof">null</grid>
     </model_grid>
 
-    <model_grid alias="1x1_brazil" compset="DATM.+CLM">
+    <model_grid alias="1x1_brazil" compset="DATM.+CLM|DATM.+CTSM">
       <grid name="atm">1x1_brazil</grid>
       <grid name="lnd">1x1_brazil</grid>
       <grid name="rof">null</grid>
     </model_grid>
 
-    <model_grid alias="1x1_smallvilleIA" compset="DATM.+CLM">
+    <model_grid alias="1x1_smallvilleIA" compset="DATM.+CLM|DATM.+CTSM">
       <grid name="atm">1x1_smallvilleIA</grid>
       <grid name="lnd">1x1_smallvilleIA</grid>
       <grid name="rof">null</grid>
     </model_grid>
 
-    <model_grid alias="1x1_camdenNJ" compset="DATM.+CLM">
+    <model_grid alias="1x1_camdenNJ" compset="DATM.+CLM|DATM.+CTSM">
       <grid name="atm">1x1_camdenNJ</grid>
       <grid name="lnd">1x1_camdenNJ</grid>
       <grid name="rof">null</grid>
     </model_grid>
 
-    <model_grid alias="1x1_mexicocityMEX" compset="DATM.+CLM">
+    <model_grid alias="1x1_mexicocityMEX" compset="DATM.+CLM|DATM.+CTSM">
       <grid name="atm">1x1_mexicocityMEX</grid>
       <grid name="lnd">1x1_mexicocityMEX</grid>
       <grid name="rof">null</grid>
     </model_grid>
 
-    <model_grid alias="1x1_vancouverCAN" compset="DATM.+CLM">
+    <model_grid alias="1x1_vancouverCAN" compset="DATM.+CLM|DATM.+CTSM">
       <grid name="atm">1x1_vancouverCAN</grid>
       <grid name="lnd">1x1_vancouverCAN</grid>
       <grid name="rof">null</grid>
     </model_grid>
 
-    <model_grid alias="1x1_urbanc_alpha" compset="DATM.+CLM">
+    <model_grid alias="1x1_urbanc_alpha" compset="DATM.+CLM|DATM.+CTSM">
       <grid name="atm">1x1_urbanc_alpha</grid>
       <grid name="lnd">1x1_urbanc_alpha</grid>
       <grid name="rof">null</grid>
     </model_grid>
 
-    <model_grid alias="5x5_amazon" compset="DATM.+CLM">
+    <model_grid alias="5x5_amazon" compset="DATM.+CLM|DATM.+CTSM">
       <grid name="atm">5x5_amazon</grid>
       <grid name="lnd">5x5_amazon</grid>
       <grid name="rof">null</grid>
     </model_grid>
 
-    <model_grid alias="hcru_hcru" compset="DATM.+CLM">
+    <model_grid alias="hcru_hcru" compset="DATM.+CLM|DATM.+CTSM">
       <grid name="atm">360x720cru</grid>
       <grid name="lnd">360x720cru</grid>
     </model_grid>
diff --git a/config/cesm/machines/config_pio.xml b/config/cesm/machines/config_pio.xml
index 539dc9556..a0e6c1d80 100644
--- a/config/cesm/machines/config_pio.xml
+++ b/config/cesm/machines/config_pio.xml
@@ -114,6 +114,7 @@
       <value compset="_CLM40" >2</value>
       <value compset="_CLM45" >1</value>
       <value compset="_CLM50" >1</value>
+      <value compset="_CTSM51">2</value>
     </values>
   </entry> -->
 
diff --git a/scripts/Tools/Makefile b/scripts/Tools/Makefile
index 41dc35c82..58abe2f56 100644
--- a/scripts/Tools/Makefile
+++ b/scripts/Tools/Makefile
@@ -768,7 +768,7 @@ test_esmf: test_esmf.o
 #-------------------------------------------------------------------------------
 # create list of component libraries - hard-wired for current ccsm components
 #-------------------------------------------------------------------------------
-CLMVER = $(filter $(CLM_CONFIG_OPTS), clm5_0 clm4_5)
+CLMVER = $(filter $(CLM_CONFIG_OPTS), clm5_0 clm4_5 ctsm5_1)
 ifeq ($(CIME_MODEL),cesm)
   ifneq ($(CLMVER),$(null))
     USE_SHARED_CLM=TRUE
diff --git a/scripts/lib/CIME/build.py b/scripts/lib/CIME/build.py
index 98dd86a2c..8704c4e0c 100644
--- a/scripts/lib/CIME/build.py
+++ b/scripts/lib/CIME/build.py
@@ -255,7 +255,7 @@ def _build_libraries(case, exeroot, sharedpath, caseroot, cimeroot, libroot, lid
         comp_lnd = case.get_value("COMP_LND")
         clm_config_opts = case.get_value("CLM_CONFIG_OPTS")
         if comp_lnd == "clm" and "clm4_0" not in clm_config_opts:
-            logging.info("         - Building clm4_5/clm5_0 Library ")
+            logging.info("         - Building clm4_5/clm5_0/CTSM Library ")
             esmfdir = "esmf" if case.get_value("USE_ESMF_LIB") else "noesmf"
             bldroot = os.path.join(sharedlibroot, sharedpath, comp_interface, esmfdir, "clm","obj" )
             libroot = os.path.join(exeroot, sharedpath, comp_interface, esmfdir, "lib")
diff --git a/src/drivers/mct/cime_config/config_component_cesm.xml b/src/drivers/mct/cime_config/config_component_cesm.xml
index debec5063..ec9d8b583 100644
--- a/src/drivers/mct/cime_config/config_component_cesm.xml
+++ b/src/drivers/mct/cime_config/config_component_cesm.xml
@@ -128,7 +128,7 @@
     <valid_values>none,never,nsteps,nstep,nseconds,nsecond,nminutes,nminute,nhours,nhour,ndays,nday,nmonths,nmonth,nyears,nyear,date,ifdays0,end</valid_values>
     <default_value>never</default_value>
     <values match="last">
-      <value compset="_DATM.+_CLM">ndays</value>
+      <value compset="_DATM.+_CLM|_DATM.+CTSM">ndays</value>
     </values>
     <group>run_begin_stop_restart</group>
     <file>env_run.xml</file>
@@ -149,6 +149,8 @@
       <value compset="^OMIP_DATM%JRA.*_POP2%[^_]*ECO">CO2A</value>
       <value compset="HIST.*_DATM.*_CLM">CO2A</value>
       <value compset="SSP.*_DATM.*_CLM">CO2A</value>
+      <value compset="HIST.*_DATM.*_CTSM">CO2A</value>
+      <value compset="SSP.*_DATM.*_CTSM">CO2A</value>
       <value compset="_BGC%BPRP">CO2C</value>
       <value compset="_BGC%BDRD">CO2C</value>
     </values>
@@ -211,6 +213,7 @@
       <value compset="_CAM\d+%WCXI">288</value>
       <value compset="_DATM%COPYALL_NPS">72</value>
       <value compset="_DATM.*_CLM">48</value>
+      <value compset="_DATM.*_CTSM">48</value>
       <value compset="_DATM.*_DICE.*_POP2">4</value>
       <value compset="_DATM.*_SLND.*_CICE.*_POP2">24</value>
       <value compset="_DATM.*_CICE.*_DOCN">24</value>
@@ -545,6 +548,7 @@
     <values match="last">
       <value compset="_CLM45.+CISM\d">TRUE</value>
       <value compset="_CLM50.+CISM\d">TRUE</value>
+      <value compset="_CTSM.+CISM\d">TRUE</value>
       <!-- Turn on two-way coupling for TG compsets - even though there are no
            feedbacks for a TG compset, this will give us additional diagnostics -->
       <value compset="_DLND.+CISM\d">TRUE</value>
```

### PR DESCRIPTION
**Pull request by ekluzek**
Changes that allow CTSM (in place of CLM) to be in long compset names. Also replace some instances of CLM in documentation for CTSM.

Test suite: Ran scripts_regression_tests.py
Test status: bit-for-bit

Fixes #3390
User interface changes?: No

Update gh-pages html (Y/N)?: N

Code review:

### CODE REVIEW

**Comment by mvertens** [comment]
@erik - sorry for the delay in this review. Is this PR still open? If so it is very old - and will need to be merged iwth the latest cime. If it is no longer relevant - can it be close?

**Comment by billsacks** [comment]
I thought the plan was to wait to do this until we could just replace everything rather than trying to do it in a backwards compatible way - since the latter proved difficult, if I remember correctly. @ekluzek is that right? If so, should this be closed?

**Comment by ekluzek** [comment]
@billsacks yes you are partially right. I couldn't make this completely backwards compatible so you could easily use either CTSM or CLM in compsets without duplication. That said this does do some changes that allow CTSM to be used rather than CLM, so it's some amount of helpful changes.

But, yes I need to try to update it and get it working. If I can do that this would be helpful. If I can't easily do that, we can ditch it and close it. And then we'll make a big change all at once to change CLM to CTSM in all compsets. If we have to close this we won't lose too much, but it would be helpful if we don't have to. So give me a little time to try to do that, and decide if it has any merit moving forward.

**Comment by rljacob** [comment]
telecon notes:  won't fix.

**Pull request closed without merging**
