### PR TITLE
find component for query_config --components

### PR DESCRIPTION
**Pull request by jedwards4b**
Query_config parsing fix to find correct component.

Test suite: hand testing query_config
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes [CIME Github issue #]

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by rljacob** [comment]
What was the problem this is fixing?

**Comment by jedwards4b** [comment]
query_config did not find the correct component when the --components flag was used.

**Comment by rljacob** [comment]
This still isn't working on blues:
```
blogin4[132]: ./query_config --components cam
ERROR: Expected one child
Exit 1
```

**Comment by jedwards4b** [comment]
Is this because you are still using the version 1 format for the config_component.xml files?   Might need @jgfouca to look into this one.

**Pull request merged**
