### PR TITLE
Remove more legacy config_compilers stuff

### PR DESCRIPTION
**Pull request by jgfouca**
Test suite:
Test baseline:
Test namelist changes:
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?:

Update gh-pages html (Y/N)?:

### CODE REVIEW

**Comment by jgfouca** [comment]
Minor PR. Mostly, I want to see what happens in the CI testing.

**Comment by jgfouca** [comment]
@jedwards4b , ah. I see what I did wrong. The check window is scrollable! :)

**Comment by jgfouca** [comment]
@jedwards4b . I had to dig deep, but @jasonb5 helped me find how cdeps was being initialized and cime's Externals.cfg was set to use an older version than CESM's Externals.cfg and this older version had some obsolete references to CIME.XML.compilers. I bumped up the version to match what's being used in CESM.

**Review by jedwards4b — COMMENTED** [review]
excellent - thank you!

**Review by jedwards4b — APPROVED** [review]

**Pull request merged**
