### PR TITLE
make 64bit data default format

### PR DESCRIPTION
**Pull request by jedwards4b**
Makes the 64bit_data format the default.  Removes a requirement that pnetcdf must be built to use this format.

Test suite: scripts_regression_tests.py
Test baseline: 
Test namelist changes: 
Test status: [bit for bit, roundoff, climate changing]

Fixes 

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Review by fischer-ncar — APPROVED** [review]

**Comment by billsacks** [comment]
@jedwards4b I'm curious: You mentioned last week that this might have some performance implications. Do you have any sense of how much performance penalty we might expect to pay with this change? Or do you think it will be negligible?

I'm just thinking that it's probably quite rare that someone will be doing a run that actually requires this change (since you need a variable with over 4 billion elements to require this), so if the performance hit is noticeable, we may want to make this conditional on some heuristic - e.g., only making this change for high res runs, for some definition of high res. (Even normal high res runs – like 1/4 or 1/10 degree – seem very unlikely to require this.)

**Comment by jedwards4b** [comment]
I mentioned that there is a file size implication.  I have not seen any performance implications.

**Comment by jedwards4b** [comment]
1/4 and 1/10 degree runs do require this for some components.

**Comment by billsacks** [comment]
Okay, sounds good - thanks for the clarification.

**Pull request merged**
