### PR TITLE
Remove mct for cesm

### PR DESCRIPTION
**Pull request by jedwards4b**
mct library is no longer needed for cesm.

Test suite:
Test baseline:
Test namelist changes:
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?:

Update gh-pages html (Y/N)?:

### CODE REVIEW

**Review by jgfouca — APPROVED** [review]
This makes me a little nervous due to the path changes, but I can fix up any impacts to CMake.

**Comment by rljacob** [comment]
This makes me a little...wistful.   But E3SM will be doing this eventually.

**Comment by brian-eaton** [comment]
@rljacob, me too:)  Thanks for the good work on MCT which got the job done for many years.  It was a rock solid lightweight coupling toolkit!

**Comment by jasonb5** [comment]
@jedwards4b I believe the remaining failures are due to `cmeps` and `csm_share` submodules needing to be updated.

**Comment by jedwards4b** [comment]
Is it okay to merge then?   Thank you so much for your help.

**Comment by jasonb5** [comment]
@jedwards4b Yea it should be fine to merge.

**Comment by jedwards4b** [comment]
Updated latest cime tag to be cime6.1.0

**Pull request merged**
