### PR TITLE
ufs_release_v1.1: remove unnecessary/incorrect configuration options for Cheyenne for the UFS; downgrade Intel 19.x.y to 18.m.n on Cheyenne, Gaea, Orion

### PR DESCRIPTION
**Pull request by climbfuji**
### Description

This PR removes a whole bunch of unnecessary/incorrect configuration options for Cheyenne for the UFS and reverts Intel back to Intel-18.0.5 on Cheyenne, Gaea, Orion.

Beforehand, the CIME regression tests failed frequently in `chgres_cube.exe` for the highest resolution cases, see description here: https://github.com/ufs-community/ufs-mrweather-app/issues/190

With this change and the associated change in the ufs-weather-model and NCEPLIBS-external (documentation only), the regression tests ran successfully (tried one time thus far, will conduct multiple runs to make sure I wasn't just lucky).
```
export UFS_DRIVER=nems
export UFS_INPUT=$CESMDATAROOT
export UFS_SCRATCH=/glade/work/heinzell/fv3/ufs-mrweather-app/ufs_scratch
qcmd -l walltime=3:00:00 -- "export UFS_DRIVER=nems; CIME_MODEL=ufs ./create_test --xml-testlist ../../src/model/FV3/cime/cime_config/testlist.xml --xml-machine cheyenne --xml-compiler intel --workflow ufs-mrweather_wo_post -j 4 --walltime 03:00:00"

...

heinzell@cheyenne3:/glade/work/heinzell/fv3/ufs-mrweather-app/ufs-mrweather-app-release-public-v1/cime/scripts> /glade/work/heinzell/fv3/ufs-mrweather-app/ufs_scratch/cs.status.20200917_210120_2ap63n | grep Overall
  ERS_Lh11.C96.GFSv15p2.cheyenne_intel (Overall: PASS) details:
  ERS_Lh11.C96.GFSv16beta.cheyenne_intel (Overall: PASS) details:
  PET_Lh11.C96.GFSv15p2.cheyenne_intel (Overall: PASS) details:
  SMS_Lh3.C192.GFSv15p2.cheyenne_intel (Overall: PASS) details:
  SMS_Lh3.C192.GFSv16beta.cheyenne_intel (Overall: PASS) details:
  SMS_Lh3.C384.GFSv15p2.cheyenne_intel (Overall: PASS) details:
  SMS_Lh3.C384.GFSv16beta.cheyenne_intel (Overall: PASS) details:
  SMS_Lh3.C768.GFSv15p2.cheyenne_intel (Overall: PASS) details:
  SMS_Lh3.C768.GFSv16beta.cheyenne_intel (Overall: PASS) details:
  SMS_Lh3.C96.GFSv15p2.cheyenne_intel (Overall: PASS) details:
  SMS_Lh3.C96.GFSv16beta.cheyenne_intel (Overall: PASS) details:
  SMS_Lh3_D.C192.GFSv15p2.cheyenne_intel (Overall: PASS) details:
  SMS_Lh3_D.C192.GFSv16beta.cheyenne_intel (Overall: PASS) details:
  SMS_Lh3_D.C384.GFSv15p2.cheyenne_intel (Overall: PASS) details:
  SMS_Lh3_D.C384.GFSv16beta.cheyenne_intel (Overall: PASS) details:
  SMS_Lh3_D.C768.GFSv15p2.cheyenne_intel (Overall: PASS) details:
  SMS_Lh3_D.C768.GFSv16beta.cheyenne_intel (Overall: PASS) details:
  SMS_Lh3_D.C96.GFSv15p2.cheyenne_intel (Overall: PASS) details:
  SMS_Lh3_D.C96.GFSv16beta.cheyenne_intel (Overall: PASS) details:
```

The PR also replaces a few tabs with whitespaces for consistent formatting in `config/ufs/machines/config_machines.xml`.

Note that we will need to (re-)create tag `ufs-v1.1.0` (or whatever the CIME convention is; this is what we use for all the UFS components and external libraries, and what is also consistent with MRW App release 1.0).

### CODE REVIEW

**Review by billsacks — CHANGES_REQUESTED** [review]
Please change the base branch of this PR. (I know you acknowledged this in your initial comment, but seeing this PR into master makes me nervous, and I want to mark this as "request changes" until you fix that.)

**Comment by climbfuji** [comment]
We are discussing this right now in the MRW App release telecon, @uturuncoglu will take care of it.

**Comment by uturuncoglu** [comment]
@climbfuji I created a branch called ufs_release_v1.1 and you could post your PR to that branch. Thanks.
@billsacks we also need to new version of CIME documentation for UFS release 1.1. The current one is http://esmci.github.io/cime/versions/ufs_release_v1.0/html/index.html but new one need to be http://esmci.github.io/cime/versions/ufs_release_v1.1/html/index.html

**Comment by billsacks** [comment]
@uturuncoglu you should be able to create the new documentation version yourself. Please see https://github.com/esmci/cime/wiki/Working-with-Sphinx-and-reStructuredText for details. I just added a section on how to add a new version. Let me know if you run into trouble.

**Comment by uturuncoglu** [comment]
@billsacks thanks for the doc. I'll try and let you know if I have any problem.

**Comment by climbfuji** [comment]
@uturuncoglu I changed the target branch to `ufs_release_v1.1` - commit history looks clean, and only two files are changed.

**Comment by uturuncoglu** [comment]
@climbfuji okay that is great. @billsacks if you don't mind could you merge it. I have no rights to merge it.

**Review by billsacks — APPROVED** [review]

**Comment by uturuncoglu** [comment]
@billsacks I created the doc and push to gh-pages but I could not see it in the drop down menu. I also updated versions/versions.json file. May be it is just a issue related with the browser.

**Comment by uturuncoglu** [comment]
@billsacks i fixed the issue. now it is fine. thanks for your help.

**Pull request merged**
