### PR TITLE
Add cesm_postbuild functionality into build.py:post_build for acme

### LINKED ISSUE #325: Reproduce ACME build provenance features
The following code from the cesm_postbuild needs to be reimplemented.  It saves info relevant to the build in the EXEROOT.

```
cd $cesmroot

if (-d $cesmroot/.git) then
  git describe > $exe_dir/GIT_DESCRIBE.$lid
  chmod 664 $exe_dir/GIT_DESCRIBE.$lid
  /bin/cp -p $exe_dir/GIT_DESCRIBE.$lid $exe_dir/GIT_DESCRIBE

  if (-f $cesmroot/.git/logs/HEAD) then
    /bin/cp $cesmroot/.git/logs/HEAD $exe_dir/GIT_LOGS_HEAD.$lid
    chmod 664 $exe_dir/GIT_LOGS_HEAD.$lid
    /bin/cp -p $exe_dir/GIT_LOGS_HEAD.$lid $exe_dir/GIT_LOGS_HEAD
  else
    /bin/rm -f $exe_dir/GIT_LOGS_HEAD
    touch $exe_dir/GIT_LOGS_HEAD
  endif
endif

if (-d $caseroot/SourceMods) then
  cd $caseroot
  /bin/tar cf $exe_dir/SourceMods.$lid.tar SourceMods
  cd $exe_dir
  /bin/cp SourceMods.$lid.tar SourceMods.tar
endif

if (-f $caseroot/software_environment.txt) then
  cd $caseroot
  /bin/cp software_environment.txt $exe_dir/build_environment.$lid.txt
  cd $exe_dir
  /bin/cp build_environment.$lid.txt build_environment.txt
endif
```

### PR DESCRIPTION
**Pull request by jgfouca**
Test suite: by hand
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes #325

User interface changes?: new build provenance files

Code review: @rljacob

### CODE REVIEW

**Comment by jgfouca** [comment]
@rljacob any thoughts oh this?

**Comment by rljacob** [comment]
Tried testing this branch on edison and got an error in case.setup:
ERROR: Command: 'module list 2>&1' failed with error ''

**Comment by jgfouca** [comment]
@rljacob Does CIME even work on edison?

**Comment by rljacob** [comment]
Yes.  CSEG runs there and @amametjanov verified it for ACME.

**Comment by jgfouca** [comment]
OK, let me jump onto edison and see what's up.

**Comment by jgfouca** [comment]
@rljacob , I can't reproduce your error on edison:
```
At test-scheduler close, state is:
status=PASS test=SEQ_Ln9.f19_g16_rx1.A.edison_intel phase=SETUP
    Case dir: /scratch1/scratchdirs/acmetest/acme_scratch/SEQ_Ln9.f19_g16_rx1.A.edison_intel.20160808_202752
status=PASS test=SMS_D_Ln9_Mmpi-serial.f19_g16_rx1.A.edison_intel phase=SETUP
    Case dir: /scratch1/scratchdirs/acmetest/acme_scratch/SMS_D_Ln9_Mmpi-serial.f19_g16_rx1.A.edison_intel.20160808_202752
status=PASS test=ERR_Ld3.f45_g37_rx1.A.edison_intel phase=SETUP
    Case dir: /scratch1/scratchdirs/acmetest/acme_scratch/ERR_Ld3.f45_g37_rx1.A.edison_intel.20160808_202752
status=PASS test=ERS_N2_Ld3.f19_g16_rx1.A.edison_intel phase=SETUP
    Case dir: /scratch1/scratchdirs/acmetest/acme_scratch/ERS_N2_Ld3.f19_g16_rx1.A.edison_intel.20160808_202752
status=PASS test=NCK_Ld3.f45_g37_rx1.A.edison_intel phase=SETUP
    Case dir: /scratch1/scratchdirs/acmetest/acme_scratch/NCK_Ld3.f45_g37_rx1.A.edison_intel.20160808_202752
status=PASS test=ERS_Ld3.ne30_g16_rx1.A.edison_intel phase=SETUP
    Case dir: /scratch1/scratchdirs/acmetest/acme_scratch/ERS_Ld3.ne30_g16_rx1.A.edison_intel.20160808_202752
status=PASS test=ERI.f45_g37.X.edison_intel phase=SETUP
    Case dir: /scratch1/scratchdirs/acmetest/acme_scratch/ERI.f45_g37.X.edison_intel.20160808_202752
```

**Comment by rljacob** [comment]
I was running create_newcase and case.setup by hand.
 ./create_newcase -case Xcase4 -compset X -res f19_g16
cd Xcase4
./case.setup

The error message is at the end of case.setup output.

**Comment by rljacob** [comment]
For module-based systems, we should do what was done on cori:
```
module list >& software_environment.txt
env >>&  software_environment.txt
```

**Comment by rljacob** [comment]
@worleyph,  Is this how the current SAVE_TIMING logic works in ACME?
SAVE_TIMING is default TRUE for all machines.  SAVE_TIMING=TRUE at minimum causes the "timing" dir to have $lid appended to its name and get tar'd up and gzip'd in the $RUNDIR.

Only some machines have SAVE_TIMING_DIR defined and it must be defined and exist for the majority of the save_timing activity to be enabled (including saving that gzip'd timing dir).

create_test will set SAVE_TIMING to FALSE when calling create_newcase.

**Comment by rljacob** [comment]
Running with SAVE_TIMING = TRUE on this branch gave an error in case.submit:

```
timing dir is /lcrc/project/ACME
Traceback (most recent call last):
  File "/var/spool/torque/mom_priv/jobs/1376291.bmgt1.lcrc.anl.gov.SC", line 114, in <module>
    _main_func(__doc__)
  File "/var/spool/torque/mom_priv/jobs/1376291.bmgt1.lcrc.anl.gov.SC", line 109, in _main_func
    success = case_run(case)
  File "/lcrc/group/earthscience/jacob/cimeESMCI/utils/python/CIME/case_run.py", line 409, in case_run
    save_timing_setup_acme(case, lid)
  File "/lcrc/group/earthscience/jacob/cimeESMCI/utils/python/CIME/case_run.py", line 164, in save_timing_setup_acme
    full_timing_dir = os.path.join(timing_dir, "performance_archive", getpass.getuser(), base_case, lid)
  File "/soft/python/2.7.6/lib/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by jgfouca** [comment]
@rljacob 

>>> For module-based systems, we should do what was done on cori:
>>> module list >& software_environment.txt
>>> env >>&  software_environment.txt

This should be exactly what's happening with this PR.

**Comment by jgfouca** [comment]
@rljacob 

> I tried on blues and did not get that error. But the software_environment.txt file seems to have both > "printenv" and the output of "softenv" which lists every softkey on the system, not the ones loaded. > There is no command for the ones loaded so for soft systems we should just do "printenv".

I know the output of softenv is cluttered, but doesn't it provide some indication of which softkeys are loaded?

**Comment by rljacob** [comment]
No it doesn't.

**Comment by worleyph** [comment]
@rljacob ,

     >@worleyph, Is this how the current SAVE_TIMING logic works in ACME? ...

Yes.

I believe that the SAVE_TIMING logic is the same as in CESM. The SAVE_TIMING_DIR and associated logic has been specific to ACME (and to the ACES4BGC branch of the CESM, if that still exists).

The ACME implementation of SAVE_TIMING may be a little skewed from that in CESM. I think that I had to move some logic around when I introduced SAVE_TIMING_DIR.

**Comment by worleyph** [comment]
@rljacob , I'm misremembering - creating the tarball and gzipping was something I added. Renaming the timing directory when SAVE_TIMING is true has been in CESM (looking at cesm1_4_beta01). However, the default for SAVE_TIMING in CESM appears to have been FALSE, not TRUE. 

The rationale for SAVE_TIMING is so that timing data from previous runs would not be lost. At one point, new data just overwrote the old (and there could be a mix of timing data files in certain situtations). The current logic (CESM and ACME) is to delete an existing timing subdirectory at the start of a new run.

**Comment by jgfouca** [comment]
@rljacob I've push a commit that addresses your save timing issue and the soft issue.

**Comment by rljacob** [comment]
case.submit now works on blues with SAVE_TIMING=TRUE and the software_environment.txt file looks good.

**Comment by jgfouca** [comment]
Ready to merge?

**Comment by rljacob** [comment]
Not yet.  More testing.

**Comment by rljacob** [comment]
Still getting this non fatal error message on edison:
`ERROR: Command: 'module list 2>&1' failed with error ''`
And the software_environment.txt file is empty after case.setup

**Comment by jgfouca** [comment]
@rljacob Yeah, that error is going to abort the setup. Why would module list return non-zero? I'm not seeing this behavior from my login shell.

**Comment by rljacob** [comment]
It doesn't seem to affect any of the other scripts.  case.build still works.  case.submit had a problem but that might be on master without SAVE_TIMING.  Looking in to it.

**Comment by rljacob** [comment]
@jgfouca to test this on edison, you'll need to use create_newcase, then cd to the case and use ./xmlchange to set SAVE_TIMING to true, then continue with case.setup, case.build, case.submit.  You'll also need the changes for edison from PR #363

**Comment by jgfouca** [comment]
@rljacob , I've rebased this branch onto latest master in order to pick up recent changes. If you set SAVE_TIMING and CHECK_TIMING to true, things should work. I'd test myself, but for some reason, edison is rejecting my submissions.

**Comment by rljacob** [comment]
My tests have been sitting in the queue for over a day.  I want to test on a machine were "SAVE_TIMING" has been true for a while (not blues).  I'll try Mira.

**Comment by jedwards4b** [comment]
Boy you know it's bad when you want to go to mira because another system is too slow!

**Comment by rljacob** [comment]
Yeah instead I switched to the debug queue on edison and also set up timing to work on Blues.

Some things are missing from SAVE_TIMING_DIR.  

On blues, compare what ACME does:
/lcrc/project/ACME/performance_archive/jacob/Xcasetiming/160810-180923

with this branch:
lcrc/project/ACME/performance_archive/jacob/Xcasenewtiming/160810-183040

Mostly its a few more items that need to be copied, appended with $lid and gzip'd.

But there's also sections in ACME/cime/machines-acme/cesm_prerun.perf_archive and cesm_postrun.perf_archive that query the queue.  Look for "titan" in those files.

You can also see an example of what ACME does on edison in:
/project/projectdirs/acme/performance_archive/rjacob/tryXtiming/160810-154754

**Comment by jgfouca** [comment]
@rljacob I thought the queue query was a bit excessive, does that really provide value?

**Comment by worleyph** [comment]
@jgfouca , the queue query is meant to help debug interference from other users, and is part of the data collected to help understand performance variability. As long as it does not cause problems, I would like to keep it. As always for my stuff, this is an ACME-project-specific capability, and need not be foisted on external users. We have used it however, e.g., in the unsuccessful attempt to diagnose the source of Edison slowdowns.

**Comment by jgfouca** [comment]
@worleyph OK, if it's been used in the past and adds value, i'll see if I can work it into the acme post run.

**Comment by worleyph** [comment]
@jgfouca , it is not currently in the "post run". There is little utility after the fact. Currently it is in the cesm_prerun script, querying the queue right before the aprun/srun/mpirun/... is submitted and also in the background job monitoring script.

**Comment by jgfouca** [comment]
Oh yeah, thanks

**Comment by jgfouca** [comment]
@rljacob looks like I did try to preserve the capability to record queue information. If you look at the file you referred me to (ACME/cime/machines-acme/cesm_prerun.perf_archive), you'll see that this information is only gathered for certain machines (mira, cori, edison, titan). So, I'm wondering how your blues run was able to gather this info?

**Comment by rljacob** [comment]
I edited that code (after it was copied to my $CASEROOT/Tools dir) to do the same for Blues as was done for Titan.  I didn't look to see if there were machine-specific clauses in the ESMCI version that I also had to edit.  Let me try this branch on edison again.

**Comment by jgfouca** [comment]
@rljacob I made some changes to this branch to enforce the naming conversion (LID in all names) and the zipping of all files.

**Comment by rljacob** [comment]
This latest branch is giving me errors on during prerun.
'''timing dir is /project/projectdirs/acme
Traceback (most recent call last):
  File "/var/spool/slurmd/job1743333/slurm_script", line 114, in <module>
    _main_func(__doc__)
  File "/var/spool/slurmd/job1743333/slurm_script", line 109, in _main_func
    success = case_run(case)
  File "/global/u2/r/rjacob/cimeESMCI/utils/python/CIME/case_run.py", line 420, in case_run
    save_timing_setup_acme(case, lid)
  File "/global/u2/r/rjacob/cimeESMCI/utils/python/CIME/case_run.py", line 172, in save_timing_setup_acme
    job_id = _get_batch_job_id(case)
  File "/global/u2/r/rjacob/cimeESMCI/utils/python/CIME/case_run.py", line 143, in _get_batch_job_id
    return os.environ("SLURM_JOB_ID")
AttributeError: _Environ instance has no __call__ method
'''

**Comment by jgfouca** [comment]
@rljacob try now

**Comment by jgfouca** [comment]
@rljacob , these were your comments on slack earlier; I'm adding these now.
```
On edison, GIT_LOGS_HEAD still needs to be copied, zipped.
1:10
As does build_environment. and “checkpoints” and the sq* files.
```

**Comment by jgfouca** [comment]
I just added a commit that copies GIT_LOGS_HEAD from the exedir to the timing dir.

Some comments: build_environment is just an exact copy of software_environment.txt which is already being archived, so I'm wondering if we can just forget about this file.

In most cases, the old system would create a checkpoints directory in the archive but then leave it empty. The new system just doesn't make it unless it's actually needed. Was your checkpoints directory on edison empty?

That is strange that the sq files were missing on edison. Can you point me to your archive?

**Comment by worleyph** [comment]
> In most cases, the old system would create a checkpoints directory in the archive but then leave it empty. The new system just doesn't make it unless it's actually needed. Was your checkpoints directory on edison empty?

Curious what determines whether the checkpoints directory is needed or not. This subdirectory is populated by the background job monitoring script. Does the background job create the subdirectory?

**Comment by rljacob** [comment]
My directory in /project/projectdirs/acme/performance_archive on edison seems to have vanished so I'm regenerating old and new.

@worleyph, can you answer Jim's question about archiving software_environment.txt vs. build_environment.txt?   Also, what is supposed to be in the checkpoints directory?

**Comment by worleyph** [comment]
if (-f $caseroot/software_environment.txt) then
       cd $caseroot
       /bin/cp software_environment.txt $exe_dir/build_environment.$lid.txt
       cd $exe_dir
       /bin/cp build_environment.$lid.txt build_environment.txt
     endif

and

         if (-f $exe_dir/build_environment.txt) then
           cp -p $exe_dir/build_environment.txt build_environment.$lid
         endif

software_environment.txt is renamed build_environment right after the build and saved in the build directory. For the current logic, software_environment is not saved (by that name) in the performance archive. The "provenance" collected is the environment during the build.

**Comment by rljacob** [comment]
I reran an X-case with timing using ACME can got the expected output visible on edison at:  /project/projectdirs/acme/performance_archive/rjacob/tryXtiming/160818-190824/

But this branch is giving me an error after case.submit:
`
edison09 scripts/Xcasenewtiming> more Xcasenewtiming.run 
timing dir is /project/projectdirs/
Traceback (most recent call last):
  File "/var/spool/slurmd/job1826523/slurm_script", line 114, in <module>
    _main_func(__doc__)
  File "/var/spool/slurmd/job1826523/slurm_script", line 109, in _main_func
    success = case_run(case)
  File "/global/u2/r/rjacob/cimeESMCI/utils/python/CIME/case_run.py", line 429, in case_run
    save_timing_setup_acme(case, lid)
  File "/global/u2/r/rjacob/cimeESMCI/utils/python/CIME/case_run.py", line 167, in save_timing_setup_acme
    os.makedirs(full_timing_dir)
  File "/usr/common/usg/python/2.7.9/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/common/usg/python/2.7.9/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/common/usg/python/2.7.9/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/common/usg/python/2.7.9/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/project/projectdirs/performance_archive'
`

**Comment by worleyph** [comment]
> Also, what is supposed to be in the checkpoints directory?

The job monitoring script "samples" a variety of different progress-related information. 

a) beginning of cesm.log (hopefully capturing the mapping of processes/threads to nids/cores)
b) timing files in timing/checkpoints
c) last 10 lines (tail) of grep for "step" (component model specific) for each component log
d) jobs running and jobs in queue, e.g. showq
e) where jobs are running (on Titan), e.g. xnodestat

This directory will be emply if the job ends before the first sample time (default is 15 minutes).

**Comment by worleyph** [comment]
@rljacob , if you want to force information to show up in the checkpoint directory, you should set 

     <entry id="SYSLOG_N"   value="900"  />

to something smaller, say

     <entry id="SYSLOG_N"   value="30"  />

to get data every 30 seconds.

**Comment by worleyph** [comment]
@rljacob , would expect the directory name to be

/project/projectdirs/<project name>/performance_archive

e.g.

/project/projectdirs/acme/performance_archive

not 

/project/projectdirs/performance_archive

(which you won't have permissions to create).

**Comment by rljacob** [comment]
I didn't have $PROJECT defined which led to the error my (now deleted) message here.

ACME for and X case has:
`
ls /project/projectdirs/acme/performance_archive/rjacob/tryXtiming/160818-190824/ -F
CaseDocs.160818-190824/             cesm.log.160818-190824.gz                sqsf_jobid.160818-190824.gz
CaseStatus.160818-190824.gz         cesm_timing.tryXtiming.160818-190824.gz  sqsw.160818-190824.gz
GIT_DESCRIBE.160818-190824.gz       cesm_timing_stats.160818-190824.gz       squeue.160818-190824.gz
GIT_LOGS_HEAD.160818-190824.gz      checkpoints/                             timing.160818-190824.tar.gz
SourceMods.160818-190824.tar.gz     cpl.log.160818-190824.gz                 tryXtiming.160818-190824.gz
build_environment.160818-190824.gz  sqsf.160818-190824.gz
`

**Comment by rljacob** [comment]
I tried Pat's suggestion for SYSLOG_N, reran, and got a new timing archive with more data in checkpoints:
```
/global/project/projectdirs/acme/performance_archive/rjacob/tryXtiming/160818-195149/checkpoints
edison01 160818-195149/checkpoints> ls -F
atm.log.160818-195149.nstep.1706.gz  cesm_timing_00010104_00000.00.gz         ice.log.160818-195149.istep.1741.gz
atm.log.160818-195149.nstep.1741.gz  cesm_timing_00010104_00000_stats.gz      lnd.log.160818-195149.timestep.1706.gz
cesm.log.160818-195149.1741.gz       cesm_timing_00010105_00000.00.gz         lnd.log.160818-195149.timestep.1741.gz
cesm_timing_00010102_00000.00.gz     cesm_timing_00010105_00000_stats.gz      ocn.log.160818-195149.stepnum.1706.gz
cesm_timing_00010102_00000_stats.gz  cpl.log.160818-195149.modeldata.1706.gz  ocn.log.160818-195149.stepnum.1741.gz
cesm_timing_00010103_00000.00.gz     cpl.log.160818-195149.modeldata.1741.gz  sqsw.160818-195149.1706.gz
cesm_timing_00010103_00000_stats.gz  ice.log.160818-195149.istep.1706.gz      sqsw.160818-195149.1741.gz
```

**Comment by jgfouca** [comment]
@worleyph , the environment for the build and run are identical. In both cases, the env settings from XML are loaded. Also, in my timing directory, I do see software_environment being saved under the CaseDocs directory.

**Comment by worleyph** [comment]
@jgfouca , executables can be built and retained for a long time - and system defaults can change (things not specificed directly) between build and run time. I really want to preserve the settings when the model was built as part of the provenance.
Our ACME runs do not include something called software_environment in the performance_archive (on Titan at least).

**Comment by worleyph** [comment]
Just looked on NERSC, and neither software_environment nor build_environment is being saved in some of the most recent jobs. This is a change from last week (?), in which build_environment was saved (but no software_environment).

This is a bug. 

@ndkeen did you change the archiving of software_environment.txt in your recent script modifications?

**Comment by jgfouca** [comment]
@worleyph I'm agreeing with you that the environment needs to be archived for provenance. What I'm saying is that there's no point in archiving both a build_environment and software_environment file when they are exactly the same. I do see software_environment being saved when I run this branch.

**Comment by worleyph** [comment]
> I do see software_environment being saved when I run this branch.

I don't see this in ACME. Thought that you were commenting on ACME.

**Comment by ndkeen** [comment]
The only thing I changed was in the current (old) cime.  All I know to use as nouns are old and new cime.  This forum is apparently new cime related.  I *added* the output of environment to software_environment.txt a few weeks ago for corip1.  I'm currently working on making some module updates to edison and will also do the same there.

**Comment by jgfouca** [comment]
@worleyph , I'm just taking to make sure this branch will meet ACME's needs for provenance.

**Comment by worleyph** [comment]
@ndkeen , Thanks. I was confused and thought that @jgfouca was using "old" cime / ACME as the model and was commeting on its design. Sounds like the new cime simply has a bug.
However, for some reason "old" cime is not capturing build_environment (at the moment?) on corip or edison. I looked at the script logic and it looks fine. I'll keep poking.

**Comment by jgfouca** [comment]
@worleyph , it looks like SYSLOG_N doesn't even exist in CIME5

**Comment by jgfouca** [comment]
I added it. It looks like mach_syslog is the only thing that uses it, so it should work now.

**Comment by jgfouca** [comment]
@rljacob @worleyph I think this branch should be ready

**Comment by rljacob** [comment]
Tried latest branch on edison and got an error:
```
timing dir is /project/projectdirs/acme
Traceback (most recent call last):
  File "/var/spool/slurmd/job1887828/slurm_script", line 114, in <module>
    _main_func(__doc__)
  File "/var/spool/slurmd/job1887828/slurm_script", line 109, in _main_func
    success = case_run(case)
  File "/global/u2/r/rjacob/cimeESMCI/utils/python/CIME/case_run.py", line 433, in case_run
    save_timing_setup_acme(case, lid)
  File "/global/u2/r/rjacob/cimeESMCI/utils/python/CIME/case_run.py", line 242, in save_timing_setup_acme
    with open(os.path.join(rundir, "syslog_jobid", ".%s" % job_id), "w") as fd:
IOError: [Errno 2] No such file or directory: '/scratch2/scratchdirs/rjacob/acme_scratch/Xcasenewtiming/run/syslog_jobid/.1887828'
```

**Comment by jedwards4b** [comment]
I think that line should be:
```
with open(os.path.join(rundir, "syslog_jobid.%s" % job_id), "w") as fd:
```

**Comment by jgfouca** [comment]
Fix pushed,  @jedwards4b was correct.

**Comment by rljacob** [comment]
Output is looking much better.  Will try again with lower SYSLOG_N.

**Comment by rljacob** [comment]
Still nothing in "checkpoints/" even with SYSLOG_N set to 30.
```
edison07 Xcasenewtiming/160826-152001> ls -F
CaseDocs.160826-152001/        GIT_LOGS_HEAD.160826-152001.gz   acme_timing.Xcasenewtiming.160826-152001.gz  checkpoints/
CaseStatus.160826-152001.gz    SourceMods.160826-152001.tar.gz  acme_timing_stats.160826-152001.gz           cpl.log.160826-152001.gz
GIT_DESCRIBE.160826-152001.gz  acme.log.160826-152001.gz        build_environment.txt.160826-152001.gz       timing.160826-152001.tar.gz
edison07 Xcasenewtiming/160826-152001> pwd
/global/project/projectdirs/acme/performance_archive/rjacob/Xcasenewtiming/160826-152001
```

**Comment by jgfouca** [comment]
Hi @rljacob , i should probably just debug this myself. Seems like you're getting your runs done before too long. What is the create_test command that you're using?

**Comment by rljacob** [comment]
To set up this case:
```
./create_newcase -case Xcasenewtime2 -compset X -res f19_g16
cd Xcasenewtime2
cp ~rjacob/env_mach_pes.xml .
./xmlchange PROJECT=acme
./xmlchange SAVE_TIMING=true
./case.setup
edit case.run and change "partition" to "debug" and time to 00:30:00
./case.build
./case.submit
```

**Comment by jgfouca** [comment]
Looks like edison is down for two weeks!?
```
Degraded. 08/29/16 8:00-09/09/16 12:00 PDT, Scheduled
                  maintenance.
                  Edison /scratch1 and /scratch2 unavailable for filesystem
                  re-formatting and upgrade.  All data on Edison /scratch1 and
                  /scratch2 will be deleted. 
```

**Comment by ndkeen** [comment]
Not exactly.  Scratch system down, but you can use Cori's scratch.
`/global/cscratch1/sd/ndk` for example

**Comment by jgfouca** [comment]
@rljacob I've updated this branch and I believe everything should be working now though I still have had a hard time testing the checkpoints.

**Comment by rljacob** [comment]
I think it has the bug from #509 .  I got the same error message.

**Comment by jgfouca** [comment]
@rljacob sorry, i'm dumb. forgot to push my local commits. try again

**Comment by rljacob** [comment]
Ok branch works but still no content in the checkpoints directory.
```
edison04 Xcasenewtiming/160907-113808> pwd
/global/project/projectdirs/acme/performance_archive/rjacob/Xcasenewtiming/160907-113808
edison04 Xcasenewtiming/160907-113808> ls -F
CaseDocs.160907-113808/          acme.log.160907-113808.gz               sqsf.160907-113808.gz
CaseStatus.160907-113808.gz      acme_timing_stats.160907-113808.gz      sqsf_jobid.160907-113808.gz
GIT_DESCRIBE.160907-113808.gz    build_environment.txt.160907-113808.gz  sqsw.160907-113808.gz
GIT_LOGS_HEAD.160907-113808.gz   checkpoints.160907-113808/              squeuef.160907-113808.gz
SourceMods.160907-113808.tar.gz  cpl.log.160907-113808.gz                timing.160907-113808.tar.gz
```

**Comment by jgfouca** [comment]
Right, but there was probably no content in the checkpoints directory in the RUNDIR for the case either.

**Comment by rljacob** [comment]
That's right. Nothing in /global/cscratch1/sd/rjacob/acme_scratch/Xcasenewtiming/run

**Comment by jgfouca** [comment]
OK, so it did what it was supposed to then.

**Comment by rljacob** [comment]
You're not implementing the checkpoint stuff yet?

**Comment by jgfouca** [comment]
The contents of checkpoints is populated by mach_syslog. The only thing my code does is move what's there to performance archive.

**Comment by rljacob** [comment]
Ok I'll go ahead and merge this and if there's a problem with mach_syslog, that'll be a new issue.

**Pull request merged**
