### PR TITLE
Sarich/fix config pes converter

### LINKED ISSUE #792: config_pes_converter.py not liking some XML comments
Comments like this in the current ACME cime2 config_pesall.xml:

```
<!-------------------------------------------------------------------------------
  tasks/thread setup - GRID for one grid (not a pair of grids)
 ------------------------------------------------------------------------------->
```

Are generating errors like:
blogin1[97]: ./config_pes_converter.py -cime2file /lcrc/group/earthscience/jacob/ACMEpure/cime/machines-acme/config_pes.xml -cime4file ../../cime_config/acme/allactive/config_pesall.xml
```
Traceback (most recent call last):
  File "./config_pes_converter.py", line 266, in <module>
    pes_compare()
  File "./config_pes_converter.py", line 258, in pes_compare
    cime2pestree = PesTree(cime2file)
  File "/lcrc/group/earthscience/jacob/cimeESMCI/scripts/Tools/grid_xml_converter.py", line 261, in __init__
    self.doc = ET.parse(xmlfilename)
  File "/soft/python/2.7.6/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/soft/python/2.7.6/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/soft/python/2.7.6/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/soft/python/2.7.6/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 244, column 6
Exit 1
```

### PR DESCRIPTION
**Pull request by sarich**
The cime2 version of config_pes.xml has ill-formed xml code that won't parse in python ElementTree. 
This update automatically fixes the old xml files before trying to parse.

It also now uses the current cime version name 'cime5' and fixes an inheritance bug

Test suite: 
Test baseline: 
Test namelist changes: 
Test status: [bit for bit, roundoff, climate changing]

Fixes #792 

User interface changes?: 

Code review:

### CODE REVIEW

**Comment by rljacob** [comment]
Thanks for fixing this as it is needed.

I tried this command: 
`./config_pes_converter.py -cime2file /lcrc/group/earthscience/jacob/ACMEpure/cime/machines-acme/config_pes.xml -cime5file /lcrc/group/earthscience/jacob/ACME5/cime/cime_config/acme/allactive/config_pesall.xml`

And first got this error:
```
Traceback (most recent call last):
  File "./config_pes_converter.py", line 12, in <module>
    from standard_script_setup import *
ImportError: No module named standard_script_setup
```

So I moved it up a directory and got progress but a different error:
```
Comparing config_pes files...
Number of ok nodes: 139
Number of wrong nodes: 0
Number of missing nodes: 9
a%ne240np4:any:any:any
a%ne120np4:any:any:any
a%ne120np4:titan|stampede|bluewaters|edison|eos|corip1:any:any
a%ne30np4:any:any:any
a%ne30np4:titan|stampede|bluewaters:any:any
a%1.9x2.5:any:T:any
a%0.9x1.25:any:T:any
a%wr50a:any:any:any
any:redsky:any:MPASLIALB
Number of duplicate nodes: 2
any:any:any:DLND.+_CISM2P
any:any:T:DATM.+DLND.+DICE.+DOCN%DOM.+DROF
Traceback (most recent call last):
  File "./config_pes_converter.py", line 280, in <module>
    pes_compare()
  File "./config_pes_converter.py", line 277, in pes_compare
    "badgrid.xml")
TypeError: postprocess() takes exactly 5 arguments (6 given)
Exit 1

```

**Comment by rljacob** [comment]
If you want to try yourself, use the config_pes.all from the latest ACME master and the config_pesall.xml from the maint-cime5.1 branch.

**Comment by sarich** [comment]
Do you have the latest grid_xml_converter.py file in the same directory as config_pes_converter.py?

**Comment by sarich** [comment]
Since both scripts were moved, you can run them where they are by setting PYTHONPATH=/lcrc/group/earthscience/jacob/ACME5/cime/scripts/Tools

**Comment by rljacob** [comment]
I moved them both up and that worked!

**Pull request merged**
