### PR TITLE
add mpilib and compiler options to configure, update Readme.configure

### PR DESCRIPTION
**Pull request by jedwards4b**
Add mpilib and compiler command line options to configure

Test suite: hand tested on hobart building map_field tool 
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes #1981

User interface changes?: 

Code review:

### CODE REVIEW

**Comment by mnlevy1981** [comment]
A couple of comments:

1. It looks like you updated the README file before adding the `--clean` option
1. The `--clean` option doesn't remove `Depends.$COMPILER`

Rest of it looks good!

**Comment by jedwards4b** [comment]
Fixed.

**Comment by mnlevy1981** [comment]
This looks good to me!

**Comment by rljacob** [comment]
Is "Fixes #1981" supposed to be a real issue number?

**Comment by mnlevy1981** [comment]
I think he pulled that off of my username, so this is my fault. The PR addresses #1265 which I already closed

**Pull request merged**
