### PR TITLE
Config grids v2.1

### PR DESCRIPTION
**Pull request by jedwards4b**
Split the cesm/config_grids.xml file into 4 parts: config_grids.xml config_grids_mct.xml config_grids_nuopc.xml config_grids_common.xml  add a new schema definition which uses
the xml xinclude feature and add code to support reading xml over multiple files. 

Test suite: scripts_regression_tests.py 
Test baseline: 
Test namelist changes: 
Test status: bit for bit
Fixes 
User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by jgfouca** [comment]
@jedwards4b , I see this error for e3sm:

```
======================================================================
FAIL: test_m_createnewcase_alternate_drivers (__main__.J_TestCreateNewcase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts_regression_tests.py", line 736, in test_m_createnewcase_alternate_drivers
    run_cmd_assert_result(self, "./create_newcase %s"%(args), from_dir=SCRIPT_DIR)
  File "./scripts_regression_tests.py", line 69, in run_cmd_assert_result
    test_obj.assertEqual(stat, expected_stat, msg=msg)
AssertionError: 
COMMAND: ./create_newcase  --driver nuopc --case /home/jgfouca/acme/scratch/scripts_regression_test.20190221_154247/TestCreateNewcase/testcreatenewcase.nuopc --compset X --res f19_g16 --output-root /home/jgfouca/acme/scratch/scripts_regression_test.20190221_154247/TestCreateNewcase --handle-preexisting-dirs=r
FROM_DIR: /home/jgfouca/cime-yetanother/scripts
SHOULD HAVE WORKED, INSTEAD GOT STAT 1
OUTPUT: Compset longname is 2000_XATM_XLND_XICE_XOCN_XROF_XGLC_XWAV
Compset specification file is /home/jgfouca/cime-yetanother/src/drivers/nuopc/cime_config/config_compsets.xml
ERRPUT: ERROR: Makes no sense to have empty read-only file
```

**Comment by rljacob** [comment]
Whats the reason for doing this?

**Comment by jedwards4b** [comment]
nuopc driver generates these mapping files at runtime, I needed a way to specify mapping files used by mct, those used by nuopc (currently none) and those used by both in common.

**Comment by jedwards4b** [comment]
@jgfouca 
I've fixed the issue you reported above - by skipping the test - is that okay?
also
Fixes #2336

**Comment by jedwards4b** [comment]
rebased to resolve merge conflict

**Comment by jgfouca** [comment]
> I've fixed the issue you reported above - by skipping the test - is that okay?

Yes, if you think that's appropriate.

**Pull request merged**
