### PR TITLE
Update hobart to PGI 18.10

### LINKED ISSUE #2922: Update hobart PGI compiler
PGI 18.10 is available on hobart, and it would be great if `config/cesm/machines/config_machines.xml` was updated to use it (we want to remove a PGI bug workaround from MARBL, but can't do that if CESM is still using a buggy version of the compiler).

I'm happy to put together a PR if someone lets me know the target branch / branches.

### PR DESCRIPTION
**Pull request by mnlevy1981**
Test suite: Single case on hobart with PGI compiler
Test baseline: Generated from original code
Test namelist changes: None
Test status: round-off for hobart_pgi tests

Fixes #2922

User interface changes?: No

Update gh-pages html (Y/N)?: No

Code review:

### CODE REVIEW

**Comment by jedwards4b** [comment]
@mnlevy1981 I think that you need to run scripts_regression_tests and in particular make sure that multi node runs are working.

**Comment by mnlevy1981** [comment]
Multi-node runs aren't working, but they didn't work with 18.1 either -- I believe it has to do with the mvapich version? (PGI 18.1 and 18.10 both use `mvapich2-2.1-qlc` while nag uses `mvapich2-2.3rc2`). When I run a 5-node case `cesm.log` contains

```
/usr/mpi/pgi/mvapich2-2.1-qlc/bin/hydra_pmi_proxy: error while loading shared libraries: libpgmp.so: cannot open shared object file: No such file or directory
/usr/mpi/pgi/mvapich2-2.1-qlc/bin/hydra_pmi_proxy: error while loading shared libraries: libpgmp.so: cannot open shared object file: No such file or directory
/usr/mpi/pgi/mvapich2-2.1-qlc/bin/hydra_pmi_proxy: error while loading shared libraries: libpgmp.so: cannot open shared object file: No such file or directory
/usr/mpi/pgi/mvapich2-2.1-qlc/bin/hydra_pmi_proxy: error while loading shared libraries: libpgmp.so: cannot open shared object file: No such file or directory
```

I don't have any tests using 18.1 to compare against handy, but I'm 99% sure they result in the same error.

Regression tests are currently running, I'll update this PR when the script finishes. So far the only error is

```
test_CIMEXML_doctests (__main__.A_RunUnitTests) ... FAIL
```

**Comment by mnlevy1981** [comment]
`scripts_regression_tests.py` finished, though I don't really know how to interpret the results. Most tests passed, but the following did not:

```
FAIL: test_CIMEXML_doctests (__main__.A_RunUnitTests)
FAIL: test_save_timings (__main__.L_TestSaveTimings)
FAIL: test_save_timings_manual (__main__.L_TestSaveTimings)
FAIL: test_b_full (__main__.O_TestTestScheduler)
FAIL: test_c_use_existing (__main__.O_TestTestScheduler)
FAIL: test_d_retry (__main__.O_TestTestScheduler)
FAIL: test_bless_test_results (__main__.Q_TestBlessTestResults)
FAIL: test_run_restart (__main__.T_TestRunRestart)
FAIL: test_run_restart_too_many_fails (__main__.T_TestRunRestart)
FAIL: test_full_system (__main__.Z_FullSystemTest)
```

And I don't think any of the tests submitted to the queue ran?

```
FAIL DAE.f19_f19.A.hobart_pgi (phase RUN)
FAIL ERI.f09_g16.X.hobart_pgi (phase RUN)
FAIL ERIO.f09_g16.X.hobart_pgi (phase RUN)
FAIL ERP.f45_g37_rx1.A.hobart_pgi (phase RUN)
FAIL ERR.f45_g37_rx1.A.hobart_pgi (phase RUN)
FAIL ERS.ne30_g16_rx1.A.hobart_pgi.drv-y100k (phase RUN)
FAIL IRT_N2.f19_g16_rx1.A.hobart_pgi (phase RUN)
FAIL LDSTA.f45_g37_rx1.A.hobart_pgi (phase RUN)
FAIL MCC_P1.f19_g16_rx1.A.hobart_pgi (phase RUN)
FAIL NCK_Ld3.f45_g37_rx1.A.hobart_pgi (phase RUN)
FAIL PEM_P4.f19_f19.A.hobart_pgi (phase RUN)
FAIL PET_P4.f19_f19.A.hobart_pgi (phase RUN)
FAIL PRE.f19_f19.ADESP.hobart_pgi (phase RUN)
FAIL PRE.f19_f19.ADESP_TEST.hobart_pgi (phase RUN)
FAIL SEQ_Ln9.f19_g16_rx1.A.hobart_pgi (phase RUN)
FAIL SMS.T42_T42.S.hobart_pgi (phase RUN)
```

Full test results are in `/home/mlevy/codes/CESM/cesm2_1_alpha01d/cime/scripts/tests/regression_test.out`; the tests that should've gone through the queue appear to be in `/scratch/cluster/mlevy/scripts_regression_test.20181128_134217`.

**Comment by jedwards4b** [comment]
@mnlevy1981 This PR should not be merged as is.   I'll look into it when I can.

**Pull request closed without merging**
