### PR TITLE
Update case status to include jobid on batch system

### LINKED ISSUE #3255: Add jobid to more entries in CaseStatus
With longer running production jobs, where we might make multiple job submits in the the case and then manually add job dependencies via slurm/pbs, it would be nice to have a little more detail in CaseStatus entries. I would like to see the jobid printed. I see it is printed for the case.submit step, which in this case is zero as there must be an issue getting jobid on theta (I see jobid on Cori).  This would help users match up when the job was submitted, when it started to run, when it completed. Note this info can be extracted from slurm databases, but as some systems (theta) are still using PBS, it's still a nice-to-have.

example output in CaseStatus.
```
2019-09-30 17:34:38: case.run starting 
 ---------------------------------------------------
2019-09-30 17:35:24: model execution starting 
 ---------------------------------------------------
2019-10-01 00:48:26: case.submit starting 
 ---------------------------------------------------
2019-10-01 00:49:04: case.submit success case.run:0
 ---------------------------------------------------
2019-10-01 00:50:22: case.submit starting 
 ---------------------------------------------------
2019-10-01 00:50:55: case.submit success case.run:0
 ---------------------------------------------------
2019-10-01 00:59:15: case.submit starting 
 ---------------------------------------------------
2019-10-01 00:59:51: case.submit success case.run:0
 ---------------------------------------------------
2019-10-01 15:25:23: model execution success 
 ---------------------------------------------------
2019-10-01 15:25:23: case.run success 
 ---------------------------------------------------
2019-10-02 01:11:34: case.run starting 
 ---------------------------------------------------
2019-10-02 01:12:25: model execution starting 
 ---------------------------------------------------
```

### PR DESCRIPTION
**Pull request by jasonb5**
Adds jobid to CaseStatus lines when running on a batch system.

Test suite: scripts_regression_tests.py
Test baseline: n/a
Test namelist changes: n/a
Test status:

Fixes #3255 

User interface changes?: n
Update gh-pages html (Y/N)?: n
Code review: @jedwards4b @jgfouca

### CODE REVIEW

**Comment by jgfouca** [comment]
@jasonb5 , I was a bit surprised to see batch_id stuff being added to build.py. CIME only does batch submissions for case.submit, so it doesn't make sense to me to try to print batch info for build phases. Can you explain your thought process here?

**Comment by jedwards4b** [comment]
@jasonb5 why not just add code to batch_jobid to update the CaseStatus file any time a new jobid is assigned - that would seem to accomplish the same thing with a small change in a single file.

**Comment by jasonb5** [comment]
@jgfouca The original thought was to keep the CaseStatus uniform; if anything was executed in a batch or interactive job then it's jobid would be recorded. I can see why this portion may not be useful since `case.build` will have it's entries created sequentially so trying to determining the build time is fairly straight forward. I can remove this portion of the PR.

@jedwards4b If I just modified batch_jobid I wouldn't be able to add the jobid to the starting and success/error phase entries. I wanted to have it on both entries to handle a case where a user may call `case.submit` multiple times and it might be difficult to match jobid to their associated phases and child phases e.g. `case.run`, `model execution`.

**Comment by jgfouca** [comment]
@jasonb5 , thanks, that sounds good.

**Review by jedwards4b — APPROVED** [review]

**Review by jgfouca — APPROVED** [review]

**Pull request merged**
