### PR TITLE
update to cime0_3_20 from CESM svn

### PR DESCRIPTION
**Pull request by jedwards4b**
Have configure look for Version in ChangeLog rather than Tag name
The cime ChangeLog uses header "Version:" to name the tag rather than
"Tag name:". So switch to it, so configure will work correctly.

 Update test scripts to output full case name when test status is
TFAIL or RUN, updated GPTL to v5.4.4

### CODE REVIEW

**Comment by rljacob** [comment]
Are you testing making a PR or would you like a review?

**Comment by jedwards4b** [comment]
Mostly I was testing, but I have to stop pushing and start doing the pull
requests at some point - how do you want to handle it?

On Mon, Apr 13, 2015 at 7:09 PM, Robert Jacob <notifications@github.com>
wrote:

> Are you testing making a PR or would you like a review?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ESMCI/cime/pull/7#issuecomment-92550297>.
>



-- 
Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by rljacob** [comment]
It would be good practice to have at least one other person look at these.  Could be whoever has time.

I'd suggest changing the title to be more specific (upgrade to cime 0.3.20) and then use the description at the top of this page for all the detail you would have put in a ChangeLog entry.  When its merged to master, the commit message could just be copy-and-paste from the description here.

**Comment by jedwards4b** [comment]
All changes have been reviewed on our end, any further review should come from your side.

**Comment by rljacob** [comment]
Ideally, the description should try to summarize the 34 commits in this PR.   But this looks good.

**Comment by rljacob** [comment]
Please go ahead and merge and close this.

**Comment by jedwards4b** [comment]
Done

**Pull request merged**
