### PR TITLE
Config tests distribution

### LINKED ISSUE #651: Move component-specific tests out of CIME
LII and SSP should not be under CIME

### PR DESCRIPTION
**Pull request by jedwards4b**
Allow for distributed config_tests.xml file and move LII test out of cime. 
Also an unrelated minor bug fix in case.py

Test suite: scripts_regression_tests. LII using cesm 
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes #651 

User interface changes?: 

Code review:

### CODE REVIEW

**Comment by billsacks** [comment]
Note that I also removed the ssp test. This will also be moved to CLM.

**Comment by jedwards4b** [comment]
I have added code to abort if the more than one copy of a test is found.   Issue one is taken care of by xml since the object is built by appending all files and only one test with a given name is allowed in the file.

**Comment by billsacks** [comment]
Thanks, @jedwards4b - I like this fix.

> Issue one is taken care of by xml since the object is built by appending all files and only one test with a given name is allowed in the file.

It lets me define the LII test both in cime's config_tests.xml and in CLM's config_tests.xml. I'm not sure which one it's taking in this case. If you know an easy fix for this, that would add a bit more robustness, but I see that as icing on the cake - not necessary.

One final question: in your last commit, you added:

```python
    print "TESTNAME %s "%testname
```

Did you mean to leave that in the code?

**Comment by jedwards4b** [comment]
I removed the debug print statement, I am not able to reproduce the other problem - if I define 
LII in both places I get:
```
Finished XML for test LII.f19_f19_mg17.ITEST.cheyenne_intel in 0.073884 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /glade/scratch/jedwards/LII.f19_f19_mg17.ITEST.cheyenne_intel.20170613_153215_aemnew
    Errors were:
        Test 'LII.f19_f19_mg17.ITEST.cheyenne_intel' failed in phase 'XML' with exception 'ERROR: Incorrect number of matches, 2, for nodename 'test' and attrs '{'NAME': 'LII'}' in file '/glade/p/work/jedwards/sandboxes/cesm2_0_alpha/cime/config/config_tests.xml''
          File "/glade/p/work/jedwards/sandboxes/cesm2_0_alpha/cime/scripts/Tools/../../scripts/lib/CIME/test_scheduler.py", line 582, in _run_catch_exceptions
            return run(test)
          File "/glade/p/work/jedwards/sandboxes/cesm2_0_alpha/cime/scripts/Tools/../../scripts/lib/CIME/test_scheduler.py", line 470, in _xml_phase
            testnode = config_test.get_test_node(test_case)
          File "/glade/p/work/jedwards/sandboxes/cesm2_0_alpha/cime/scripts/Tools/../../scripts/lib/CIME/XML/tests.py", line 32, in get_test_node
            node = self.get_node("test",{"NAME":testname})
          File "/glade/p/work/jedwards/sandboxes/cesm2_0_alpha/cime/scripts/Tools/../../scripts/lib/CIME/XML/generic_xml.py", line 95, in get_node
            expect(len(nodes) == 1, "Incorrect number of matches, {:d}, for nodename '{}' and attrs '{}' in file '{}'".format(len(nodes), nodename, attributes, self.filename))
          File "/glade/p/work/jedwards/sandboxes/cesm2_0_alpha/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 29, in expect
            raise exc_type("{} {}".format(error_prefix, error_msg))

```

**Comment by billsacks** [comment]
Thanks, @jedwards4b . I realized that I made a mistake when I was testing the duplicate definition in xml. You're right that that gets caught - sorry about that.

This looks good to me now, so I'll merge it.

**Pull request merged**
