### PR TITLE
Add ability to customize CaseStatus success message for a phase.

### LINKED ISSUE #2108: Consider upgrading status of the job ID
When submitted jobs to a batch system, the job ID is a critical integer and could be made more available.  One place it seems it could easily be added is in the CaseStatus.

```
2017-11-29 14:01:27: case.submit starting 
 ---------------------------------------------------
2017-11-29 14:02:15: case.submit success  JOB ID is 42
 ---------------------------------------------------
2017-11-29 15:37:35: model execution success 
```

Jim F. suggested a query that doesn't do what I would expect: 
```
cori08% pwd
/global/cscratch1/sd/ndk/ACME_simulations/2017-master-nov28.hmod526t03.mnov28.st04.atune.long.ne120np4_oRRS18to6v3_ICG.cori-knl/case_scripts
cori08% xmlquery JOB_IDS
        JOB_IDS: case.run:8787607
cori08% 
```

The job ID returned is the ID for the job that is currently submitted, but I'd like to know the job ID of the previous job that just failed (for example).

I might even argue to put the job ID with the date/time stamp for the log files.  `cpl.log.171129-022802` could be `cpl.log.171129-022802.8787607`.

Also, after the job is complete, the slurm system (at least) has a nice way of getting some info from the job:
```
cori08% sacct -j 8700613 -X --format=JobID,JobName,NNodes,Elapsed,Account,QOS,State
       JobID    JobName   NNodes    Elapsed    Account        QOS      State 
------------ ---------- -------- ---------- ---------- ---------- ---------- 
8700613      hmod600t0+      600   01:23:35       acme normal_kn+     FAILED 

or:

cori08% sacct -j 8700613 -a -o JobID%-20,JobName,State,ExitCode,DerivedExitCode,Elapsed,NNodes,NTasks,MaxRSS
               JobID    JobName      State ExitCode DerivedExitCode    Elapsed   NNodes   NTasks     MaxRSS 
-------------------- ---------- ---------- -------- --------------- ---------- -------- -------- ---------- 
8700613              hmod600t0+     FAILED      1:0             0:0   01:23:35      600                     
8700613.batch             batch     FAILED      1:0                   01:23:35        1        1     43568K 
8700613.extern           extern  COMPLETED      0:0                   01:25:03      600      600          0 
8700613.0              acme.exe CANCELLED+      0:9                   00:25:13      600    38400    548784K 

```

This will tell you exactly how much time the entire job used and if it failed.  The memory reported in the second command is only moderately useful, but can point to a job that used too much memory.

### PR DESCRIPTION
**Pull request by jgfouca**
Add ability to customize CaseStatus success message for a phase.

Test suite: code_checker, by-hand
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes #2108 

User interface changes?: jobid now added to CaseStatus case_submit entry

Update gh-pages html (Y/N)?: N

Code review: @jedwards4b

### CODE REVIEW

**Comment by jedwards4b** [comment]
Also I'm not sure that this will work on anything other than slurm?

**Comment by jgfouca** [comment]
@jedwards4b , I wasn't sure we wanted to change the log files name. That seems like a big change that could confuse a lot of people. I was hoping to just do the minimum to help Noel.

Why would this only work on slurm?

**Comment by jedwards4b** [comment]
I think that slurm is the only system that gives you that information (jobid, wallclocktime) on job exit. 
My proposal is that we have a log file format field that users (or config_machines.xml) can modify to add jobid, but that we keep the current format as default.

**Comment by jgfouca** [comment]
@jedwards4b , I think we have jobid retrieval working on all the major batch systems. I know it also works on PBS.

**Comment by jedwards4b** [comment]
I've added issue #2116 to address the log file name format.

**Pull request merged**
