### PR TITLE
fix wget option for directories

### LINKED ISSUE #2699: Issue downloading data (wildcards not supported in HTTP)
I was wanting to have a case download all of the data it needs. First create an empty tmp inputdata directory, set the DIN env vars.  However, I got error below which seems like a problem with wget and wildcards?

```
        Refcase not found in /global/cscratch1/sd/ndk/inputdata/e3sm_init/20171228.beta3rc13_1850.ne30_oECv3_ICG.edison/0331-01-01, will attempt to download from inputdata
          Model refcase missing file refdir = '/global/cscratch1/sd/ndk/inputdata/e3sm_init/20171228.beta3rc13_1850.ne30_oECv3_ICG.edison/0331-01-01/'
        wget failed with output:  and errput Warning: wildcards not supported in HTTP.
        --2018-06-29 14:11:00--  https://web.lcrc.anl.gov/public/e3sm/inputdata/e3sm_init/20171228.beta3rc13_1850.ne30_oECv3_ICG.edison/0331-01-01/*
        Resolving web.lcrc.anl.gov (web.lcrc.anl.gov)... 140.221.74.23
        Connecting to web.lcrc.anl.gov (web.lcrc.anl.gov)|140.221.74.23|:443... connected.
        HTTP request sent, awaiting response... 404 Not Found
        2018-06-29 14:11:00 ERROR 404: Not Found.
```

The test I was using: `SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.cori-knl_intel.allactive-v1cmip6`

### PR DESCRIPTION
**Pull request by jedwards4b**
wget should use -r instead of wildcard

Test suite: by hand  
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes #2699 

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by rljacob** [comment]
This turns out to be not quite right.  See further discussion in #2699

**Comment by jedwards4b** [comment]
@rljacob Fixed, please try it again.

**Comment by ndkeen** [comment]
I tried that and I do see different behavior. Things are still messy and I'm not sure if I now see a different problem or if this can still be improved.

One thing I see that the downloads are still grabbing files like index.html, but I would assume that's OK if -r is what is being used.

Here is the contents of the dir after download attempts:
```
e3sm_init/20171228.beta3rc13_1850.ne30_oECv3_ICG.edison/0331-01-01:
total 11023664
-rw-rw-r-- 1 ndk ndk        245 Nov 20  2004 unknown.gif
-rw-rw-r-- 1 ndk ndk        229 Nov 20  2004 text.gif
-rw-rw-r-- 1 ndk ndk        225 Nov 20  2004 folder.gif
-rw-rw-r-- 1 ndk ndk        148 Nov 20  2004 blank.gif
-rw-rw-r-- 1 ndk ndk        216 Nov 20  2004 back.gif
-rw-rw-r-- 1 ndk ndk          0 Nov 18  2014 test.ocn
-rw-rw-r-- 1 ndk ndk        234 Mar 22 13:50 HOWTO
-rw-rw-r-- 1 ndk ndk 1238731020 Apr  9 21:35 20171228.beta3rc13_1850.ne30_oECv3_ICG.edison.cam.i.0331-01-01-00000.nc
-rw-rw-r-- 1 ndk ndk 6872280072 Apr  9 21:39 20171228.beta3rc13_1850.ne30_oECv3_ICG.edison.cam.r.0331-01-01-00000.nc
-rw-rw-r-- 1 ndk ndk   68546256 Apr  9 21:39 20171228.beta3rc13_1850.ne30_oECv3_ICG.edison.cam.rs.0331-01-01-00000.nc
-rw-rw-r-- 1 ndk ndk     419152 Apr  9 21:40 20171228.beta3rc13_1850.ne30_oECv3_ICG.edison.clm2.rh0.0331-01-01-00000.nc
-rw-rw-r-- 1 ndk ndk  889192576 Apr  9 21:40 20171228.beta3rc13_1850.ne30_oECv3_ICG.edison.clm2.r.0331-01-01-00000.nc
-rw-rw-r-- 1 ndk ndk  394241024 Apr  9 21:40 20171228.beta3rc13_1850.ne30_oECv3_ICG.edison.cpl.r.0331-01-01-00000.nc
-rw-rw-r-- 1 ndk ndk     115968 Apr  9 21:40 20171228.beta3rc13_1850.ne30_oECv3_ICG.edison.mosart.rh0.0331-01-01-00000.nc
-rw-rw-r-- 1 ndk ndk   39845892 Apr  9 21:40 20171228.beta3rc13_1850.ne30_oECv3_ICG.edison.mosart.r.0331-01-01-00000.nc
-rw-rw-r-- 1 ndk ndk         76 Apr  9 21:41 rpointer.rof
-rw-rw-r-- 1 ndk ndk         21 Apr  9 21:41 rpointer.ocn
-rw-rw-r-- 1 ndk ndk         76 Apr  9 21:41 rpointer.lnd
-rw-rw-r-- 1 ndk ndk         21 Apr  9 21:41 rpointer.ice
-rw-rw-r-- 1 ndk ndk         73 Apr  9 21:41 rpointer.drv
-rw-rw-r-- 1 ndk ndk         74 Apr  9 21:41 rpointer.atm
-rw-rw-r-- 1 ndk ndk  540343228 Apr 18 13:57 mpascice.rst.0331-01-01_00000.nc
-rw-rw-r-- 1 ndk ndk 1244361488 Apr 18 13:58 mpaso.rst.0331-01-01_00000.nc
-rw-rw-r-- 1 ndk ndk       1274 Apr 18 14:44 checksum
drwxrwxr-x 3 ndk ndk       4096 Jul  6 10:32 ../
-rw-rw-r-- 1 ndk ndk       3826 Jul  6 10:36 'index.html?C=N;O=A'
-rw-rw-r-- 1 ndk ndk       3826 Jul  6 10:36 'index.html?C=S;O=D'
-rw-rw-r-- 1 ndk ndk       3826 Jul  6 10:36 'index.html?C=M;O=D'
-rw-rw-r-- 1 ndk ndk       3826 Jul  6 10:36 'index.html?C=D;O=D'
drwxrwxr-x 2 ndk ndk       4096 Jul  6 10:36 ./
-rw-rw-r-- 1 ndk ndk       2127 Jul  6 10:37 'index.html?C=N;O=D'
-rw-rw-r-- 1 ndk ndk       2127 Jul  6 10:37 'index.html?C=S;O=A'
-rw-rw-r-- 1 ndk ndk       2127 Jul  6 10:37 'index.html?C=M;O=A'
-rw-rw-r-- 1 ndk ndk       2127 Jul  6 10:37 'index.html?C=D;O=A'
-rw-rw-r-- 1 ndk ndk       1950 Jul  6 10:37 index.html
```

**Comment by jedwards4b** [comment]
Yes it's just downloading the entire directory - I have no control over what you choose to put in it.

**Comment by rljacob** [comment]
The .gif, HOWTO and index.html files are NOT in the directory.  They are in the directory above the target directory.

**Comment by rljacob** [comment]
The only files that should be downloaded are the ones you can see here:  https://web.lcrc.anl.gov/public/e3sm/inputdata/e3sm_init/20171228.beta3rc13_1850.ne30_oECv3_ICG.edison/0331-01-01/

**Comment by jedwards4b** [comment]
Seems to be a feature of the wget http interface - I haven't found a way to get rid of them.

**Comment by rljacob** [comment]
This thread suggests its an http limitation:  https://stackoverflow.com/questions/4496182/getting-directory-listing-over-http

**Comment by jedwards4b** [comment]
Given that information - do we accept the PR?

**Comment by rljacob** [comment]
Yes.  This is still better then the current behavior on master.

**Pull request merged**
