### PR TITLE
Ensure module setup is sourced before list

### LINKED ISSUE #372: module list for tcsh and csh users
The module list command in env_mach_specific.py does not work for tcsh and csh users
I've commented out the call to this code in case_setup.py until the problem can be resolved.
Code was added in PR 337

### PR DESCRIPTION
**Pull request by jgfouca**
Test suite: None
Test baseline: 
Test namelist changes: 
Test status: [bit for bit, roundoff, climate changing]

Fixes #372 

User interface changes?: No

Code review: @rljacob @jedwards4b

### CODE REVIEW

**Comment by jgfouca** [comment]
@rljacob , you're the only one I know who uses a csh-based login shell. Please see if this branch fixes the issue. @jedwards4b I want to be sure you're OK with this change.

**Comment by jedwards4b** [comment]
You still need to uncomment the code in case_setup.py but I did that and confirmed that this is working (using a tcsh shell where it did not work before).

**Comment by rljacob** [comment]
Works for me too after uncommenting that line.  I get a complete software_environment.txt file and no error message.

**Comment by jgfouca** [comment]
OK, who wants to click the green button?

**Comment by rljacob** [comment]
I'll merge it.

**Comment by rljacob** [comment]
Tested on edison by a csh user (rjacob).
create_newcase -compset X -res f19_g16
./case_setup

software_environment.txt fill was successfully created.

**Pull request merged**
