### PR TITLE
Copy user_nl_foo from the case directory to the multi-instance version

### PR DESCRIPTION
**Pull request by billsacks**
Changes how user_nl files are handled in multi-instance cases and tests

(1) When case.setup is run, then for any component foo, if there is a
    file user_nl_foo in the case directory, but no file
    user_nl_foo_NNNN, where NNNN <= NINST_FOO, then user_nl_foo is
    copied to user_nl_foo_NNNN. This means that anything added to
    user_nl_foo, either by user_mods / testmods or manually by the user,
    is copied to any multi-instance user_nl_foo file, if that given
    multi-instance user_nl_foo file doesn't already exist.

(2) Remove handling of multi-instance in apply_user_mods: this is now
    handled by (1).

(3) Get rid of user_mods / testmods handling in case_setup, just keeping
    it in create_newcase. It was originally needed in case_setup to
    handle multi-instance cases, but with the reworked handling of
    multi-instance user_nl files, this is no longer needed.

(4) Remove code that checks for already-applied user_nl contents: this
    was needed because user_mods / testmods were applied repeatedly by
    case.setup; since they are now only applied by create_newcase, this
    is no longer needed.

Test suite: scripts_regression_tests.py on yellowstone
   All pass except test_create_test_rebless_namelist
      (which is also failing on master)
   Also many other manual tests - see below
Test baseline: N/A
Test namelist changes: none
Test status: bit for bit

Other tests:

For user cases (not tests):

- for ninst = 1, make sure user_nl_ files get copied from the source
  tree

- for ninst = 2, when there is no user_nl_foo in the case dir, make sure
  it gets copied from the source tree

- for ninst = 2, if there is a user_nl_foo in the case dir and also a
  user_nl_foo_0002, user_nl_foo_0002 should be maintained

- for ninst = 2, if there is a user_nl_foo in the case dir but no
  user_nl_foo_0002, user_nl_foo should be copied to user_nl_foo_0002.

- and some other manipulations of NINST and rerunning of case.setup

For tests:

- Make sure user_nl files are set up correctly for an _N2 test with a
  testmods dir

- Make sure user_nl files are set up correctly for a NCK test.

- Checked CLM_BLDNML_OPTS in
  ERP_P60x2_Lm36.f10_f10.ICRUCLM50BGCCROP.yellowstone_intel.clm-clm50cropIrrigMonth_interp
  - ensured the append wasn't repeatedly applied

- Ran NCK_D.f10_f10.ICLM45BGC.yellowstone_intel.clm-default from clm4_5_12_r198

Fixes: #734

User interface changes?: YES: For multi-instance cases, when case.setup
is run, then for any component foo, if there is a file user_nl_foo in
the case directory, but no file user_nl_foo_NNNN, where NNNN <=
NINST_FOO, then user_nl_foo is copied to user_nl_foo_NNNN. This means
that anything added to user_nl_foo, either by user_mods / testmods or
manually by the user, is copied to any multi-instance user_nl_foo file,
if that given multi-instance user_nl_foo file doesn't already exist.

Code review: @jedwards4b

### CODE REVIEW

**Comment by billsacks** [comment]
This was in response to conversation on #734 

Mostly a note to myself: testing to do on those diffs: 

For user cases (not tests):

1. for ninst = 1, make sure user_nl_ files get copied from the source tree

2. for ninst = 2, when there is no user_nl_foo in the case dir, make sure it gets copied from the source tree

3. for ninst = 2, if there is a user_nl_foo in the case dir and also a user_nl_foo_0002, user_nl_foo_0002 should be maintained

4. for ninst = 2, if there is a user_nl_foo in the case dir but no user_nl_foo_0002, user_nl_foo should be copied to user_nl_foo_0002. 

And for tests:

5. Make sure user_nl files are set up correctly for an _N2 test with a testmods dir

6. Make sure user_nl files are set up correctly for a NCK test.

**Comment by billsacks** [comment]
@jedwards4b - Do you mean taking over #727 ? My inclination would be for you to back out your most recent commit there (de38a267514ba6d5a386e686cf6ffe75a03c1515), then we can review that PR without it, and bring it to master if it looks good. Then I can take over the removal of applying user_mods during case.setup, which I'll fold in to this PR.

**Comment by jedwards4b** [comment]
okay, last commit reverted

**Comment by jedwards4b** [comment]
Is this ready?

**Comment by billsacks** [comment]
No, I hope to work on it today.

**Comment by billsacks** [comment]
@jedwards4b - this is ready for review. scripts_regression_tests are still ongoing; they're currently on `__main__.L_TestSaveTimings`. I'll try to check them before yellowstone goes down tomorrow morning.

I have put detailed notes in the edited first comment of this PR. Please copy this into the log message for the merge.

**Comment by billsacks** [comment]
scripts_regression_tests passed except for test_create_test_rebless_namelist, which is also failing on master according to CDash.

**Pull request merged**
