### PR TITLE
Adding support for Anvil

### PR DESCRIPTION
**Pull request by jayeshkrishna**
This commit adds support for anvil (the new cluster at ANL)

Test suite: 
Test baseline: 
Test namelist changes: 
Test status:

User interface changes?: None

Code review: @rljacob 

Adding support for the new acme cluster, anvil. This
machine uses the same login node as blues and jobs are
submitted to the "acme" queue.

To use the anvil cluster, create your case on the
blues login node by specifying the "-mach" explicitly
as "anvil"

### CODE REVIEW

**Comment by rljacob** [comment]
This should also be added to the maint-cime5.1 branch.

**Comment by jayeshkrishna** [comment]
Is it ok that I branched off master? Did I have to branch off where maint-cime5.1 branched off?

**Comment by rljacob** [comment]
I think you have to branch at maint-cime5.1.  @douglasjacobsen ?

**Comment by douglasjacobsen** [comment]
It's safest to branch from the base of maint-cime5.1 or earlier. Just to ensure it's mergable into both cime5.1 and master.

Since this is a single commit, it should be easy to rebase / cherry-pick it though.

**Comment by jayeshkrishna** [comment]
@jgfouca / @douglasjacobsen : This is what I did to rebase my branch so that it is mergeable to both maint-cime5.1 and master. Please let me know if it is ok.
```
> git checkout jayeshkrishna/machinefiles/add_Anvil
> git merge-base master maint-cime5.1
81851c4a2bbde9bf46de8d8158de97845f1f6e59
> git rebase --onto 81851c4a2bbde9bf46de8d8158de97845f1f6e59 f63e863
```
f63e863 was the old parent commit for the only commit on the branch.

**Comment by jgfouca** [comment]
Maybe @douglasjacobsen can correct me here, but I think you just need to do:
```
> git checkout jayeshkrishna/machinefiles/add_Anvil
> git rebase 81851c4a2bbde9bf46de8d8158de97845f1f6e59
```

**Comment by jayeshkrishna** [comment]
On my branch 81851c4a2bbde9bf46de8d8158de97845f1f6e59 is showing up (as expected) as the parent commit.

**Comment by jayeshkrishna** [comment]
I will be updating this branch to add support for intel and pgi & change name to "anvil" (all lowercase). @rljacob : please wait for my updates before merging this branch.

**Comment by jayeshkrishna** [comment]
@rljacob : I have now added support for intel+gnu+pgi and mvapich+openmpi . This should be ready to merge to master.
I will create a separate PR to merge this branch to cime-maint5.1

**Comment by jayeshkrishna** [comment]
Tested (successfully) all the combinations (intel+gnu+pgi & mvapich+openmpi) with an X case.

**Comment by jayeshkrishna** [comment]
Please see PR #718 that merged this branch to the cime maint branch

**Pull request merged**
