### PR TITLE
Update testing

### PR DESCRIPTION
**Pull request by jasonb5**
- Adds a developer/testing Dockerfile
- Adds E3SM system testing
- Adds a few fixes to get testing to work in this environment
- Updates GitHub actions to use new Dockerfile

Test suite: script_regression_tests
Test baseline: n/a
Test namelist changes: n/a
Test status: n/a

Fixes n/a
User interface changes?: n
Update gh-pages html (Y/N)?: n

### CODE REVIEW

**Comment by jedwards4b** [comment]
I have been working on something similar.

I started by creating a new repo that just builds and uploads the images from Dockerfiles in https://github.com/ESMCI/TestingTools  I've been testing these in the ParallelIO repository using a PR https://github.com/NCAR/ParallelIO/pull/1908  

My plan is once I get it working in the ParallelIO repo to my satisfaction I would create a new Docker layer there and use that to test ESMF (not used by e3sm) and from there cime, cmeps and cdeps.   

I already see a few things in your work that I would like to adopt, but I'll have to study it a bit to figure out
how our efforts can coexist.

**Review by jgfouca — APPROVED** [review]
Looks great!

**Comment by jgfouca** [comment]
@jasonb5 , @jedwards4b , can this be merged?

**Comment by jedwards4b** [comment]
I think that our plan is to bring in #4162 first and then this one - @fischer-ncar?

**Comment by fischer-ncar** [comment]
@jedwards4b I think either order would be fine for me.

**Comment by rljacob** [comment]
Notes from telecon:  workflow will first see if container files have changed and rebuild container and push to containerhub if changed.   Will then run python tests and CESM tests with NUOPC driver.

**Comment by jasonb5** [comment]
E3SM tests are failing due to the `genf90` short type issue from #4221.

**Comment by jedwards4b** [comment]
@jasonb5 lets plan to bring this in next week?

**Comment by jasonb5** [comment]
@jedwards4b Sounds good to me. I'll update this branch to ensure the genf90 update fixes the failing test and we should be good after that.

**Review by jedwards4b — APPROVED** [review]

**Pull request merged**
