### PR TITLE
add mvsource script

### LINKED ISSUE #3542: Keeping an old case running when a username changes
One of our clusters recently updated its accounting and a bunch of usernames changed.

As you might expect, this plays havoc with cases already created in a user's $HOME directory with the old name.

There should be a way to fix this without re-creating the case form scratch.

Here's what we tried so far:
use xmlchange to update: CASEROOT, CIMEROOT, SRCROOT, MACHDIR
do ./case.setup --reset

When trying to do /.case.build, there's an error because the softlinks in $CASEDIR/Tools are still pointing to the old pathname (with the old username) and the Makefile can't be found.   Shouldn't case.setup --rest remake those links?   Is that the last step?

### PR DESCRIPTION
**Pull request by jedwards4b**
Add script cime/scripts/Tools/movesrc which accepts two arguments caseroot and cimeroot
and updates a case directory with these paths.  If either the case directory or the code source is moved use this script to correct the case and keep it functional. 

Test suite: 
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes #3542 

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by jedwards4b** [comment]
I'll work on a test, but wanted to put this up for review and comments.

**Comment by billsacks** [comment]
At a glance, this looks like useful functionality - thanks for working on it. Are you planning to change the script to look more like other cime tools, both from a coding perspective and from a user interface perspective - e.g., use of argparse, logging, etc.?

**Comment by jedwards4b** [comment]
@billsacks I started with the assumption that this would need to work without access to the cime python library, but then I did back off that assumption a little but I don't think it can use the argparse stuff because you can't access it until you have the cimeroot.    @jgfouca what do you think?

**Comment by billsacks** [comment]
You could use python's argparse library for argument parsing without having access to cimeroot. But I see your point about not being able to access some of the other cime stuff until you know where you're getting it from.

**Comment by jedwards4b** [comment]
@rljacob you were the one to request this feature - do you want to review?

**Pull request merged**
