### PR TITLE
Centos7 linux

### PR DESCRIPTION
**Pull request by jedwards4b**
A port to a generic Linux workstation.

Test suite: scripts_regression_tests.py
Test baseline: 
Test namelist changes: 
Test status: bit for bit
Fixes

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by billsacks** [comment]
At a glance, I'm happy with this. But I have no way of testing it. Should it be reviewed by someone with a linux machine who can test it?

**Comment by jedwards4b** [comment]
I don't think there is any point unless you want someone to start from an OS install and do the whole thing.

**Comment by billsacks** [comment]
Have you tested this yourself? I'd be a little wary of adding something like this if it hasn't undergone any testing, since it might give the false impression that we expect it to wor.

**Comment by billsacks** [comment]
Though I'm willing to accept it if we at least add a comment saying that this hasn't been tested at all.

**Comment by jedwards4b** [comment]
Yes - I have tested as documented.

**Comment by billsacks** [comment]
The documentation just says you ran scripts_regression_tests - but as far as I know that wouldn't actually test this new stuff at all. What I meant was, have you actually tested using this port in any way?

**Comment by jedwards4b** [comment]
I ran scripts_regression_tests on the centos7-linux system.

**Comment by billsacks** [comment]
Ah, that makes me feel much better – I couldn't tell that from your initial PR comments. I'll merge this, then.

**Pull request merged**
