### PR TITLE
Make Flgl_qice attname consistent with name

### LINKED ISSUE #1660: Flgl_qice name/attname consistency
In seq_flds_mod, there seems to be an inconsistency in the name and attname for this variable,

     name = 'Flgl_qice'
     longname = 'New glacier ice flux'
     stdname  = 'ice_flux_out_of_glacier'
     units    = 'kg m-2 s-1'
     attname  = 'Fgll_qice'

should it be Flgl or Fgll.  Some new code I'm working on picked up on this and barfed out an error.  I believe name and attname should always be the same in CESM for all coupling fields.

### PR DESCRIPTION
**Pull request by billsacks**
Test suite: ./create_test cime_developer on yellowstone
Test baseline: N/A
Test namelist changes: none
Test status: bit for bit

Fixes #1660 

User interface changes?: none

Code review:

### CODE REVIEW

**Comment by jedwards4b** [comment]
@apcraig as the assignee you are responsible for merging the PR.  If you would rather not do that you can reassign.

**Comment by apcraig** [comment]
I have not done a PR on escmi and don't know the process.  I'll merge it if you want.  It's it just "click" the "Merge pull request" button?  If it's more than that, maybe somebody else can take it.

**Comment by billsacks** [comment]
Thanks, @apcraig and @jedwards4b 

@apcraig - for future reference: it's just a matter of clicking the Merge pull request button, then copying and pasting the original PR comments into the message box, so that they get incorporated in the git log history.

**Comment by gold2718** [comment]
After the copy, you should replace references to ESMCI issues (e.g., Fixes #1660) with something explicit (e.g., Fixes ESMCI/CIME issue 1660) so that the git log, which ends up in other repos (e.g., ACME, CESM-Development) don't refer to the wrong issue number.

**Pull request merged**
