### PR TITLE
Add walltimemax to skybridge and redsky

### PR DESCRIPTION
**Pull request by jgfouca**
Make sure num_nodes is always int.

Test suite: 
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes [CIME Github issue #]

User interface changes?: none

Code review: jedwards

### CODE REVIEW

**Comment by rljacob** [comment]
Do we need to check this for all the ACME machines?

**Comment by jgfouca** [comment]
@rljacob yes, i think so

**Comment by rljacob** [comment]
Ok.  Also can this same branch be pushed to the maint-cime5.1 branch?

**Comment by jedwards4b** [comment]
No need - this problem was only introduced after maint-cime5.1

**Pull request merged**
