### PR TITLE
Support for SCM functionality for multiple columns

### PR DESCRIPTION
**Pull request by bogensch**
PR changes the name of the ambiguously named flag “iop_mode” with “scm_multcols”, which turns on single column model (SCM) functionality but for multiple columns.  Specifically, its purpose is to take the column on the globe intended to be run in SCM mode, but propagates that point (i.e. meaning surface type and location etc.) to multiple columns, as defined by the user.  All columns are then forced identically according to the Intensive Observation Period (IOP) file, which is typically required to run in SCM mode.  This PR also adds the flexibility for the user to determine the number of columns in the x & y direction (PTS_NX, PTX_NY and scm_nx, scm_ny).

Background/Motivation for changes: This PR is intended to support running a doubly periodic cloud resolving model with the planar version of HOMME (specifically, the doubly periodic version of SCREAM) but could be potentially useful for other applications.

Test suite: scripts_regression_tests on cori
Test baseline: 
Test namelist changes: 
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by billsacks** [comment]
At a glance, I'm thinking this should wait until we have completed the cime split (separating out the Fortran code so CESM is using a different version from E3SM); otherwise it probably needs a review from the CESM side as well as the E3SM side.

**Comment by mvertens** [comment]
I agree with the point that @billsacks raises. I think this should wait until the CIME source code split is finalized. We are aiming for the end of March for this on the CESM end.

**Comment by bogensch** [comment]
Thanks @billsacks and @mvertens.  Understood and sounds good.

**Comment by jgfouca** [comment]
@bogensch , RobJ has completed the CIME split. I recommend you move this work over the E3SM master. I can help with the details if you need.

**Comment by rljacob** [comment]
This PR makes changes to src/share which I haven't moved yet.  But it should be redone in the E3SM repo anyway.

**Comment by bogensch** [comment]
Thanks @rljacob !

**Pull request closed without merging**
