### PR TITLE
Mvertens/split drv config component

### PR DESCRIPTION
**Pull request by mvertens**
Separated out acme/cesm model specific config_component.xml

All compset dependent xml variables in driver_cpl/cime_config/config_component.xml have no been separated into config_component_cesm.xml and config_component_acme.xml in driver_cpl/cime_config. This will provide the ability for acme and cesm to modify these variables independently but still have all common non-compset dependent variables in one xml file.

Test suite: scripts_regression_tests
Test baseline: NA
Test namelist changes: NA
Test status: bit for bit

Fixes: None

User interface changes?: None

Code review:

### CODE REVIEW

**Comment by rljacob** [comment]
Can other entries from config_component.xml be moved?   ACME wants DRV_THREADING and SAVE_TIMING to be default TRUE, possibly BFBFLAG as well.

**Comment by mvertens** [comment]
Sure. I had a very simple rule when I implemented this - but I can easily
add the above variables before the PR is accepted. Anything else?

**Comment by mvertens** [comment]
I believe that setting BFBFLAG to TRUE incurs a performance penalty.

**Comment by rljacob** [comment]
That was the thinking about BFBFLAG but hasn't been verified at least in testing with ACME cases.

**Comment by rljacob** [comment]
That's all the variables for now.

**Pull request merged**
