### PR TITLE
additional fields needed for environment_variables

### PR DESCRIPTION
**Pull request by jedwards4b**
additional environment attributes needed 
Test suite: hand tested
Test baseline: 
Test namelist changes: 
Test status: bit for bit
Fixes cdash on blues and melvin

User interface changes?: 

Code review:

### CODE REVIEW

**Comment by rljacob** [comment]
What issue does this address?

**Comment by jedwards4b** [comment]
Failing cdash tests on master - do you want me to open an issue?

**Comment by rljacob** [comment]
Not if its a hotfix.

**Comment by jgfouca** [comment]
Looks like this fixes things on melvin.

**Comment by dqwu** [comment]
@jedwards4b @jgfouca 
I tested latest master (with this PR merged) on anlworkstation, phase XML still fails:
env_mach_specific.xml:35: element env: Schemas validity error : Element 'env', attribute 'mpilib': The attribute 'mpilib' is not allowed.
The xml file (around line 35):
```
  <environment_variables mpilib="!mpi-serial">
    <env mpilib="!mpi-serial" name="PNETCDFROOT">$SHELL{dirname $(dirname $(which pnetcdf_version))}</env>
  </environment_variables>
```

**Comment by dqwu** [comment]
@jedwards4b 
This is from cime/config/acme/machines/config_machines.xml, line 687 to 689
Could you update config_machines.xml for anlworkstation? Thanks.

**Comment by jgfouca** [comment]
@dqwu this is our job, not @jedwards4b , since it's an ACME XML file. I'll make a quick fix.

**Comment by jgfouca** [comment]
@dqwu OK, the fix is on master.

**Comment by rljacob** [comment]
@dqwu you can also make PR's to CIME if you have a change to make (and know how to make it).

**Pull request merged**
