### PR TITLE
Update user defined

### PR DESCRIPTION
**Pull request by jedwards4b**
Updating the user_defined template, this also lead to a number of pylint issues due to using a newer version of the pylint code.   Retested with pylint on cheyenne after making the changes to make sure that it was backward compatilble.   There are still some issues with running scripts_regression_tests.py on this small (4 processor) system.   For example
Phase 'RUN' for test 'SEQ_Ln9.f19_g16_rx1.A.elm_gnu' required more processors, 9, than this machine can provide

Test suite: scripts_regression_tests.py on elm (Mac) and cheyenne
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes 

User interface changes?: 

Code review:

### CODE REVIEW

**Comment by billsacks** [comment]
Thanks, @jedwards4b . I'll try to look through this tomorrow. One initial question: Will the changes here require everyone who has done a port to their own machine to update the files in their .cime directory in some way? Or are these just cleanup changes / providing more reasonable defaults, which shouldn't require any action on the part of people who already have a working port?

**Comment by billsacks** [comment]
@mvertens - do you want to review this given your experience porting? Or should we merge this one and then open a new PR with any further changes needed?

**Comment by jedwards4b** [comment]
I've updated the README with improvement in the cprnc build instructions plus your suggested change.   One thing I noticed there which could perhaps be better clarified - you don't necessarily need to modify anything in config_compilers.xml or config_pes.xml.

**Comment by mvertens** [comment]
Lets open a new PR if there are further changes that are needed.

**Pull request merged**
