### PR TITLE
Add support for f05_f05_mg17 resolutiion

### PR DESCRIPTION
**Pull request by fvitt**
modified:   config/cesm/config_grids.xml

For running F compsets on half-degree horizontal resolution

Test suite: Smoke tests
 create_newcase --compset F2000climo --res f05_f05_mg17 --case ...
 SMS_Ld1.f09_g17.B1850.cheyenne_intel 
 SMS_Ld1.f09_f09_mg17.FHIST.cheyenne_intel
 SMS_Ld1.f09_f09_mg17.FWmaHIST.cheyenne_intel

Test status: expect bit-for-bit

Fixes CIME Github issue #2467
  Add support for half-degree CAM runs in CESM

User interface changes?: No

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by mvertens** [comment]
@billsacks, @fvitt - I think we need to get this on the release branches.
We had told Francis and Simone that we would try to get this into the
release. Lets talk tomorrow and determine if this would be problematic.

**Comment by ekluzek** [comment]
From my talking with Simone this afternoon, they really need f05 for the CESM2.0 release, because they need to run chemistry at this resolution, and they can't use the SE dycore for it yet. So it's a configuration that they need for the next several years to get the science they need to do with chemistry until they can replace it with a SE resolution.

**Comment by mvertens** [comment]
@ekluzek - thanks for the additional details as to why this is important to add.

**Comment by billsacks** [comment]
I'm okay with this being added to the release. In that case, this change should be rebased onto the maint-5.6 branch (because currently it is based off of the latest master), and then the base for the PR should be changed to maint-5.6.

**Comment by fvitt** [comment]
Someone needs to clue me on how to rebase this PR to maint-5.6

**Comment by jedwards4b** [comment]
I think that the easiest way is going to be to create a new branch from maint-5.6 and apply your changes there and open a new PR.   
```
git checkout maint-5.6 -b net_half_degree_res
git checkout half_degree_res -- config/cesm/config_grids.xml
git commit -a -m'add half degree grid'
```
This should get you a new branch based from maint-5.6 with your config_grids.xml changes.

**Comment by jedwards4b** [comment]
I've already done this and will post the new PR.

**Pull request closed without merging**
