### PR TITLE
addition of new dwav and dlnd compsets and functionality

### LINKED ISSUE #1100: Create a test for DLND
We need a test for DLND where DLND does something.

### PR DESCRIPTION
**Pull request by mvertens**
New compsets for DWAV and DLND

This PR does several things:
1) Adds new compsets ADWAV and ADLND, that permit testing of DWAV and
DLND from a stand-alone CIME checkout.
2) Cleans up the data models and removes outdated datamodes that are no longer used.
This helps clarify the functionality of the data models. The corresponding documentation
has been put in place in the CIME data model documentation.

Two new compsets have been added to 

  ```
<compset>
    <alias>ADWAV</alias>
    <lname>2000_SATM_SLND_SICE_SOCN_SROF_SGLC_DWAV%CLIMO</lname>
  </compset>
  <compset>
    <alias>ADLND</alias>
    <lname>2000_SATM_DLND%SCPL_SICE_SOCN_SROF_SGLC_SWAV</lname>
  </compset>
  
```
For ADWAV, the simples way to use it is as follows:

 `./create_newcase -case dwavtest -compset ADWAV -res ww3a --run-unsupported
`
This leads to the grid:

   `a%null_l%null_oi%null_r%rx1_g%null_w%ww3a_m%null 
`

However, ACME does not have a ww3a grid and does not leverage a DWAV model.

This PR will defer adding a test for ADWAV and ADLND until ACME decides what it
wants to do with these compsets and determines if it has grids compatible with running
these compsets.

For cesm, two new tests to add to its prealpha testing would be

  ```
   ERS.ww3a.ADWAV.machine_compiler 
   ERS.f09_f09.ADLND.machine_compiler
```
In addition, the following cesm tests have been run and compared to cesm2_0_alpha06h to verify
bfb functionality with the data model changes.

   ```
   ERI.f45_g37_rx1.DTEST.yellowstone_gnu.cice-default
   ERI.f45_g37_rx1.DTEST.yellowstone_gnu.cice-default
   ERI.f45_g37_rx1.DTEST.yellowstone_gnu.cice-default
   ERP_Ln9.f09_f09.FC55CLUBB.yellowstone_intel.cam-outfrq9s
   ERS_IOP.T62_g16.GIAF.yellowstone_intel.pop-default
   ERS_Lm3.T62_g16.AIAF.yellowstone_intel
   ERS_Ly20_N2_P2.f09_g16_gl10.TG1.yellowstone_pgi
   ERS_Ly3.f09_g16_gl4.TG.yellowstone_intel
   ERS.T62_g16.C.yellowstone_intel.pop-default
   ERS.T62_g37.G.yellowstone_gnu.pop-cice
   NCK_Ld1.f10_f10.ICRUCLM45.yellowstone_intel.clm-default
   NCK_Ld1.f10_f10.ICRUCLM45.yellowstone_intel.clm-default
   SMS_D_Ln9.f09_f09.FWAMIP.yellowstone_intel.cam-reduced_hist3s
   SMS_Ld1_Mmpi-serial.f45_f45.ICLM45.yellowstone_intel.clm-ptsRLA
```

Test suite: scripts_regression_test
Test baseline: for cesm alpha test for cesm2_0_alpha06h with above compsets
Test namelist changes: 
Test status: bit for bit

Fixes #1100

User interface changes?: None

Code review:

### CODE REVIEW

**Comment by rljacob** [comment]
When you say "This PR will defer adding a test for ADWAV and ADLND until ACME decides what it
wants to do with these compsets and determines if it has grids compatible with running
these compsets" isn't everything needed to run these tests entirely in CIME itself?

**Comment by mvertens** [comment]
No the issue is that the best grid to use for DWAV is ww3a - and I don't believe ACME has that grid or even wants it since its not interested in ww3 (at least as far as I know). So I did not want to put in a grid in place for this test that ACME wanted. 

In terms of the DLND, I want to make sure that we really want to add an f09_f09 test in the scripts regression test - or is there another one to add. 

So this PR puts the capability in CIME to have DLND and DWAV compsets in stand-alone CIME - but leaves open the question of what we want to now add to the scripts_regression_test.

**Comment by rljacob** [comment]
Ok but I have no problem with another PR adding tests of those compsets.  Its just another entry in config_grids.xml right?

**Comment by mvertens** [comment]
Yes - on the acme side.

**Comment by rljacob** [comment]
Please change the PR title to "verb noun".   Also remove the text in [] in the PR description.

**Comment by jedwards4b** [comment]
I am rerunning scripts_regression_tests.py after resolving merge conflicts.

**Comment by mvertens** [comment]
I think at this point this PR is ready to merge.

**Pull request merged**
