### PR TITLE
Update nuopc esmf

### PR DESCRIPTION
**Pull request by jedwards4b**
Update cheyenne nuopc esmf to 8.1.0b05, fix bug in env_batch/env_workflow.py which caused an error in xmlquery --listall

Test suite: scripts_regression_tests.py
Test baseline: 
Test namelist changes: 
Test status: bit for bit
Fixes 

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by jgfouca** [comment]
So we're removing support for PROJECT_REQUIRED?

**Comment by rljacob** [comment]
Yeah what was the bug?  This seems like the wrong fix.

**Comment by jgfouca** [comment]
It looks like maybe he thought about moving PROJECT_REQUIRED to env_workflow.xml. But the driver config_component.xml files still have it going to env_batch.xml.

**Comment by jedwards4b** [comment]
I see what happened, in mct it still goes in env_batch.xml but in nuopc it goes in env_workflow.xml
I think I had a reason for moving it but can't remember now.  I'll move it back until I can recall again.

**Comment by jedwards4b** [comment]
We found some significant differences with this change, we are backing it out until we can determine the difference.

**Pull request merged**
