### PR TITLE
remove cprnc to new repo

### PR DESCRIPTION
**Pull request by jedwards4b**
Puts the cprnc program into it's own repo
Test suite: scripts_regression_tests on derecho
Test baseline:
Test namelist changes:
Test status: bit for bit

Fixes

User interface changes?:  cprnc is now external and added with Externals_cime.cfg
This means that in your Externals.cfg you will need:
`externals = Externals_cime.cfg`

Update gh-pages html (Y/N)?:

### CODE REVIEW

**Comment by jedwards4b** [comment]
@jasonb5 please do.   I think you already have permissions but I'll confirm.

**Comment by rljacob** [comment]
Please also add an entry in .gitmodules for those of us using submodules.

**Comment by jedwards4b** [comment]
We're getting closer - thank you @jasonb5

**Review by billsacks — APPROVED** [review]
Thanks a lot for your work on this, @jedwards4b!

**Comment by jasonb5** [comment]
@jedwards4b Looks like the cprnc repo is missing a Makefile required for one of the E3Sm tests.

**Comment by jedwards4b** [comment]
It shouldn't need a Makefile - it's a cmake build.

**Comment by jedwards4b** [comment]
@jasonb5 I think I have it fixed - should I push the change?

**Comment by jasonb5** [comment]
@jedwards4b Go ahead and push it.

**Comment by jedwards4b** [comment]
@mnlevy1981 I'm trying to run the test_get_domain.sh script on derecho - it's looking for a file that doesn't exist:
${inputdata_root}/cpl/gridmaps/oQU240/map_oQU240_to_ne4np4_aave.160614.nc

**Comment by jedwards4b** [comment]
try to push since I don't have data for a local test

**Comment by jasonb5** [comment]
That's fine, the changes look right, it's the same route I was on.

**Pull request merged**
