### PR TITLE
Fix current mods test

### LINKED ISSUE #3728: scripts_regression_tests.py Y_TestUserConcurrentMods is failing for cesm
It seems to archive the cesm.log before the file is grepped to look for the run successful message.

### PR DESCRIPTION
**Pull request by jgfouca**
Fixes Y_TestUserConcurrentMods by adding a more-robust waiting scheme.

Prior to this PR, 6 of 10 Y_TestUserConcurrentMods runs on a sandia batch machine failed. After, 10 of 10 passed, so I think the race conditions are gone.

Test suite: scripts_regression_tests Y_TestUserConcurrentMods
Test baseline: 
Test namelist changes: 
Test status: [bit for bit, roundoff, climate changing]

Fixes #3728 

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review: @jedwards4b

### CODE REVIEW

**Comment by jedwards4b** [comment]
```
======================================================================
FAIL: test_user_concurrent_mods (__main__.Y_TestUserConcurrentMods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts_regression_tests.py", line 1909, in test_user_concurrent_mods
    casedir = self._create_test(["--walltime=0:30:00", "TESTRUNUSERXMLCHANGE_P1.f19_g16.X"], test_id=self._baseline_name)
  File "./scripts_regression_tests.py", line 1276, in _create_test
    self._wait_for_tests(test_id, expect_works=(not pre_run_errors and not run_errors))
  File "./scripts_regression_tests.py", line 1287, in _wait_for_tests
    from_dir=self._testroot, expected_stat=expected_stat)
  File "./scripts_regression_tests.py", line 70, in run_cmd_assert_result
    test_obj.assertEqual(stat, expected_stat, msg=msg)
AssertionError: 
COMMAND: /home/jedwards/cesm2_x_alpha/cime/scripts/Tools/wait_for_tests  *fake_testing_only_20201014_074057/TestStatus
FROM_DIR: /scratch/cluster/jedwards/scripts_regression_test.20201014_074057
SHOULD HAVE WORKED, INSTEAD GOT STAT 100
OUTPUT: Test 'TESTRUNUSERXMLCHANGE_P1.f19_g16.X.izumi_intel' finished with status 'FAIL'
    Path: TESTRUNUSERXMLCHANGE_P1.f19_g16.X.izumi_intel.fake_testing_only_20201014_074057/TestStatus
ERRPUT: 


----------------------------------------------------------------------
Ran 1 test in 279.640s

FAILED (failures=1)
[jedwards@izumi tests]$ git status
On branch jgfouca/fix_current_mods_test
```

**Comment by jedwards4b** [comment]
Changing _P1 to _Mmpi-serial seems to solve the problem.  @jgfouca can I push this change back?

**Comment by jedwards4b** [comment]
Please also note that this test, even when it passes, seems to leave behind a directory:
```
ls -l /scratch/cluster/jedwards/scripts_regression_test.20201014_081759
total 4
-rwxr-xr-- 1 jedwards cgdcsm 83 Oct 14 08:18 testreporter
```
I have added code to remove the testreporter file and allow the directory to be removed.

**Review by jedwards4b — CHANGES_REQUESTED** [review]
I would like to push back changes to use mpi-serial and to clean up the test directory.

**Comment by jgfouca** [comment]
@jedwards4b , thanks, those changes sound good.

**Review by jedwards4b — APPROVED** [review]

**Pull request merged**
