### PR TITLE
use nodefail code for cheyenne 

### PR DESCRIPTION
**Pull request by jedwards4b**
Use the nodefail code to retry jobs on cheyenne when MPT timeouts occur on startup.
NODE_FAIL_REGEX="MPT ERROR: could not launch executable"

Test suite: 
Test baseline: 
Test namelist changes: 
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by jedwards4b** [comment]
@jgfouca I've modified this to get rid of the hardcoded machine name, but I haven't introduced any new xml variables.   Is this acceptable?

**Comment by jgfouca** [comment]
Yes, that's a pretty elegant way to get "retry" working. Should I merge?

**Comment by jedwards4b** [comment]
Let's wait a bit - I am still testing to make sure it solves the issue.  I've made a mock test and that works, but would like to get a real failure, I suspect we'll see one sometime this afternoon.

**Comment by jedwards4b** [comment]
@jgfouca I have confirmed that this works on cheyenne.

**Pull request merged**
