### PR TITLE
if nuopc and any datamodel add a cdeps directory

### PR DESCRIPTION
**Pull request by jedwards4b**
Add a SourceMods/src.cdeps directory for shared cdeps sourcemods

Test suite: scripts_regression_tests.py and hand testing of SMS.f19_g17.A.cheyenne_intel
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes  https://github.com/ESCOMP/CDEPS/issues/98

User interface changes?: 

Update gh-pages html (Y/N)?:

### CODE REVIEW

**Comment by jedwards4b** [comment]
@mvertens can you confirm this solves the issue and review.   Note that component specific cdeps files go in the component subdirectory and non-component specific files go in the added src.cdeps directory.

**Comment by billsacks** [comment]
CDEPS is built even if you don't have any data models in your case, right? (Because it's needed for streams functionality, right?). So I'm thinking that there should always be a cdeps SourceMods directory when building with driver nuopc?

**Comment by jedwards4b** [comment]
Right - that's a good point, I'll remove that conditional.  Thanks

**Review by billsacks — APPROVED** [review]
Thanks!

**Pull request merged**
