### PR TITLE
Upgrade preview_run.

### PR DESCRIPTION
**Pull request by jgfouca**
1) Redo the formatting of output to make it prettier
2) Add some output for key derived attributes
3) Add logger.info suggestion to user to run preview_run

Test suite: by-hand, code-checker
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes [CIME Github issue #]

User interface changes?: preview_run output improvements

Update gh-pages html (Y/N)?: N

Code review: @jedwards4b

### CODE REVIEW

**Comment by jgfouca** [comment]
Example of new output:

```
CASE INFO:
  nodes: 1
  total tasks: 24
  tasks per node: 24
  thread count: 2

BATCH INFO:
  FOR JOB: case.test
    ENV:
      module command is /usr/bin/modulecmd python purge 
      module command is /usr/bin/modulecmd python load sems-env acme-env sems-git sems-python/2.7.9 sems-cmake/2.8.12 sems-gcc/5.3.0 sems-openmpi/1.8.7 sems-netcdf/4.4.1/exo_parallel
      Setting Environment NETCDFROOT=/projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.4.1/gcc/5.3.0/openmpi/1.8.7/exo_parallel
      Setting Environment OMP_STACKSIZE=64M
      Setting Environment OMP_PROC_BIND=spread
      Setting Environment OMP_PLACES=threads
      Setting Environment PNETCDFROOT=/projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.4.1/gcc/5.3.0/openmpi/1.8.7/exo_parallel
    SUBMIT CMD:
      case.test

MPIRUN:
  mpirun  -np 24  --map-by ppr:12:socket:PE=2 --bind-to hwthread /home/jgfouca/acme/scratch/SMS_P24x2.f19_g16_rx1.A.melvin_gnu.20180503_131747_xuv3a7/bld/e3sm.exe  >> e3sm.log.$LID 2>&1 
```

**Comment by jedwards4b** [comment]
@jgfouca failing travis-ci testing, please address.

**Comment by jgfouca** [comment]
@jedwards4b , I cannot reproduce this error on my machine

**Comment by jgfouca** [comment]
I think it has something to do with Travis using newer versions than I have.

**Comment by jgfouca** [comment]
OK, that fixed it.

**Pull request merged**
