### PR TITLE
xmlchange: Add documentation for setting values with commas

### PR DESCRIPTION
**Pull request by jgfouca**
This has come up a few times and confused our users.

Test suite: None, just a docs change
Test baseline:
Test namelist changes:
Test status: bit for bit

User interface changes?:

Update gh-pages html (Y/N)?:

### CODE REVIEW

**Review by jedwards4b — APPROVED** [review]
Thanks for figuring this out.

**Comment by klindsay28** [comment]
Spelling correction from the peanut gallery...
alternaltive -> alternative

**Comment by jgfouca** [comment]
Thanks, @klindsay28 . Fixed.

**Review by jasonb5 — APPROVED** [review]
LGTM

**Pull request merged**
