### PR TITLE
Add quotation marks to timing entry names - Resolved conflicts

### PR DESCRIPTION
**Pull request by jayeshkrishna**
Adds quotation marks to timing entry names.

Test suite: X case
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes [CIME Github issue #]

User interface changes?: 

Code review: @jedwards4b

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
This is a conflict resolved version of PR #467

**Comment by jayeshkrishna** [comment]
I could not run script_regression_tests.py on anlworkstation (compute001) or blues (on this branch or CIME master)
Got an X case working and verified that timer names had quotes as required after building with a local merge to cime-maint5.1 (I could build the X case after merging this branch to cime-maint5.1)
Will see if I can get script_regression_tests.py to run on anlworkstation+cime-maint5.1_local_merge_with_this_branch

**Comment by jayeshkrishna** [comment]
The script_regression_tests.py passes most of the tests with anlworkstation+cime-maint5.1_local_merge_with_this_branch . The failures are however not related to this change,
* Fail due to issues with mpi-serial (Some MPI functions missing)
* Fail due to manual reduction (from 64 to 16) of pes available on compute001 (By default it uses all cores but compute001 is a shared machine. Some tests fail if you run it with < 64 procs)

**Comment by jayeshkrishna** [comment]
This change should be ready for review+merge

**Comment by worleyph** [comment]
Note that this approach will not affect direct calls to GPTL (e.g. GPTLstart/GPLTstop), only calls that go through perf_mod.F90. So, some of the timers in pio2 will not be quoted, and they will not pick up the prefixes added at the perf_mod level. I don't know if there are other instances of this. I don't have a suggestion about how to address this. Have something similar to perf_mod on the C side to add model-specific customizations? or have C call the fortran entry points? Both seem awkward. However scripts that expect timer names to be quoted will break if they are missing.

**Pull request merged**
