### PR TITLE
Fixes exception from xmlchange

### PR DESCRIPTION
**Pull request by jasonb5**
The `xmlchange` tool should not raise an exception when a diff is detected.

Test suite:
Test baseline:
Test namelist changes:
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]
User interface changes?:
Update gh-pages html (Y/N)?:

### CODE REVIEW

**Comment by jedwards4b** [comment]
@jasonb5 that solved the first problem but I am still seeing:
```
======================================================================
FAIL: test_e_xmlquery (test_sys_create_newcase.TestCreateNewcase)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/glade/work/jedwards/sandboxes/cesm2_x_alpha/cime/CIME/tests/test_sys_create_newcase.py", line 321, in test_e_xmlquery
self.assertTrue(output == "TRUE", msg="%s != %s" % (output, BUILD_COMPLETE))
AssertionError: False is not true : FALSE != False

----------------------------------------------------------------------
```
I think that I have a fix for this and will push it back if that's okay?

**Comment by jasonb5** [comment]
@jedwards4b Go ahead and push your fix.

**Comment by jedwards4b** [comment]
@jasonb5 based on [this result](https://github.com/ESCOMP/CMEPS/pull/464) I am ready to merge this PR.

**Review by jedwards4b — APPROVED** [review]

**Comment by jedwards4b** [comment]
I'll have to double check - I realized that #4631 fixed the github testing and that I needed that more urgently than testing on derecho or perlmutter.  I think there are still some issues that need to be addressed there, but I'm not sure if this is one of them.

**Pull request merged**
