### PR TITLE
Support complex arguments and limit number of positional arguments in xmlchange

### LINKED ISSUE #323: xmlchange doesn't report bad syntax
On edison, I tried to do: `./xmlchange SAVE_TIMING TRUE` and it returned quietly with no error message as if it was successful.  But this syntax does nothing.  The right syntax is: `./xmlchange SAVE_TIMING=TRUE`

### LINKED ISSUE #364: xmlchange broken for complex arguments
xmlchange needs to support the following:
```
./xmlchange CICE_CPPDEFS="-DCCSMCOUPLED -Dncdf -DNUMIN=11 -DNUMAX=99 -DNICECAT=5 -DNXGLOB=100 -DNYGLOB=116 -DNTRAERO=3 -DNBGCLYR=3 -DNICELYR=8 -DNSNWLYR=3 -DTRAGE=1 -DTRFY=1 -DTRLVL=1 -DTRPND=1 -DTRBRI=0 -DTRBGCS=0"
```

Since CESM was broken, I had to revert #343 . Please unrevert this revert, fix the above usecase, and maybe add a scripts_regression_test for this usecase.

### PR DESCRIPTION
**Pull request by wilke**
Limiting the number of positional command line arguments to 1 or 0. 
Implicit provided argument is in the form of key=value.
Supporting complex arguments. The value in key=value can contain equal signs too.

Test suite: 
Test baseline: 
Test namelist changes: 
Test status: [bit for bit, roundoff, climate changing]

Fixes #323  

Avoids problems reported in #359 and #364 
User interface changes?: 

Code review:

### CODE REVIEW

**Comment by rljacob** [comment]
Replaces PR #343

**Comment by jedwards4b** [comment]
This still doesn't work 
./xmlchange JOB_QUEUE="The fox, the bear, and the cat"

**Comment by wilke** [comment]
The comma syntax is a new feature, I suggest closing this pull request and branch and opening a new issue?

**Comment by rljacob** [comment]
Yes.  That is the "git way".

**Comment by jedwards4b** [comment]
okay fine - please resolve conflicts and merge, I will open an issue on the syntax error.

**Comment by rljacob** [comment]
Andreas, Jim was supposed to integrate this.  No one should merge their own PRs to master.

**Comment by rljacob** [comment]
Nevermind.  I see Jim told you to merge it.

**Pull request merged**
