### PR TITLE
fix the restart tests by using ceil instead of int

### PR DESCRIPTION
**Pull request by jedwards4b**
int was rounding down, but this calculation should round up. 

Test suite: ERS.f19_g17.A.derecho_intel
Test baseline:
Test namelist changes:
Test status: bit for bit

Fixes #4667 

User interface changes?:

Update gh-pages html (Y/N)?:

### CODE REVIEW

**Comment by jedwards4b** [comment]
@jasonb5 we continue to have trouble with black tests failing on files we didn't touch...

**Comment by jasonb5** [comment]
@jedwards4b #4670 will fix the pre-commit failure. See the PR description for an explanation.

**Review by jgfouca — COMMENTED** [review]
Did you intend to update the cprnc submodule?

**Comment by jedwards4b** [comment]
No - I'll back that out.  Thanks

**Review by jgfouca — APPROVED** [review]

**Comment by fischer-ncar** [comment]
@jedwards4b This PR is causing several prealpha test failures.  An example is ERS_Ly7.f09_g17_gris4.T1850Gg.derecho_intel.

```python
Traceback (most recent call last):
  File "/glade/u/home/fischer/code/cesm3_0_alpha03b/cime/CIME/SystemTests/system_tests_common.py", line 351, in run
    self.run_phase()
  File "/glade/u/home/fischer/code/cesm3_0_alpha03b/cime/CIME/SystemTests/ers.py", line 53, in run_phase
    self._ers_first_phase()
  File "/glade/u/home/fischer/code/cesm3_0_alpha03b/cime/CIME/SystemTests/ers.py", line 19, in _ers_first_phase
    self._rest_n = self._set_restart_interval()
  File "/glade/u/home/fischer/code/cesm3_0_alpha03b/cime/CIME/SystemTests/system_tests_common.py", line 179, in _set_restart_interval
    expect(stop_n > 0, "Bad STOP_N: {:d}".format(stop_n))
ValueError: Unknown format code 'd' for object of type 'float'

```

**Comment by jedwards4b** [comment]
Got it - fix coming.

**Comment by jedwards4b** [comment]
https://github.com/ESMCI/cime/pull/4671

**Pull request merged**
