### PR TITLE
Reinstate ability to select queue by num tasks

### LINKED ISSUE #2209: Want ability to select default queue based on number of tasks, not just number of nodes
We used to have the ability for cime to select a default queue based on the number of tasks. With @jgfouca 's changes in #1918 (to fix #1913), this is no longer possible.

This is important for jobs that use less than a full node - such as single-point or other jobs that use a single task. CLM, CISM and possibly other components have used this capability in some configurations. Now these single-processor jobs are using a full node - so, on cheyenne, they are getting charged 36x what they should be.

Can we get back the capability to select queues based on the number of tasks?

@jedwards4b @ekluzek

### PR DESCRIPTION
**Pull request by jgfouca**
Test suite: scripts_regression_tests (on batch machine)
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes #2209 

User interface changes?: N

Update gh-pages html (Y/N)?: N

Code review: @jedwards4b @billsacks

### CODE REVIEW

**Comment by jgfouca** [comment]
I'm unable to test this new feature without access to cheyenne.

**Comment by jedwards4b** [comment]
I did suggest a way to test on nersc systems.  Edison and cori have a debug queue that should work for this purpose.

**Comment by jgfouca** [comment]
@jedwards4b , i think the debug queue supports a few nodes. At least is does in the e3sm configuration. I suppose I could temporarily change the config to use num_tasks=1.

**Comment by jgfouca** [comment]
@jedwards4b , my test:

change sandiatoss3 queue settings:
```
  <batch_system MACH="sandiatoss3" type="slurm" >
    <queues>
      <queue jobmin="1" jobmax="1" walltimemax="04:00:00" strict="true" default="true">short</queue>
      <queue nodemin="1" nodemax="64" walltimemax="24:00:00">batch</queue>
    </queues>
  </batch_system>
```

Then do:
```
% ./create_test ERS_P1.f19_g16_rx1.A --no-build

% ./create_test ERS_P2.f19_g16_rx1.A --no-build
```

I confirmed that the P1 case uses the "short" queue via preview_run. The P2 case uses "batch".

**Comment by jedwards4b** [comment]
On this branch I add to config_batch.xml:
```      <queue walltimemax="06:00" jobmin="1" jobmax="18">share</queue>```
and tried a test SMS_P1.f09_g16.X
But preview run shows
```BATCH SUBMIT: (nodes 1)
    case.test -> qsub    -q regular -l walltime=12:00:00 -A P93300606 -m a .case.test ```

**Comment by jgfouca** [comment]
@jedwards4b , the system will prefer the default queue if it's compatible.

**Comment by jgfouca** [comment]
This is why, I generally prefer to make the "smaller" queue the default whenever possible.

**Comment by jedwards4b** [comment]
Right, once I did that I get the correct queue for case.run and case.test, but the case.st_archive is still going to the other (regular) queue - is task_count being interpreted somewhere as node count?

**Comment by jgfouca** [comment]
@jedwards4b , shoot! Let me try to fix that.

**Comment by jgfouca** [comment]
@billsacks , i added comments.

**Comment by jgfouca** [comment]
@jedwards4b , bug fixed.

**Comment by billsacks** [comment]
@jgfouca looks good - thanks!

**Pull request merged**
