### PR TITLE
modified regexp for pylint version test

### PR DESCRIPTION
**Pull request by wilke**
Better check for pylint version

Test suite: B_CheckCode
Test baseline: 
Test namelist changes: 
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?: 

Code review:

### CODE REVIEW

**Comment by sarich** [comment]
you left in the print("DEBUG:\n")

**Comment by rljacob** [comment]
Wasn't @sarich supposed to merge this?

**Comment by wilke** [comment]
yes - but I handled his comment and it is only going into the debug branch not master.

**Comment by rljacob** [comment]
Ok you're right.  I didn't notice the target of the merge.

**Pull request merged**
