### PR TITLE
Singhbalwinder/machines/constance mach files maint cime5.1

### PR DESCRIPTION
**Pull request by jgfouca**
Test suite: 
Test baseline: 
Test namelist changes: 
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?: 

Code review:

### CODE REVIEW

**Comment by jgfouca** [comment]
Does anyone understand why Ballwinder's branch that was made off of maint ids not merging cleanly into master? Shouldn't master have every commit that's on maint?

**Comment by rljacob** [comment]
No because I've been adding things to maint to get it ready for ACME and not necessarily to master.

**Comment by jedwards4b** [comment]
I had a really hard time when I tried to do this with the cori update - my conclusion was that you really need to do two separate branches from the respective heads instead of one from the branch point.

**Comment by jgfouca** [comment]
@rljacob I'm going to close this PR. I did a cherry pick of this commit. I am concerned though that things are going onto maint and not master. Are we going to merge maint into master?

**Comment by rljacob** [comment]
Yes we should merge maint to master.  Something to talk about this Friday.

**Comment by singhbalwinder** [comment]
I also had hard time rebasing my old branch on to maint-cime5.1 branch. Cherry picking also added a lot of unintended changes, so I started off with a fresh branch from maint-cime5.1.

**Pull request closed without merging**
