### PR TITLE
PEA should not always fail on machines without mpi-serial

### PR DESCRIPTION
**Pull request by jgfouca**
Test suite: Pylint (PEA not currently tested)
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes [CIME Github issue #]

User interface changes?: No

Code review: jedwards

### CODE REVIEW

**Comment by jgfouca** [comment]
@jedwards4b , thoughts?

**Comment by billsacks** [comment]
I don't like the idea of forcing a test to do nothing under some circumstances: It will be hard to determine what's actually being tested. ("Our PEA tests have all been passing.... Oh, right, they aren't actually testing anything.") It would be better to (a) not run the PEA test on such machines, or (b) let it fail and mark it as an expected failure.

**Comment by jedwards4b** [comment]
Please resolve conflicts and merge

**Comment by rljacob** [comment]
Is this related to issue #527 ?    What we really need is a rule: "don't put PEA in a test suite that must run on every machine".  Because not every machine can run mpi-serial.  If we can do that, we don't need this PR.

**Comment by jgfouca** [comment]
Yes, this PR was initially related to 527 which turned out to be something else. I don't feel strongly either way, @rljacob you can be the tie-breaker. Do you think PEA should fail if the system doesn't support mpi-serial?

**Comment by jedwards4b** [comment]
What about having the test in test suites but add code to create_test to skip it if the machine doesn't support mpi-serial?  I think that might be better than having the test do nothing and it's certainly better that not having it in suites.

**Comment by rljacob** [comment]
I'm not sure I like that idea either because its sets a bad precedent.  create_test should just run tests and not know anything about them.

If we want PEA to fail when mpi-serial doesn't exist, that's a different kind of FAIL then mpi-serial gives different answers.  Can we introduce an INVALID outcome?

**Comment by jgfouca** [comment]
@rljacob we could but that's a major change. If most machines that we test on support mpi-serial, then I'd prefer the changes in my PR. This will make the test show PASS on the few machines without mpi-serial so developers there won't have to dig into errors that are not really errors.

**Comment by billsacks** [comment]
If people feel this is the best solution, I'm willing to let this go as long as it doesn't become a slippery slope.

**Comment by billsacks** [comment]
As I think about this more: It strikes me that the PEA test is really more about testing the mpi-serial library than it is about testing cime/CESM/ACME: It's saying, "Is the mpi-serial library a valid substitute for a real mpi library?" In that light, these machine-specific failures are real signals that the answer is, in some cases, "no": mpi-serial is NOT always a valid substitute. In that sense, it seems like the correct solution would be to (eventually) fix the mpi-serial library. Although I could be misunderstanding these failures entirely, in which case feel free to ignore me :-)

I'm still okay with the current solution, I guess, acknowledging that it isn't ideal but is expedient.

**Comment by rljacob** [comment]
The fails that prompted this were the mpi-serial library failed to even build.

**Comment by jgfouca** [comment]
Merge?

**Comment by jedwards4b** [comment]
I'm okay with it.

**Comment by billsacks** [comment]
Me too

**Pull request merged**
