### PR TITLE
changes for izumi nag ESMF lib

### PR DESCRIPTION
**Pull request by fvitt**
Minor changes to Makefile needed for izumi nag build to link to ESMF lib. 
Point ESMFMKFILE to my nag built ESMF lib location on izumi.

Test suite: 

  SMS_D_Ln9.f45_f45_mg37.QPX2000.izumi_nag (Overall: PASS) details:
  SMS_Ln9.f45_f45_mg37.QPX2000.izumi_nag (Overall: PASS) details:
  SMS_D_Ln9.f19_f19_mg17.FX2000.cheyenne_intel (Overall: PASS) details:
  SMS_D_Ln9.f19_f19_mg17.QPX2000.cheyenne_intel (Overall: PASS) details:
  SMS_Ln9.f19_f19_mg17.FX2000.cheyenne_intel (Overall: PASS) details:

Fixes [CIME Github issue #] 

User interface changes?:  No

Update gh-pages html (Y/N)?: No

Code review:

### CODE REVIEW

**Review by jedwards4b — APPROVED** [review]
Thanks, I think one of the ESMF guys was working on this too,
we may need to merge this with his.

**Comment by jedwards4b** [comment]
Hi @fvitt  - The ESMF team has installed a module build for nag here: /fs/cgd/data0/modules/modulefiles/esmfpkgs/nag/6.2
can you try it and make changes in this PR to use it if it works properly?

**Comment by fvitt** [comment]
@jedwards4b - Yes, those esmf modules work.  Thanks.

**Review by jedwards4b — APPROVED** [review]
thanks

**Review by fischer-ncar — APPROVED** [review]

**Comment by jedwards4b** [comment]
@fvitt I've been working on the cmeps/cdeps port to nag and have an additional change to push back to this branch,
can you authorize me to do that?

**Comment by fvitt** [comment]
> @fvitt I've been working on the cmeps/cdeps port to nag and have an additional change to push back to this branch,
> can you authorize me to do that?

I have not figured out how to authorize you to push to my fork/branch.  Can you give me some hints?  Maybe issue a PR to my branch.

**Comment by jedwards4b** [comment]
From your fork web page: Settings/Manage Access/Invite a Collaborator.

**Pull request merged**
