### PR TITLE
Cmeps driver env var

### PR DESCRIPTION
**Pull request by jedwards4b**
We needed to add a way to differentiate between different drivers using the same coupler.

Test suite: scripts_regression_tests.py
Test baseline: 
Test namelist changes: 
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by rsdunlapiv** [comment]
@jedwards4b would you consider another name than `CMEPS_DRIVER`?  Drivers and different than mediators, so you might have a configuration not using CMEPS that still needs to set its driver.

**Comment by jedwards4b** [comment]
@rsdunlapiv This code is specific to the cmeps mediator - we are telling cmeps what driver it should use so the name seems to me to be entirely appropriate.

**Comment by rsdunlapiv** [comment]
@jedwards4b I disagree.  CMEPS actually does not know what driver it uses, which is why it works both under NEMS and with the CESM/CIME driver.  That's by design.  This variable is setting what driver to use for the coupled system, regardless of whether CMEPS is a part of it.

**Comment by uturuncoglu** [comment]
Yes. The variable name can be changed to more convenient one such as DRIVER_NAME?

**Comment by mvertens** [comment]
I agree with @rsdunlapiv regarding the naming convention. CMEPS needs to be treated like any other component and I plan to actually move it out of CIME and with the other CESM components in an upcoming PR.

**Comment by jedwards4b** [comment]
How about UFS_DRIVER?  I am concerned that this solves a very particular problem and the suggested names are too general implying this may do more that it is intended to.

**Comment by uturuncoglu** [comment]
I updated CMEPS_DRIVER as UFS_DRIVER.

**Pull request merged**
