### PR TITLE
New mesh file and grid for running CISM over Antarctica

### PR DESCRIPTION
**Pull request by billsacks**
Test suite: aux_glc
Test baseline: cismwrap_2_1_87
Test namelist changes: none
Test status: bit for bit

Fixes none

User interface changes?: N

Update gh-pages html (Y/N)?: N

### CODE REVIEW

**Review by fischer-ncar — APPROVED** [review]
Looks good.  Just make sure you rimport antarctica_8km_epsg3031_ESMFmesh_c210621.nc to the subversion server.

**Comment by jasonb5** [comment]
@billsacks I'm having the same test failures for #4060 and #4066. Looks like this commit (https://github.com/ESCOMP/CESM_CPL7andDataComps/commit/9e2fdcfd69d4011580c4e3b9fc3949546e3e4fe2) is causing the `This compset and grid combination is untested in CESM.  Override this warning with the --run-unsupported option to create_newcase.` error.

Should we fix this in cime by adding the `--run-unsupported` or add the correct compset+grid in `ESCOMP/CESM_CPL7andDataComps`?

**Comment by billsacks** [comment]
@fischer-ncar that file is in the server.

@jasonb5 thanks for tracking down the source of the error. I'd cast a weak vote for adding `--run-unsupported` to the failing test cases. @fischer-ncar - would you be able to take that on? Unless @jasonb5 has already figured out exactly what needs to be done and would be able to fix it quickly.

**Comment by jasonb5** [comment]
@billsacks I'd be fine trying to add the flag. I'll update if that fixes the issues.

**Comment by fischer-ncar** [comment]
@billsacks @jasonb5 adding the --run-unsupported would be fine.

**Comment by jasonb5** [comment]
@billsacks once #4066 is merged the fixes will be in master.

**Comment by billsacks** [comment]
> once #4066 is merged the fixes will be in master.

Thanks a lot for this @jasonb5 !

**Review by fischer-ncar — APPROVED** [review]

**Pull request merged**
