### PR TITLE
Add missing doctest

### PR DESCRIPTION
**Pull request by jasonb5**
Adds missing doctests.

`./scripts_regression_tests.py test_unit_doctest` will run the doctests.

Test suite: scripts_regression_tests.py
Test baseline: n/a
Test namelist changes: n/a
Test status: n/a

Fixes n/a
User interface changes? n/a
Update gh-pages html (Y/N)?: N

### CODE REVIEW

**Comment by jasonb5** [comment]
@jedwards4b Can you check https://github.com/jasonb5/cime/blob/71ce9b503a541c06bdde770a7fa2025a9a26570c/scripts/lib/CIME/case/case.py#L743-L744, this test failed. https://github.com/ESMCI/cime/pull/4159/commits/6779d261f61c7b663657faa33881b076d060730f fixed it, but I just wanted to double check everything looks good.

**Comment by jedwards4b** [comment]
@jasonb5 yes that change in case.py is correct, thank you.
However I don't have any indication that doctests are working
This is documented in the README:

> ./scripts_regression_tests.py A_RunUnitTests
> Machine object has no machine defined
> Testing commit 71ce9b503a541c06bdde770a7fa2025a9a26570c
> Using cime_model = cesm
> Testing machine = cheyenne
> Test root: /glade/scratch/jedwards/scripts_regression_test.20220113_080614
> Test driver: nuopc
> Python version 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
> [GCC 9.4.0]
> 
> A_RunUnitTests (unittest.loader._FailedTest) ... ERROR
> 
> ======================================================================
> ERROR: A_RunUnitTests (unittest.loader._FailedTest)
> ----------------------------------------------------------------------
> ImportError: Failed to import test module: A_RunUnitTests
> Traceback (most recent call last):
>   File "/glade/work/jedwards/conda/cheyenne/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
>     module = __import__(module_name)
> ModuleNotFoundError: No module named 'A_RunUnitTests'
> 
How do I run doctests with this script?  Can you update the Readme?

**Comment by jasonb5** [comment]
@jedwards4b You can run the doctests with `./scripts_regression_tests.py test_unit_doctest` or it will run when you run all the tests with just `./scripts_regression_tests.py`.

I will update the readme.

**Review by jedwards4b — APPROVED** [review]

**Review by jgfouca — APPROVED** [review]

**Comment by jgfouca** [comment]
@jasonb5 , were you going to update the README in this PR or should I merge?

**Comment by jasonb5** [comment]
@jgfouca I need to update the readme.

**Comment by jasonb5** [comment]
@jgfouca Can merge now.

**Pull request merged**
