### PR TITLE
update netcdf and pnetcdf modules for cesm on edison

### PR DESCRIPTION
**Pull request by jedwards4b**
Move to latest available modules, avoids a runtime error about hdf5 module incompatibility.

Test suite: 
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes 

User interface changes?: 

Code review:

### CODE REVIEW

**Comment by rljacob** [comment]
Not sure who to assign this to for reviewing.  Who besides JImE cares about CESM on edison?

**Comment by jedwards4b** [comment]
Do we need a review for changes restricted to the cime_config/model/machines directory?

**Comment by rljacob** [comment]
Up to you for CESM.  ACME has machine points-of-contact who are responsible.

**Comment by jedwards4b** [comment]
that would be me!

**Pull request merged**
