### PR TITLE
case.setup: Fix case reset on some machines

### LINKED ISSUE #3473: Some cime_developer tests fail during phase SHAREDLIB_BUILD
This issue is reproducible on both anlworkstation and summit.
It is caused by PR #3449: Improve case.setup clean (happens for --clean or --reset)

Steps to reproduce:
```
git clone https://github.com/ESMCI/cime.git
cd cime/scripts
./create_test DAE.ww3a.ADWAV --no-run
```
Errors are:
```
        ...
        WARNING: Test case setup failed. Case2 has been removed, but the main case may be in an inconsistent state. If you want to rerun this test, you should create a new test rather than trying to rerun this one.
        ERROR: Cannot move past core phase 'SETUP', it didn't pass:
```

CaseStatus shows:
```
case.setup error 
ERROR: FakeCase does not support getting value of 'SMP_PRESENT'
```
Another way to reproduce this issue:
```
git clone https://github.com/ESMCI/cime.git
cd cime/scripts
./create_test DAE.ww3a.ADWAV --no-build
cd to Case dir
./case.setup --reset
```
Output messages:
```
Successfully cleaned .case.test
Successfully cleaned env_mach_specific.xml
Successfully cleaned Macros.make
Successfully cleaned Macros.cmake
ERROR: FakeCase does not support getting value of 'SMP_PRESENT'
```

### PR DESCRIPTION
**Pull request by jgfouca**
Removing env_mach_specific.xml triggered the FakeCase path in
BuildConf.configure. This path doesn't work if the machine is using
advanced attribute selectors (e.g. SMP_PRESENT) in their environment
block in config_machines.xml.

case_setup only needs BuildConf.configure to recreate the env_mach_specific.xml
file and the Macro files.

Test suite: scripts_regression_tests
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes #3473 

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review: @jedwards4b

### CODE REVIEW

**Comment by dqwu** [comment]
@jgfouca 
I have tested this PR on anlworkstation, which has caused 3 tests to fail:
ERP_Ln9.f45_g37_rx1.A.anlworkstation_gnu
NCK_Ld3.f45_g37_rx1.A.anlworkstation_gnu
PEM_Ln9_P4.f19_f19.A.anlworkstation_gnu

```
WARNING: Test case setup failed. Case2 has been removed, but the main case may be in an inconsistent state. If you want to rerun this test, you should create a new test rather than trying to rerun this one.
ERROR: Potential loss of unflushed changes in /sandbox/jenkins-ci/workspace/CIME_SCORPIO_CLASSIC/test_cime_scorpio_classic/ERP_Ln9.f45_g37_rx1.A.anlworkstation_gnu.20200408_140123_rffqq9/case2/ERP_Ln9.f45_g37_rx1.A.anlworkstation_gnu.20200408_140123_rffqq9/env_run.xml
```

**Comment by jgfouca** [comment]
@dqwu , I'm seeing the same failures. Fixing soon.

**Comment by dqwu** [comment]
@jgfouca 
The "Potential loss of unflushed changes" error is still reproducible with latest PR.

`ERROR: Potential loss of unflushed changes in /sandbox/jenkins-ci/workspace/CIME_SCORPIO/test_cime_scorpio/ERP_Ln9.f45_g37_rx1.A.anlworkstation_gnu.20200409_045904_yudw3g/case2/ERP_Ln9.f45_g37_rx1.A.anlworkstation_gnu.20200409_045904_yudw3g/env_run.xml`

Could you manually run ERP_Ln9.f45_g37_rx1.A on anlworkstation to make sure it is fixed?

**Comment by dqwu** [comment]
@jgfouca 
Sorry for the confusion. It is already fixed. That error is from yesterday's Jenkins run without your fix.

**Comment by jgfouca** [comment]
No worries, glad it's fixed.

**Comment by jgfouca** [comment]
All tests are passing for me.

**Pull request merged**
