### PR TITLE
check current machine and exit if not case machine

### LINKED ISSUE #4178: Throw a sensible error message when submitting from the wrong machine.
I think this is the right place for this! (@mvertens is this the right place?)
This may just be me, but I am often moving back and forth between cheyenne and casper for example, and occasionally end up submitting a job I had built on cheyenne on casper which throws a traceback of course, and puzzles me for a while. Could we have a sensible exit that says straight up that I am not submitting on the machine/architecture I had originally built it on. Trivial I know, but hey.

### PR DESCRIPTION
**Pull request by jedwards4b**
When initializing the case object for an existing case make sure that it matches the machine you are on,
throw an error otherwise

Test suite:scripts_regression_tests.py  hand testing on casper and cheyenne
Test baseline:
Test namelist changes:
Test status: bit for bit

Fixes #4178

User interface changes?:

Update gh-pages html (Y/N)?:

### CODE REVIEW

**Comment by jedwards4b** [comment]
Are there situations where this check will be problematic?  Should we have an override option?

**Comment by jedwards4b** [comment]
@jgfouca is there a way to know (when initializing the case) if we are using that feature?

**Comment by jgfouca** [comment]
@jedwards4b  `--non-local` flag for create_newcase.

**Review by jgfouca — APPROVED** [review]

**Review by fischer-ncar — APPROVED** [review]

**Comment by jedwards4b** [comment]
Having trouble with:
```
======================================================================
FAIL: test_rebless_namelist (CIME.tests.test_sys_bless_tests_results.TestBlessTestResults)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/work/jedwards/sandboxes/cesm2_3_alpha08a.cice5/cime/scripts/lib/CIME/tests/test_sys_bless_tests_results.py", line 212, in test_rebless_namelist
    self._create_test(compargs)
  File "/glade/work/jedwards/sandboxes/cesm2_3_alpha08a.cice5/cime/scripts/lib/CIME/tests/base.py", line 236, in _create_test
    output = self.run_cmd_assert_result(
  File "/glade/work/jedwards/sandboxes/cesm2_3_alpha08a.cice5/cime/scripts/lib/CIME/tests/base.py", line 137, in run_cmd_assert_result
    self.assertEqual(stat, expected_stat, msg=msg)
AssertionError: 100 != 0 : 
```

**Comment by jgfouca** [comment]
@jedwards4b , you may need to add some verbose printing (command + output/stderr) to see what the problem is.

**Pull request merged**
