### PR TITLE
properly link nag f90

### PR DESCRIPTION
**Pull request by jedwards4b**
Fix an issue in mct configure by providing the correct link flags for nag f90.

Test suite: SMS_D.f45_g37.A.izumi_nag
Test baseline: 
Test namelist changes: 
Test status: [bit for bit, roundoff, climate changing]

Fixes 

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by fischer-ncar** [comment]
For hobart, these links are specified in cime/scripts/Tools/Makefile.  Which is bad, because it makes
it hard to find, as I found out.  We should remove the code for hobart from the Makefile and put
it in config_compiler.xml where it belongs.

Code in Makefile

      ifeq ($(strip $(MACH)),hobart)
       # GCC needs to be able to link to
       # nagfor runtime to get autoconf
       # tests to work.
         CFLAGS += -Wl,--as-needed,--allow-shlib-undefined
         SLIBS += -L$(COMPILER_PATH)/lib/NAG_Fortran -lf62rts
      endif

**Comment by jedwards4b** [comment]
agreed

**Comment by jedwards4b** [comment]
@fischer-ncar I'll add it to this PR

**Comment by jedwards4b** [comment]
Rerunning tests

**Comment by jedwards4b** [comment]
scripts_regression_tests.py --compiler=nag now passes on both izumi and hobart.

**Pull request merged**
