### PR TITLE
Pio2 fix

### PR DESCRIPTION
**Pull request by jedwards4b**
Fix runtime issues with latest pio2 development

Test suite: cime_developer using pio1 and latest pio2 develop code
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes 
User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by dqwu** [comment]
@jedwards4b 
I tested this fix with latest PIO2 develop branch, the failed 6 cime_develop tests can pass now.

**Comment by edhartnett** [comment]
OK, awesome. Shall I merge these changes now?

**Comment by dqwu** [comment]
@edhartnett 
Better after that fix is merged to ESMCI/cime master (should make sure it does not break tests built with PIO1)

**Comment by jedwards4b** [comment]
@dqwu in cime the assignee is tasked with doing the merge.

**Pull request merged**
