### PR TITLE
Updated documentation to match new directory structure

### PR DESCRIPTION
**Pull request by agsalin**
Note: This is PR into gh-pages branch.

Updated users guide for new directory structure.

Since many top-level directories were moved down a level, I added another table with
Content of Key Subdirectories (e.g. config/cesm, src/drivers) in the introduction and overview section. Please review.

As Rob suggested, we may want to delay this PR until new CIME gets deployed. 

Test suite: visual check with sphinx
Test baseline: 
Test namelist changes: 
Test status: bit-for-bit

Code review:

### CODE REVIEW

**Comment by mvertens** [comment]
Are we ready to merge this yet?

**Comment by rljacob** [comment]
Not until  both CESM and ACME users are using this version.

**Comment by rljacob** [comment]
@agsalin go ahead and merge this.

**Comment by agsalin** [comment]
I committed the changes directly to gh-pages branch. This PR was stale, so I just cherry-picked the one commit I had made months ago, resolved conflicts, and pushed.

**Pull request closed without merging**
