### PR TITLE
Add bless logging capability

### PR DESCRIPTION
**Pull request by jgfouca**
Also, some minor cleanup in bless_test_results.

Test suite: scripts_regression_tests, extensive by-hand testing
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes [CIME Github issue #]

User interface changes?: New bless_log file in baseline dirs

Update gh-pages html (Y/N)?: N

Code review: @jedwards4b @billsacks

### CODE REVIEW

**Comment by rljacob** [comment]
Where will this "bless_log" live?  How are multiple blesses on multiple machines handled?

**Comment by jgfouca** [comment]
@billsacks I could turn off this feature for CESM if you guys want. I was thinking it may not make sense with your workflow. That may make more sense than trying to fix the problems you raised, both of which are legitimate.

@rljacob it will live in the baseline directory, so $BASELINE_ROOT/$COMPILER/$CASENAME/bless_log

Each blessing adds a line to this file.

**Comment by billsacks** [comment]
Yeah, I probably won't use it in my own workflow. No strong opinion as to whether you turn it off or leave it on without much value. @jedwards4b do you have any feelings about this?

**Comment by rljacob** [comment]
Can multiple people bless a test?  And if so can they each write to this file?

**Comment by jgfouca** [comment]
@rljacob , yep! Sane maintenance already requires that the baseline area be group writable.

**Comment by jedwards4b** [comment]
I think that the cam developers may use it in their workflow. @cacraigucar care to weigh in?

**Comment by cacraigucar** [comment]
CAM's workflow is that we generate a new baseline directory with the CAM tag name each time we make a tag using bless_test_results.  Since we are naming the directory ourselves when we use bless_test_results and this naming is not error prone, I don't feel like we'd need the sha information as well.  So as long as this doesn't impact our baseline comparisons or running bless_test_results, I don't have an opinion on what is done with this new log.

**Comment by jgfouca** [comment]
Sounds like this should be an ACME-only feature.

**Comment by billsacks** [comment]
> Sounds like this should be an ACME-only feature.

Yes, probably, if the logic for making it acme-only is easy and limited. If it involves logic in a number of places, though, I'd be inclined to keep it active always and we'll just ignore it in cesm.

**Comment by jgfouca** [comment]
@billsacks , nope, it's trivial.

**Comment by billsacks** [comment]
Okay, sounds good, thanks.

**Comment by jgfouca** [comment]
OK, this is ready.

**Comment by billsacks** [comment]
Okay, I'm happy with this now, thanks.

**Comment by jgfouca** [comment]
I'm going to go ahead and click the button for Jim, I have another PR that needs this.

**Pull request merged**
