### PR TITLE
Buildsub

### LINKED ISSUE #3532: python logger debug statements aren't printed when used in "buildlib".
While updating CAM's buildlib script, it was found that `logger.debug` statements are not printed to any file in the case, even if the log level is set to debug in buildlib itself.  However, `logger.info` statements do make it to the `*.bldlog.*` file. 

This seems to hold even if the `DEBUG` variable is set to True in `env_build.xml`, and if the `--debug` flag is provided to `case.build`.  It also doesn't seem to be CAM-specific, as the same behavior happens in CLM's buildlib script as well (although I didn't test other components' buildlib scripts).

I specifically used the CESM `release-cesm2.1.3` tag on Izumi to run these tests (although I ran a similar test on Cheyenne with the same results).

Any ideas as to why this is the happening would be greatly appreciated.  Thanks!

### PR DESCRIPTION
**Pull request by jedwards4b**
Allows threads to call run_sub_or_cmd for calling buildlib 

Test suite: scripts_regression_tests.py 
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes #3532 

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by jgfouca** [comment]
Didn't @WesCoomber 's solution to #3532 work?

Also, I'm a little worried about how we can trust that components' buildlib scripts won't make thread unsafe changes. We would need to somehow verify that none of them did any chdir or modified os.environ.

**Comment by jgfouca** [comment]
OK, I just read some of the comments on #3532 , so I guess Wesley's solution didn't work for you guys. He did some testing and it looks to me like it should work, so I'd like to understand why his solution didn't work before we pursue using run_or_sub_cmd, which raises a lot of complex issues.

**Comment by jedwards4b** [comment]
I think that you can test this all inside cime - just add a logger.debug or logger.info call inside one of the data model buildlib scripts.

**Comment by jgfouca** [comment]
I'm pretty sure that's exactly what @WesCoomber tested. Wes, can you chime in here?

**Comment by WesCoomber** [comment]
@jgfouca I spent some time checking my tests for the subprocess feature, #3539, and they still work on Melvin. So I am following up in the original issue thread with the steps I used to verify the feature is working correctly and we will figure out the issue on the other machines. Passing the same logging options as was used for current executable to subprocesses should work.

**Pull request closed without merging**
