### PR TITLE
Start adding option for MizuRoute

### LINKED ISSUE #3495: Logic for config_grids with both compset= and not_compset= is wrong...
The logic in scripts/lib/CIME/XML/grids.py for when both compset= and not_compset= is wrong. This is demonstrated for example with (the somewhat screwy example C96_C96_mg17 grid).

> ./create_test SMS_D_Ld9.C96_C96_mg17.I2000Clm50Sp.cheyenne_intel.clm-default -r . --no-build
> Testnames: ['SMS_D_Ld9.C96_C96_mg17.I2000Clm50Sp.cheyenne_intel.clm-default']
> Using project from .cesm_proj: P93300606
> Creating test directory /glade/work/erik/ctsm_fv3/cime/scripts/SMS_D_Ld9.C96_C96_mg17.I2000Clm50Sp.cheyenne_intel.clm-default.20200422_095606_rtqo4w
> RUNNING TESTS:
>   SMS_D_Ld9.C96_C96_mg17.I2000Clm50Sp.cheyenne_intel.clm-default
> Starting CREATE_NEWCASE for test SMS_D_Ld9.C96_C96_mg17.I2000Clm50Sp.cheyenne_intel.clm-default with 1 procs
> Finished CREATE_NEWCASE for test SMS_D_Ld9.C96_C96_mg17.I2000Clm50Sp.cheyenne_intel.clm-default in 0.341601 seconds (FAIL). [COMPLETED 1 of 1]
>     Case dir: /glade/work/erik/ctsm_fv3/cime/scripts/SMS_D_Ld9.C96_C96_mg17.I2000Clm50Sp.cheyenne_intel.clm-default.20200422_095606_rtqo4w
>     Errors were:
>         ERROR: grid alias C96_C96_mg17 not valid for compset 2000_DATM%GSWP3v1_CLM50%SP_SICE_SOCN_MOSART_CISM2%NOEVOLVE_SWAV_SIAC_SESP
> 
> At test-scheduler close, state is:
> FAIL SMS_D_Ld9.C96_C96_mg17.I2000Clm50Sp.cheyenne_intel.clm-default (phase CREATE_NEWCASE)
>     Case dir: /glade/work/erik/ctsm_fv3/cime/scripts/SMS_D_Ld9.C96_C96_mg17.I2000Clm50Sp.cheyenne_intel.clm-default.20200422_095606_rtqo4w
> test-scheduler took 0.402869939804 seconds

When I fix the logic with the following change it works...

``` python
diff --git a/scripts/lib/CIME/XML/grids.py b/scripts/lib/CIME/XML/grids.py
index 5bfe1c2a0..2947f283b 100644
--- a/scripts/lib/CIME/XML/grids.py
+++ b/scripts/lib/CIME/XML/grids.py
@@ -111,7 +111,7 @@ def _read_config_grids(self, name, compset, atmnlev, lndnlev):
                 if compset_attrib and not_compset_attrib:
                     compset_match = re.search(compset_attrib, compset)
                     not_compset_match = re.search(not_compset_attrib, compset)
-                    if compset_match is not None and not_compset_match is not None:
+                    if compset_match is not None and not_compset_match is None:
                         foundcompset = True
                         model_gridnode = node
                         logger.debug("Found match for {} with compset_match {} and not_compset_match {}"
```

### LINKED ISSUE #3526: Add a new r05_amazon grid for ROF components
We'd like to add a new grid for ROF components to run over the same region as the 5x5_amazon regional grid that is used for CTSM. We want this primarily for testing simple regional grids for mizuRoute. It'll also allow us to do CTSM/ROF configurations with very small PE counts and even a single processor with mpi-serial.

I propose this will be called 

r05_amazon

It's on the half-degree grid, but only over the 5x5_amazon region that is used by CTSM. This grid would only be allowed for either stand-alone ROF configurations or ROF with CTSM and DATM.

### LINKED ISSUE #3528: Start adding support for mizuRoute in CIME
We'd like to start adding support for mizuRoute in cime. Minimally this means CIME needs to know where the mizuRoute cime_config files are and what the default resolution is for cime. In time there might also be mizuRoute specific grids that need support.

### PR DESCRIPTION
**Pull request by ekluzek**
Changes to start adding support for mizuRoute in CESM

Test suite: SMS_D_P1x1_Vnuopc_Ld5.5x5_amazon_r05.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default 
Test status: bit for bit
Requires a branch for CMEPS and mizuroute as well as CTSM.

Fixes #3495 
Fixes #3528 
Fixes #3526 

User interface changes?: New component added for cesm

Update gh-pages html (Y/N)?: N

Code review:

### CODE REVIEW

**Comment by fischer-ncar** [comment]
@ekluzek can you do a PR for ESCOMP/cesm with the required CMEPS branch.  
Thanks

**Comment by ekluzek** [comment]
> @ekluzek can you do a PR for ESCOMP/cesm with the required CMEPS branch.
> Thanks

Should I point to my branch? Or wait until the CMEPS change is updated to include it?

**Comment by fischer-ncar** [comment]
What until CMEPS is updated.

**Comment by ekluzek** [comment]
Can this be moved to master now? It would help with my work with @mvertens and nuopc for mizuroute.

**Comment by ekluzek** [comment]
Awesome. Thanks @jedwards4b

**Pull request merged**
