### PR TITLE
remove hardcoded compclasses

### LINKED ISSUE #1170: get_timing.py specifies component classes by hand
Are lines like this:
`for k in ['CPL', 'GLC', 'WAV', 'LND', 'ROF', 'ICE', 'ATM', 'OCN']:`
appropriate in get_timing.py? They prevent get_timing from automatically picking up new component types (e.g., ESP).

### PR DESCRIPTION
**Pull request by jedwards4b**
Removes some lingering hardcoded lists of COMP_CLASSES and uses get_values instead
Test suite: scripts_regression_tests.py
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes #1170 

User interface changes?: 

Code review:

### CODE REVIEW

**Comment by gold2718** [comment]
Did you test all of these modified scripts? I don't think scripts_regression_tests.py tests them all (e.g., ncr).

**Comment by jedwards4b** [comment]
Testing of ncr indicates that it didn't work before this PR.   Would you like me to jump down this rabbit hole?

**Comment by gold2718** [comment]
Well, it sort of says that our testing program is not very robust. At the very least, you should document the status in this PR.
How about the other tests you changed? Were they all tested? Please document that.

**Comment by jedwards4b** [comment]
Rabbit hole jumping ... tomorrow.

**Comment by fischer-ncar** [comment]
I merged it so I could run the cesm2_0_alpha06g overnight.

**Comment by gold2718** [comment]
Why was this PR required? We always seem to be rushing around and now we have code in master which either has not been tested or at the least has tests which are undocumented.
What's the rush?

**Comment by fischer-ncar** [comment]
I messed up.  I thought Jim told be to go ahead and make a tag with this PR.  It was really without
this PR.

**Comment by fischer-ncar** [comment]
I reverted this PR, but I'm not seeing a simple way to reopen #1210.

**Comment by rljacob** [comment]
Also you'll need to "revert the revert" when you finally put this branch on master.

**Comment by fischer-ncar** [comment]
Which is better, to "revert the revert", or make a new PR?

**Pull request merged**
