### PR TITLE
Remove GPU options from the Python workflow and move them to XML files for CESM

### PR DESCRIPTION
**Pull request by sjsprecious**
As discussed in https://github.com/ESMCI/cime/pull/4687, it is better remove the GPU options from the Python workflow in CIME and use XML files instead to configure them for CESM.

This PR does this and it works for CESM CPU & GPU runs according to my tests on Derecho.

The general build procedure for building a CESM GPU run on Derecho now looks like (the other machines can modify the settings for their specific hardware accordingly):
```
1. create a new case as normal
2. go to the case directory
3. ./xmlchange GPU_TYPE=a100
4. ./xmlchange OPENACC_GPU_OFFLOAD=TRUE
5. ./xmlchange OVERSUBSCRIBE_GPU=TRUE
6. ./xmlchange NGPUS_PER_NODE=4
7. ./case.setup
8. ./case.build
```

It should work together with the following PRs:
- CMEPS: https://github.com/ESCOMP/CMEPS/pull/512
- ccs_config_cesm: https://github.com/ESMCI/ccs_config_cesm/pull/189

### CODE REVIEW

**Review by jedwards4b — APPROVED** [review]

**Comment by jedwards4b** [comment]
pylint errors to correct:

```
************* Module CIME.XML.env_mach_pes
CIME/XML/env_mach_pes.py:47:8: W0613: Unused argument 'oversubscribe_gpu' (unused-argument)
************* Module CIME.case.case_setup
CIME/case/case_setup.py:415:24: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
CIME/case/case_setup.py:427:20: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
```

**Comment by sjsprecious** [comment]
Thanks @jedwards4b . I have fixed the pylint error. But it looks like there are still two errors left:
```
Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted CIME/case/case_setup.py
```
Could you tell me how to fix these errors?

**Comment by jedwards4b** [comment]
The easiest way is to install pre-commit and use it locally.
You can install it from pip, or use mine: /glade/u/home/jedwards/.local/bin/pre-commit
from your cime directory: pre-commit run
This should reformat case_setup.py then you can commit again.

**Comment by jasonb5** [comment]
@sjsprecious Run `pre-commit run -a`, this should check all the files and fix any issues.

**Comment by sjsprecious** [comment]
Thanks @jasonb5 . I have fixed them with Jim's help.

**Comment by jedwards4b** [comment]
@sjsprecious I noticed that you only tested this for e3sm - the cesm version of the [config_machines xsd](https://github.com/ESMCI/cime/blob/master/CIME/data/config/xml_schemas/config_machines_version3.xsd#L65) file has not been updated to reflect the change.

**Comment by sjsprecious** [comment]
Thanks @jedwards4b for catching this bug. I will work on a PR to fix it for CESM shortly.

**Pull request merged**
