### PR TITLE
Remove all support for legacy config_compilers.xml system

### PR DESCRIPTION
**Pull request by jgfouca**
Not every day that we get to remove 3000 lines of code from CIME!

The new macro system has been in place for a year and I doubt config_compilers.xml has been kept in-sync with the cmake_macros so is likely not usable anyway.

Test suite: scripts_regression_tests
Test baseline:
Test namelist changes:
Test status: bit for bit

Fixes [CIME Github issue #]

User interface changes?:

Update gh-pages html (Y/N)?:

### CODE REVIEW

**Review by billsacks — APPROVED** [review]
Thanks for this! I haven't looked at the details, but I approve of doing this cleanup / removal if others do. I don't feel a need to review the details.

**Review by jedwards4b — APPROVED** [review]

**Comment by jedwards4b** [comment]
@jgfouca you merged with a failing test???

**Comment by jgfouca** [comment]
@jedwards4b am I missing something? I saw all passed and one skip

**Comment by jedwards4b** [comment]
Screen Shot 2022-08-10 at 3 06 26 PM

**Comment by jgfouca** [comment]
@jedwards4b , ok I must have no refreshed my browser or something. I will fix.

**Pull request merged**
