### PR TITLE
Update for UFS app

### PR DESCRIPTION
**Pull request by uturuncoglu**
This PR aims to update UFS app as a part of unification of different applications such as S2S, MR-Weather and HAFS.

Test suite: 
**1.** ./scripts/tests/scripts_regression_tests.py** is run and has two fails
```
test_cime_case_test_custom_project (__main__.K_TestCimeCase) ... FAIL
```
```
======================================================================
FAIL: test_a_createnewcase (__main__.J_TestCreateNewcase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts/tests/scripts_regression_tests.py", line 396, in test_a_createnewcase
    run_cmd_assert_result(self, "./case.st_archive --test-all", from_dir=testdir)
  File "./scripts/tests/scripts_regression_tests.py", line 70, in run_cmd_assert_result
    test_obj.asse
```

```
----------------------------------------------------------------------
Ran 158 tests in 5788.877s

FAILED (failures=2, skipped=13)
```

**2.** qcmd -l walltime=4:00:00 -- ./create_test --xml-testlist ../src/drivers/nuopc/cime_config/testdefs/testlist_drv.xml --xml-machine cheyenne --xml-category nuopc --compare aug19 --baseline-root /glade/p/cesmdata/cseg/cmeps_baselines
```
  ERS_Vnuopc_Ln5.f19_f19_mg17.F2000Nuopc.cheyenne_intel.cam-nuopc_cap (Overall: NLFAIL) details:
    FAIL ERS_Vnuopc_Ln5.f19_f19_mg17.F2000Nuopc.cheyenne_intel.cam-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ln9_N3.f19_g17_rx1.A.cheyenne_intel TPUTCOMP Error: Computation time increase > 25 pct from baseline
    FAIL SMS_Vnuopc_Ld1_N3.f19_g17_rx1.A.cheyenne_intel TPUTCOMP Error: Computation time increase > 25 pct from baseline
  SMS_Vnuopc_Ln5.f19_f19_mg17.F2000Nuopc.cheyenne_intel.cam-nuopc_cap (Overall: NLFAIL) details:
    FAIL SMS_Vnuopc_Ln5.f19_f19_mg17.F2000Nuopc.cheyenne_intel.cam-nuopc_cap NLCOMP
```
Test baseline: aug19
Test namelist changes: No
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by jedwards4b** [comment]
FAIL: test_a_createnewcase (__main__.J_TestCreateNewcase) 

This is a fundamental test, it is unacceptable that it would fail.

**Comment by uturuncoglu** [comment]
@jedwards4b How can I create a test that could reproduce this. I run whole CESM test suite without any problem. Let me know if you have any ideas.

**Comment by jedwards4b** [comment]
scripts_regression_tests.py J_TestCreateNewcase.test_a_createnewcase will run the individual test - I am running it now on your branch.

**Comment by uturuncoglu** [comment]
Okay, let me know if you want me to test something.

**Comment by jedwards4b** [comment]
./scripts_regression_tests.py J_TestCreateNewcase.test_a_createnewcase

Testing commit 36cbc603973259000405df3d55b40d2bfcb25a4a
Using cime_model = cesm
Testing machine = cheyenne
Test root: /glade/scratch/jedwards/scripts_regression_test.20200902_094808
Test driver: mct

test_a_createnewcase (__main__.J_TestCreateNewcase) ... ok

**Comment by jedwards4b** [comment]
When run with CIME_DRIVER=ufs I get an error:
======================================================================
FAIL: test_a_createnewcase (__main__.J_TestCreateNewcase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts_regression_tests.py", line 373, in test_a_createnewcase
    run_cmd_assert_result(self, "./create_newcase %s"%(args), from_dir=SCRIPT_DIR)
  File "./scripts_regression_tests.py", line 70, in run_cmd_assert_result
    test_obj.assertEqual(stat, expected_stat, msg=msg)
AssertionError: 1 != 0 : 
COMMAND: ./create_newcase  --case /glade/scratch/jedwards/scripts_regression_test.20200902_095432/TestCreateNewcase/testcreatenewcase --compset X --output-root /glade/scratch/jedwards/scripts_regression_test.20200902_095432/TestCreateNewcase --handle-preexisting-dirs=r  --res f19_g17 
FROM_DIR: /glade/work/jedwards/sandboxes/cesm2_x_alpha/cime/scripts
SHOULD HAVE WORKED, INSTEAD GOT STAT 1
OUTPUT: Compset longname is 2000_XATM_XLND_XICE_XOCN_XROF_XGLC_XWAV
Compset specification file is /glade/work/jedwards/sandboxes/cesm2_x_alpha/cime/src/drivers/nuopc/cime_config/config_compsets.xml
Automatically adding SESP to compset
ERRPUT: ERROR: no alias f19_g17 defined

**Comment by uturuncoglu** [comment]
I am testing after merging with master. Do you think it is the reason of failure? My sandbox is in /glade/u/home/turuncu/NCAR/CESM_test/cime

**Comment by uturuncoglu** [comment]
I tested under CESM app and I did not define CIME_DRIVER=ufs.

**Pull request merged**
