### PR TITLE
Indent consistently

### PR DESCRIPTION
**Pull request by jedwards4b**
Whitespace cleanup and remove svn tags from fortran.  

Test suite: scripts_regression_tests.py
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes 

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review: billsacks

### CODE REVIEW

**Comment by billsacks** [comment]
There are still changes here that are not just whitespace changes. Can you please recreate this to truly have nothing but whitespace changes?

**Comment by billsacks** [comment]
Following discussion with @jedwards4b I see that there are 4 types of changes here:

1. Whitespace changes

2. Removing some comment lines (mostly or entirely related to old svn tags)

3. On `end type` and `end interface` adding the name of what's ended (e.g., `end interface foo`)

4. Removing some `#ifdef AIX` lines.

Based on discussion with @jedwards4b I can accept (2) and (3) being folded into this PR, but would like (4) done separately, since this potential behavior change could get lost in this big commit.

@rljacob are you comfortable with this?

**Comment by jedwards4b** [comment]
@billsacks I've added back the AIX directives.

**Comment by billsacks** [comment]
Thanks a lot @jedwards4b . I'm happy with this now. I'm just waiting to approve it to make sure that @rljacob is comfortable with this.

**Comment by rljacob** [comment]
Didn't we already go through a big white-space removal in CIME?

**Comment by billsacks** [comment]
> Didn't we already go through a big white-space removal in CIME?

If I recall, that was removing trailing white space. This one changes indentation in fortran and C code.

**Comment by billsacks** [comment]
For the record, here are the indentation levels @jedwards4b used, according to https://github.com/ESMCI/cime/pull/2181#issuecomment-355192388

f90-associate-indent = 2
f90 continuation indent = 5
f90 critical indent = 2
f90 do indent = 3
f90 if indent = 3
f90 program indent = 2
f90 type indent = 3

**Pull request merged**
