### PR TITLE
Cori port2

### PR DESCRIPTION
**Pull request by jedwards4b**
Port to corip1, partial port to corip2 for cime-maint5.1
Fix for scripts_regression_tests cmake tests on Cray system

Test suite: scripts_regression_tests
Test baseline: 
Test namelist changes: 
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?: 

Code review:

### CODE REVIEW

**Comment by ndkeen** [comment]
OK, I don't know how to get the branch.

git clone  git@github.com:ESMCI/cime cime5-corib
cd cime5-corib/

cori05% git checkout jedwards4b/cime
error: pathspec 'jedwards4b/cime' did not match any file(s) known to git.
cori05% git checkout cori_port2
error: pathspec 'cori_port2' did not match any file(s) known to git.

**Comment by jayeshkrishna** [comment]
@ndkeen : Check out the "command line instructions" next to the "Merge pull request" (green merge button)

**Comment by ndkeen** [comment]
well then what is git@github.com:ESMCI/cime?

**Comment by jedwards4b** [comment]
```
git remote add jimsfork https://github.com/jedwards4b/cime.git
git fetch jimsfork
git checkout cori_port2
```

**Comment by rljacob** [comment]
A fork is just a git clone managed by github.  In git, all clones are equal.  By convention, we treat git@github.com:ESMCI/cime as THE master that all development is targeted towards.

**Comment by jedwards4b** [comment]
I don't understand the commit log on this - it has a lot of commits that are not directly related to this change.   I am going to close this and try to get a clean branch for merge.

**Pull request closed without merging**
