### PR TITLE
Add ParamGen to CIME

### LINKED ISSUE #4266: Want to bring ParamGen tool into CIME
A new python-based namelist and runtime parameter generation tool, currently called ParamGen, has been developed by @alperaltuntas for use with MOM, and has recently been implemented in the developmental version of SIMA (CAMDEN).  There was also some interest in using it in CTSM as well (@ekluzek).  You can find a notebook describing ParamGen in more detail here:

https://github.com/nusbaume/cime/blob/ParamGen/CIME/ParamGen/README.ipynb

Given that this tool will be cross-component, it seemed to make sense to put the relevant code into CIME.  I'll open a PR for it soon once I have made sure that all of the tests pass, I just wanted to make an issue first to put it on peoples' radar.

### PR DESCRIPTION
**Pull request by nusbaume**
Adds the ParamGen fortran namelist and runtime parameter generator to CIME. 

FYI @alperaltuntas @ekluzek  

Test suite:  scripts_regression_tests.py (assuming I ran it correctly).
Test baseline: N/A
Test namelist changes: N/A
Test status: N/A

Fixes #4266 

User interface changes?: N

Update gh-pages html (Y/N)?: N

### CODE REVIEW

**Comment by jedwards4b** [comment]
@nusbaume you'll want to add the tests to the scripts_regression_tests.py you may want to consult with @jasonb5 on the best way to do that.

**Comment by nusbaume** [comment]
Thanks @jedwards4b!  

@jasonb5 It looks like for `unittest` tests I just need to add a new `test_unit_paramgen.py` file to `CIME/tests` that contain all of the relevant tests, and that the doctests should be handled automatically by the `test_unit_doctest.py` script (as the ParamGen code is inside the `CIME` directory).  Is that correct, or do I need to do something different?

**Comment by rljacob** [comment]
Is placing this under cime/CIME the right location?  In general, if we add python packages directly to the repo, would they always go under cime/CIME ?

**Comment by nusbaume** [comment]
@rljacob I am happy to put it wherever you all feel is the best location.  I can just say that the original reason I put it in `cime/CIME` is because we use it as a replacement for the `nmlgen.py` routines, which are also located in `cime/CIME`, inside of our component's `cime_config/builnml` script.

**Comment by rljacob** [comment]
I don't have a strong opinion on where is the best location but wanted to raise the issue.  Current location is fine.

**Comment by nusbaume** [comment]
@jasonb5 Just pinging you again to see if my plan above for implementing the python unit tests is correct, or if I should do something different.  Thanks!

**Comment by jasonb5** [comment]
@nusbaume Apologies still catching up from being out last week.
I would suggest moving the tests from `cime/CIME/ParamGen/tests` to `cime/CIME/tests/test_unit_paramgen.py` as noted from your earlier comment and you are correct `test_unit_doctest.py` will automatically run all doctests.

**Comment by nusbaume** [comment]
@jasonb5 Great, thanks for verifying for me!  I think this PR is ready to go for review now (assuming all the tests pass).  Thanks again!

**Review by jedwards4b — APPROVED** [review]

**Review by jasonb5 — APPROVED** [review]
@nusbaume @jedwards4b This PR looks good now. Thanks.

**Pull request merged**
